#!/usr/bin/env python3
"""Require, validate and record a human review reference for a production apply.

WHY THIS FILE EXISTS (owner decision, 2026-08-11)
-------------------------------------------------
This replaces `scripts/production_apply_model_review.py`, which called the
Anthropic API on every production-apply attempt and billed for it. That paid
review produced exactly one substantive verdict in its entire life (batch B10d,
issue #788) and not one of its findings was ever confirmed as a real defect
(adjudicated in issue #800). Meanwhile every genuine defect found on 2026-08-11
was found by an agent in Claude Code reproducing behaviour. Code review for
shared-db is therefore done in Claude Code, and the lane no longer pays a model
to duplicate it.

WHAT MUST NOT BE LOST
---------------------
The deleted step had one property worth more than its verdict: **an apply could
not proceed without a review, and nobody could silently skip it.** Deleting the
job outright would turn that into an honour system, and a future session under
promotion pressure would skip it with nothing to notice. That is precisely the
failure class this repo spent 2026-08-11 removing -- three stacked faults each
hidden by a green tick earned by nothing (#617, PRs #779 / #783 / #787).

So the gate survives with the API call removed. The operator must supply
`review_reference`: a URL or repository path pointing at where the review was
actually performed. This file FAILS CLOSED when that is missing, blank, or not a
plausible reference, and echoes the accepted value into the job summary and the
apply evidence artifact so the audit trail records who reviewed what and where.

THERE IS DELIBERATELY NO BYPASS.
No default that satisfies the check, no environment variable that skips it, no
`continue-on-error` on the calling step, no "if unset, warn and continue". A
missing reference fails the run exactly as a failed review did. This check is
cheap, so there is never a cost argument for skipping it.

WHAT THIS CHECK CAN AND CANNOT PROVE
------------------------------------
It proves a reference was RECORDED, not that a good review happened behind it.
That is honest and it is the point: it makes skipping the review a visible,
deliberate act of writing a false reference, rather than an invisible omission.
The human approver on `environment: production` reads the reference and is the
one who judges it. Do not oversell this step in any summary text.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

# Values people type when they mean "I did not do this". Accepting any of them
# would reduce the gate to a formality, so they are refused by name. Compared
# case-insensitively against the whole stripped value.
PLACEHOLDERS = {
    "-",
    ".",
    "//",
    "n/a",
    "na",
    "none",
    "nil",
    "null",
    "no",
    "nope",
    "tbd",
    "todo",
    "to do",
    "skip",
    "skipped",
    "pending",
    "later",
    "x",
    "xxx",
    "test",
    "n\\a",
    "not applicable",
    "not needed",
    "no review",
    "see above",
    "asdf",
}

# A repository-relative path is accepted only from the reviews directory. Any
# other path would let "README.md" pass, which proves nothing.
REVIEWS_DIR = ".ai/reviews/"

MIN_LENGTH = 12

BANNER = (
    "<!-- generated by scripts/production_apply_review_reference.py -->\n\n"
)


def annotate(level: str, message: str) -> None:
    """Emit a GitHub Actions annotation (harmless plain text off-runner)."""
    safe_print(f"::{level}::{message}")


def safe_print(text: str) -> None:
    """Print text a non-UTF-8 console may not be able to encode.

    Never raises. The predecessor script lost a completed review to a
    UnicodeEncodeError on a cp1252 console; the same trap is avoided here.
    """
    stream = sys.stdout
    encoding = getattr(stream, "encoding", None) or "utf-8"
    try:
        stream.write(text + "\n")
    except UnicodeEncodeError:
        stream.write(text.encode(encoding, errors="replace").decode(encoding) + "\n")
    stream.flush()


def publish(text: str, heading: str) -> None:
    """Write the durable evidence FIRST, then the console.

    Order matters: an artifact and a job summary survive the run; the console
    does not. Writing them first means no console problem can destroy the
    record.
    """
    out = BANNER + text + "\n"
    temp = os.environ.get("RUNNER_TEMP")
    if temp:
        Path(temp, "production-review-reference.md").write_text(out, encoding="utf-8")
    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with open(summary, "a", encoding="utf-8") as handle:
            handle.write(f"## {heading}\n\n" + out)
    safe_print(out)


def binding_tokens(sha: str, allowlist: str) -> list[str]:
    """Strings that tie a review to THIS apply: the commit and each version.

    The short SHA is included because humans quote seven characters, not forty.
    A SHA under 7 characters contributes NOTHING -- matching a review file on
    three or four hex characters would bind nothing at all. That is deliberate,
    and it is safe only because `validate` REFUSES an apply whose token list
    comes back empty. Do not relax the length rule; do not remove that refusal.
    """
    tokens: list[str] = []
    sha = (sha or "").strip()
    if len(sha) >= 7:
        tokens.append(sha[:7])
    for part in (allowlist or "").split(","):
        part = part.strip()
        if part:
            tokens.append(part)
    return tokens


def require_binding(tokens: list[str]) -> tuple[bool, str]:
    """Refuse an apply that gives this gate nothing to bind a review TO.

    THE DEFECT THIS CLOSES (found by GLM, reproduced on PR #806, held before
    merge). The content check on a `.ai/reviews/` file used to be written
    `if tokens:` -- so when `REQUESTED_SHA` and `PRODUCTION_ALLOWLIST` were both
    empty, the token list came back empty and the check was SKIPPED ENTIRELY.
    Any unrelated review file was then accepted, `main()` printed
    `Commit: (unknown)` and returned 0. A SHA shorter than seven characters did
    the same thing, because `binding_tokens` only contributes a SHA at
    `len(sha) >= 7`. That is exactly the "an old unrelated review satisfies
    today's apply" hole that was supposedly fixed in d8e77b5, still reachable
    through an empty-token door.

    WHY IT IS FIXED IN THE SCRIPT AND NOT ONLY IN THE WORKFLOW. In practice a
    real apply supplies both values and the guard chain rejects an empty
    allowlist further along, so a live run would have gone red anyway. But both
    inputs are `required: false` at the workflow level, which made this file
    fail-closed BECAUSE OF HOW IT HAPPENS TO BE CALLED rather than because of
    what it asserts. This file's entire purpose is to be the thing that cannot
    be skipped, so it is the last place that pattern may survive. It now stands
    on its own: no caller, present or future, can reach an accept path without
    supplying something to bind to.
    """
    if tokens:
        return True, ""
    return False, (
        "this apply supplied no commit SHA (7+ characters) and no allowlist, so "
        "there is nothing to bind a review to and an unrelated review would be "
        "accepted. Set REQUESTED_SHA and PRODUCTION_ALLOWLIST. This check is "
        "deliberately in the script, not only in the workflow -- do not remove "
        "it and rely on the caller."
    )


def validate(
    raw: str,
    repo: Path | None = None,
    sha: str = "",
    allowlist: str = "",
) -> tuple[bool, str]:
    """Return (accepted, reason). `reason` describes the refusal when False.

    Accepted forms:
      * An absolute https URL with a host AND a non-empty path -- a PR review
        comment, an issue comment, a commit comment, a gist.
      * A repository-relative path under `.ai/reviews/` that EXISTS in the
        checkout AND mentions this apply (the short commit SHA, or one of the
        allowlisted migration versions).

    THE LIMIT OF THIS CHECK, STATED PLAINLY. An independent review of this file
    (Codex, GPT-5.6, on PR chore/review-in-claude-code) made two findings, and
    both are correct:

      1. An invented https URL such as `https://example.com/nope` passes. It
         cannot be otherwise: proving a URL holds a real review means fetching
         it, and fetching things from this lane is precisely the paid, networked
         behaviour the owner removed. The mitigation is human, not mechanical --
         the reference is printed in the job summary that the approver on
         `environment: production` is looking at when they click approve, and
         the summary tells them to open it.
      2. An unrelated OLD file under `.ai/reviews/` used to pass. That one WAS
         fixable offline and is now fixed: a reviews file must mention this
         commit or one of these migration versions, so last month's review of a
         different batch no longer satisfies today's apply.

    Do not "fix" finding 1 by adding an HTTP request. Do not weaken finding 2's
    binding to make a dispatch easier.
    """
    value = (raw or "").strip()

    if not value:
        return False, "no review reference was supplied (the input was empty or whitespace)"

    if "\n" in value or "\r" in value:
        return False, "the review reference must be a single line"

    if value.casefold() in PLACEHOLDERS:
        return False, f"{value!r} is a placeholder, not a review reference"

    if value.startswith(("http://", "https://")):
        parsed = urlparse(value)
        if not parsed.netloc:
            return False, f"{value!r} is not a usable URL (it has no host)"
        # A NON-EMPTY PATH IS REQUIRED. This used to accept a bare host that
        # carried only a query or a fragment, which contradicted the very
        # sentence documenting it; Codex caught the inconsistency. No review
        # lives at `https://github.com/?x=1`.
        if parsed.path.strip("/") == "":
            return False, (
                f"{value!r} points at a bare host with no path -- link the actual "
                "review comment, issue or file"
            )
        if value.startswith("http://"):
            return False, (
                f"{value!r} uses plain http; link the https URL so the reference "
                "cannot be silently rewritten in transit"
            )
        if len(value) < MIN_LENGTH:
            return False, f"{value!r} is too short to be a real reference"
        return require_binding(binding_tokens(sha, allowlist))

    # Normalise a repo path the operator may have typed with backslashes or a
    # leading ./ so a correct reference is not refused on cosmetics.
    # NOTE: `str.lstrip("./")` is WRONG here and was the first bug in this file.
    # It strips a CHARACTER SET, so it eats the leading dot of `.ai/reviews/...`
    # and turns a valid reference into `ai/reviews/...`, which is then refused.
    # Strip the `./` prefix explicitly instead.
    normalised = value.replace("\\", "/")
    while normalised.startswith("./"):
        normalised = normalised[2:]
    normalised = normalised.lstrip("/")
    if not normalised.startswith(REVIEWS_DIR):
        return False, (
            f"{value!r} is neither an https URL nor a path under {REVIEWS_DIR!r}. "
            "Link the PR/issue review comment, or commit the review under "
            f"{REVIEWS_DIR} and name that file."
        )
    if ".." in Path(normalised).parts:
        return False, f"{value!r} escapes the repository with '..'"

    root = repo or Path(os.environ.get("GITHUB_WORKSPACE") or ".")
    target = root / normalised
    if not target.is_file():
        return False, (
            f"{value!r} does not exist in this checkout. A path that is not "
            "there is not evidence of a review."
        )

    # BIND THE FILE TO THIS APPLY. Without this, any review file committed at
    # any time for any batch satisfies every future apply, and the gate decays
    # into "does .ai/reviews/ contain at least one file". The file must name
    # this commit or at least one of the migrations being applied.
    tokens = binding_tokens(sha, allowlist)
    accepted, reason = require_binding(tokens)
    if not accepted:
        return accepted, reason
    body = target.read_text(encoding="utf-8", errors="replace")
    if not any(token in body for token in tokens):
        return False, (
            f"{value!r} exists but does not mention this apply. It must "
            f"name the commit ({tokens[0]}) or at least one allowlisted "
            "migration version, otherwise an old review of a different "
            "batch would satisfy this run."
        )
    return True, ""


def fail(reason: str) -> int:
    body = (
        "**NO REVIEW REFERENCE -- THIS JOB IS FAILING ON PURPOSE.**\n\n"
        f"Cause: {reason}\n\n"
        "Code review for shared-db happens in Claude Code. This lane does not "
        "perform the review; it requires you to record WHERE it was performed, "
        "so the audit trail on this run says who reviewed what.\n\n"
        "Dispatch again with `review_reference` set to one of:\n\n"
        "* the https URL of the PR review comment, issue comment or commit "
        "comment holding the review, or\n"
        f"* a repository path under `{REVIEWS_DIR}` that exists at the applied "
        "commit.\n\n"
        "Do not add a bypass, and do not type a placeholder. A missing "
        "reference fails this run exactly as a failed review did."
    )
    publish(body, heading="Production apply review reference -- MISSING")
    annotate("error", f"Production apply blocked: {reason}")
    sys.stderr.write(f"REVIEW REFERENCE REJECTED: {reason}\n")
    return 1


def main() -> int:
    raw = os.environ.get("REVIEW_REFERENCE", "")
    sha = os.environ.get("REQUESTED_SHA", "").strip() or "(unknown)"
    allowlist = os.environ.get("PRODUCTION_ALLOWLIST", "").strip() or "(unknown)"
    actor = os.environ.get("GITHUB_ACTOR", "").strip() or "(unknown)"

    accepted, reason = validate(
        raw,
        sha=os.environ.get("REQUESTED_SHA", ""),
        allowlist=os.environ.get("PRODUCTION_ALLOWLIST", ""),
    )
    if not accepted:
        return fail(reason)

    value = raw.strip()
    body = (
        "This production apply was reviewed in **Claude Code**, not by an "
        "automated model call in this workflow. The reference below is the "
        "operator's record of where that review lives.\n\n"
        f"* **Review reference:** {value}\n"
        f"* **Dispatched by:** `{actor}`\n"
        f"* **Commit:** `{sha}`\n"
        f"* **Allowlist:** `{allowlist}`\n\n"
        "**What this proves and what it does not.** It proves a reference was "
        "recorded, and -- for a `.ai/reviews/` path -- that the file exists and "
        "names this apply. **This lane did NOT fetch or read the reference**; "
        "doing so would restore the networked, paid behaviour that was removed. "
        "It therefore does NOT prove the review behind it was any good.\n\n"
        "**Approver: open the link above and read it BEFORE you approve.** That "
        "judgement is yours, and nothing in this run has made it for you."
    )
    publish(body, heading="Production apply review reference")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
