#!/usr/bin/env node
import path from 'node:path'; import { fileURLToPath } from 'node:url'; import { validateAll } from './throughput-guard/ledger-lib.mjs'; import { collect } from './catalog-truth.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export const GUARDS={
  'production-migration-guard':{purpose:'prevent unsafe or contradictory production migration batches',owner:'shared-db migration safety'},
  'sidecar-presence':{purpose:'require reviewed post-apply evidence for dynamic SQL risk markers',owner:'shared-db verification'},
  'catalog-verification':{purpose:'verify declared migration outcomes against read-only catalog evidence',owner:'shared-db verification'},
  'reviewer-harness':{purpose:'preserve required independent review coverage and evidence',owner:'AI review tooling'}
};
export const selectAuthoritativeLedgers=(entries,{guard,object=null,issue=null})=>issue?entries.filter(v=>v.resolved_at===null&&v.guard===guard&&v.issue_or_pr===issue&&(!object||v.object===object)):[];
export async function triage({guard,object=null,issue=null,target='both',catalog=collect,repo=root}){const {entries,fixtures}=validateAll(repo);const matches=fixtures.filter(v=>(v.guard===guard||v.id.includes(guard))&&(!object||v.objects?.includes(object)));const historicalLedgers=entries.filter(v=>matches.some(f=>f.ledger_id===v.id));const authoritativeLedgers=(object||issue)?selectAuthoritativeLedgers(entries,{guard,object,issue}):[];const incidentLike=Boolean(object||issue)||matches.some(v=>v.origin==='incident');const meta=GUARDS[guard]??{purpose:'unknown; no purpose inferred',owner:'unknown; route by the named check documentation'};const lines=[`guard=${guard}`,`purpose=${meta.purpose}`,`owner=${meta.owner}`,matches.length?`matches=${matches.map(v=>`${v.id}:${v.expected_verdict}`).join(',')}`:'NO KNOWN MATCH',...(!object&&!issue&&historicalLedgers.length?[`historical_ledger_id=${historicalLedgers.map(v=>v.id).join(',')}`]:[]),authoritativeLedgers.length?`ledger_id=${authoritativeLedgers.map(v=>v.id).join(',')}`:(incidentLike?'LEDGER_MISSING':'ledger_id=none')];let exitCode=0;if(object){const truth=await catalog({identity:object,target,repo});lines.push(JSON.stringify(truth));exitCode=truth.exitCode}lines.push(`proof_command=${authoritativeLedgers[0]?.proof_command??(object?`node scripts/catalog-truth.mjs --target ${target} ${object}`:'run the named guard with its normal evidence output')}`);lines.push(`next_action=${matches.length?'compare the current evidence with the recorded fixture before changing any refusal':incidentLike?'record the minimal blocker stub before calling this diagnosis proved':'keep the diagnosis as a working hypothesis until rerunnable evidence exists'}`);return{output:lines.join('\n'),exitCode}}
export async function main(argv=process.argv.slice(2)){const guard=argv.shift();if(!guard)throw new Error('usage: triage-gate <guard-or-check> [object] [--target ...]');let target='both';let issue=null;const ii=argv.indexOf('--issue');if(ii>=0){issue=argv[ii+1];argv.splice(ii,2)}const i=argv.indexOf('--target');if(i>=0){target=argv[i+1];argv.splice(i,2)}const result=await triage({guard,object:argv[0]??null,issue,target});console.log(result.output);return result.exitCode}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){main().then(c=>process.exitCode=c).catch(e=>{console.error(e.message);process.exitCode=2})}
