-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `itemHeader` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: PLM item master header
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm."itemHeader" (
    item_id_pk integer NOT NULL,
    created_user_fk character varying(20),
    created_time_date timestamp without time zone,
    item_active_status character varying(1),
    discont_status character varying(1),
    mod_time_date timestamp without time zone,
    mod_user_fk character varying(20),
    dsn_ref_num character varying(200),
    item_descr_name character varying(100),
    item_displ_descr_name character varying(40),
    item_length_size numeric,
    item_width_size numeric,
    item_depth_size character varying(50),
    item_weight_size numeric,
    uom_size_fk character varying(8),
    uom_weight_fk character varying(8),
    item_note character varying,
    item_content character varying(20),
    item_avail_status character varying(1),
    item_cbm_size numeric,
    "udf_item_priceA" numeric,
    "udf_item_priceB" numeric,
    "udf_item_priceC" numeric,
    "udf_item_priceD" numeric,
    "udf_item_priceE" numeric,
    "udf_item_priceF" numeric,
    "udf_item_priceG" numeric,
    "udf_item_priceH" numeric,
    item_cost_ext numeric,
    hts_num_ext_fk character varying(16),
    hts2_num_ext_fk character varying(16),
    innerpack_qty integer,
    giftwrap character varying(1),
    base_qty integer,
    carton_length_size numeric,
    carton_width_size numeric,
    carton_depth_size numeric,
    carton_weight_size numeric,
    carton_code_ext character varying(10),
    carton_packtype_fk character varying(20),
    carton_qty integer,
    "AllowedSizes_ext" character varying,
    udf_merchgroup01 character varying(20),
    udf_merchgroup02 character varying(20),
    udf_merchgroup03 character varying(20),
    udf_merchgroup04 character varying(20),
    udf_merchgroup05_fk character varying(20),
    udf_merchgroup06_fk character varying(20),
    udf_merchgroup07_fk character varying(20),
    udf_merchgroup08_fk character varying(100),
    udf_merchgroup09_fk character varying(100),
    udf_merchgroup10_fk character varying(100),
    udf_merchgroup11_fk character varying(20),
    udf_merchgroup12_fk character varying(20),
    udf_merchgroup13_fk character varying(20),
    udf_merchgroup14_fk character varying(20),
    udf_merchgroup15_fk character varying(20),
    udf_merchgroup16_fk character varying(20),
    udf_merchgroup17_fk character varying(20),
    udf_merchgroup18_fk character varying(20),
    udf_merchgroup19_fk character varying(20),
    udf_merchgroup20_fk character varying(20),
    udf_merchgroup21_fk character varying(20),
    udf_merchgroup22_fk character varying(20),
    udf_merchgroup23_fk character varying(20),
    udf_merchgroup24_fk character varying(20),
    udf_merchgroup25_fk character varying(20),
    origin_country_fk character varying(4),
    season_code_fk character varying(20),
    pack_type character varying(20),
    retail_price numeric,
    selling_price numeric,
    mfg_lead_time integer,
    size_explo_code_ext character varying(20),
    size_range_code_ext character varying(20),
    udf_freeform_01 character varying(50),
    udf_freeform_02 character varying(50),
    udf_freeform_03 character varying(50),
    udf_freeform_04 character varying(50),
    udf_freeform_05 character varying(50),
    udf_freeform_06 character varying(50),
    udf_freeform_07 character varying(50),
    udf_freeform_08 character varying(50),
    udf_freeform_09 character varying(50),
    udf_freeform_10 character varying(50),
    udf_freeform_11 character varying(50),
    udf_freeform_12 character varying(50),
    udf_freeform_13 character varying(50),
    udf_freeform_14 character varying(50),
    udf_freeform_15 character varying(50),
    udf_freeform_16 character varying(50),
    udf_freeform_17 character varying(50),
    udf_freeform_18 character varying(50),
    udf_freeform_19 character varying(50),
    udf_freeform_20 character varying(50),
    udf_date01 timestamp without time zone,
    udf_date02 timestamp without time zone,
    udf_date03 timestamp without time zone,
    udf_date04 timestamp without time zone,
    udf_date05 timestamp without time zone,
    udf_date06 timestamp without time zone,
    udf_date07 timestamp without time zone,
    udf_date08 timestamp without time zone,
    udf_date09 timestamp without time zone,
    udf_date10 timestamp without time zone,
    udf_date11 timestamp without time zone,
    udf_date12 timestamp without time zone,
    udf_date13 timestamp without time zone,
    udf_date14 timestamp without time zone,
    udf_date15 timestamp without time zone,
    udf_date16 timestamp without time zone,
    udf_date17 timestamp without time zone,
    udf_date18 timestamp without time zone,
    udf_date19 timestamp without time zone,
    udf_date20 timestamp without time zone,
    udf_int01 integer,
    udf_int02 integer,
    udf_int03 integer,
    udf_int04 integer,
    udf_int05 integer,
    udf_int06 integer,
    udf_int07 integer,
    udf_int08 integer,
    udf_int09 integer,
    udf_int10 integer,
    udf_num01 numeric,
    udf_num02 numeric,
    udf_num03 numeric,
    udf_num04 numeric,
    udf_num05 numeric,
    udf_num06 numeric,
    udf_num07 numeric,
    udf_num08 numeric,
    udf_num09 numeric,
    udf_num10 numeric,
    non_inv_item character varying(1),
    udf_yesno01 character varying(1),
    udf_yesno02 character varying(1),
    udf_yesno03 character varying(1),
    udf_yesno04 character varying(1),
    udf_yesno05 character varying(1),
    udf_yesno06 character varying(1),
    udf_yesno07 character varying(1),
    udf_yesno08 character varying(1),
    udf_yesno09 character varying(1),
    udf_yesno10 character varying(1),
    udf_yesno11 character varying(1),
    udf_yesno12 character varying(1),
    udf_yesno13 character varying(1),
    udf_yesno14 character varying(1),
    udf_yesno15 character varying(1),
    uom_code character varying(8),
    vendor_code_fk character varying(8),
    old_item_num character varying(20),
    "OH_min_qty" integer,
    ds_cat character varying(20),
    compare_price numeric,
    costcomp1 numeric,
    costcomp2 numeric,
    costcomp3 numeric,
    costcomp4 numeric,
    costcomp5 numeric,
    comm_code_ext character varying(10),
    royalty_code_fk character varying(20),
    royalty2_code_fk character varying(20),
    salesper_code_fk character varying(20),
    salesper2_code_fk character varying(20),
    product_manager_fk character varying(20),
    item_num_id character varying(100),
    compan_code_fk integer,
    div_code_fk integer,
    lic_comment character varying,
    lic_compnay character varying,
    lic_sample_no character varying,
    lic_item_desc character varying,
    lic_licensorcode character varying,
    lic_concept_submiteed character varying,
    lic_concept_submitted_date character varying,
    lic_concept_approved character varying,
    lic_concept_approved_date character varying,
    lic_sample_requested character varying,
    lic_sample_requested_date character varying,
    lic_sample_made character varying,
    lic_sample_made_date character varying,
    lic_vendor_sent character varying,
    lic_vendor_sent_date character varying,
    lic_office_received character varying,
    lic_office_received_date character varying,
    lic_office_sent character varying,
    lic_office_sent_date character varying,
    lic_dev_received character varying,
    lic_dev_sample_recv_date character varying,
    lic_dev_sample_sent character varying,
    lic_dev_sample_sent_date character varying,
    lic_prepo_approved character varying,
    lic_prepo_approved_date character varying,
    lic_prepo_rejected character varying,
    lic_prepo_rejected_date character varying,
    lic_brand_assurance_number character varying,
    lic_order_placed character varying,
    lic_order_placed_date character varying,
    lic_concept_rejected character varying,
    lic_concept_rejected_date character varying,
    udfnum01 character varying,
    ref_num character varying,
    productmanager character varying,
    compan_code character varying,
    div_code character varying,
    is_item_active boolean,
    is_item_old boolean,
    udf_merchgroup01_id integer,
    udf_merchgroup02_id integer,
    udf_merchgroup03_id integer,
    udf_merchgroup04_id integer,
    udf_merchgroup05_fk_id integer,
    udf_merchgroup06_fk_id integer,
    udf_merchgroup07_fk_id integer,
    udf_merchgroup08_fk_id integer,
    udf_merchgroup09_fk_id integer,
    udf_merchgroup10_fk_id integer,
    season_code_fk_id integer,
    udf_merchgroup15_fk_id integer,
    tags character varying(500),
    art_piece_id integer,
    lic_tracking_updated_date timestamp with time zone,
    due_date timestamp with time zone,
    item_type_id_fk integer,
    sample_start_date character varying(255)
);

DO $$ BEGIN
  ALTER TABLE ONLY plm."itemHeader"
    ADD CONSTRAINT "itemHeader_pkey" PRIMARY KEY (item_id_pk);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE plm."itemHeader" IS 'PLM item master header';
