-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260310200917
-- Name: 44e7b363_0a0c_407e_a02e_e6331eb31cdc
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
