-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260515115430
-- Name: find_ai_pdf_duplicates_fn
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
