-- Production migration-history marker.
--
-- This migration version is already recorded in production as
-- `restore_popdam_auth_trigger`, but the original SQL was applied outside the
-- canonical shared-db migration flow. Keep this no-op file so Supabase CLI can
-- reconcile local migration history with the production ledger.
