-- Sample Tracking Release B: Flow 1 factory visits.
--
-- Additive only. Nothing in Release A (#975, 20260814130000) is altered.
-- Scope: the ordered plan of factory visits for
-- workflow_type = 'nyo_purchased_factory_reference', its append-only history,
-- the shared-parent lineage of split physical pieces, and one read view.
--
-- Custody truth stays exclusively in dflow.sample_movement. Nothing here may
-- contradict it and nothing here writes around dflow.post_sample_movement.
--
-- No RLS and no grants are added: every dflow relation runs with
-- relrowsecurity = false and dflow tables carry no anon/authenticated grants.
-- That is a deliberate empty set matching Release A, which likewise only
-- REVOKEs. Release B repeats the same REVOKE for the new objects.
BEGIN;

-- ---------------------------------------------------------------------------
-- 1. dflow.sample_piece_lineage - the shared-parent relationship
-- ---------------------------------------------------------------------------
CREATE TABLE dflow.sample_piece_lineage (
  sample_piece_lineage_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_id_fk integer NOT NULL UNIQUE
    REFERENCES dflow.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
  parent_sample_id_fk integer NOT NULL
    REFERENCES dflow.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
  root_sample_id_fk integer NOT NULL
    REFERENCES dflow.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
  piece_quantity integer NOT NULL CHECK (piece_quantity > 0),
  split_reason text NOT NULL CHECK (btrim(split_reason) <> ''),
  split_by_user text NOT NULL CHECK (btrim(split_by_user) <> ''),
  split_by_role text NOT NULL CHECK (btrim(split_by_role) <> ''),
  idempotency_key text NOT NULL CHECK (btrim(idempotency_key) <> ''),
  request_hash text NOT NULL CHECK (btrim(request_hash) <> ''),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sample_piece_lineage_not_own_parent CHECK (sample_id_fk <> parent_sample_id_fk),
  CONSTRAINT sample_piece_lineage_not_own_root CHECK (sample_id_fk <> root_sample_id_fk),
  UNIQUE (split_by_user, idempotency_key)
);

CREATE INDEX sample_piece_lineage_root_idx
  ON dflow.sample_piece_lineage (root_sample_id_fk, sample_id_fk);
CREATE INDEX sample_piece_lineage_parent_idx
  ON dflow.sample_piece_lineage (parent_sample_id_fk);

-- The denormalised root must never drift from the parent chain.
CREATE OR REPLACE FUNCTION dflow.validate_sample_piece_lineage()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_parent_root integer;
BEGIN
  SELECT root_sample_id_fk INTO v_parent_root
  FROM dflow.sample_piece_lineage
  WHERE sample_id_fk = NEW.parent_sample_id_fk;

  IF NOT FOUND THEN
    -- The parent is itself a root: it has no lineage row of its own.
    v_parent_root := NEW.parent_sample_id_fk;
  END IF;

  IF NEW.root_sample_id_fk <> v_parent_root THEN
    RAISE EXCEPTION
      'Piece lineage root % disagrees with the root % of parent sample %',
      NEW.root_sample_id_fk, v_parent_root, NEW.parent_sample_id_fk
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END $$;

CREATE TRIGGER sample_piece_lineage_validate
BEFORE INSERT OR UPDATE ON dflow.sample_piece_lineage
FOR EACH ROW EXECUTE FUNCTION dflow.validate_sample_piece_lineage();

-- ---------------------------------------------------------------------------
-- 2. dflow.sample_factory_visit - the plan
-- ---------------------------------------------------------------------------
-- factory_id carries a real foreign key to dflow."Factory". The legacy
-- dflow.sample.factory_id_fk is an unconstrained integer, but every non-null
-- value already resolves against dflow."Factory"(id) with zero orphans, so a
-- new table has no reason to import that defect. CONSUMER CONSEQUENCE: the
-- tracking API is now rejected (23503) for an unknown factory id instead of
-- storing it.
CREATE TABLE dflow.sample_factory_visit (
  sample_factory_visit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_id_fk integer NOT NULL
    REFERENCES dflow.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
  factory_id integer NOT NULL
    REFERENCES dflow."Factory"(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  visit_order integer NOT NULL CHECK (visit_order > 0),
  provenance text NOT NULL CHECK (provenance IN ('nyo_requested','ningbo_added')),
  state text NOT NULL DEFAULT 'planned' CHECK (state IN (
    'planned','shipped','at_factory','returning','returned',
    'cancelled','not_returned'
  )),
  outbound_shipment_id bigint
    REFERENCES dflow.sample_shipment(sample_shipment_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  return_shipment_id bigint
    REFERENCES dflow.sample_shipment(sample_shipment_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  requested_by_user text NOT NULL CHECK (btrim(requested_by_user) <> ''),
  requested_by_role text NOT NULL CHECK (btrim(requested_by_role) <> ''),
  shipped_at timestamptz,
  factory_received_at timestamptz,
  returned_at timestamptz,
  closed_at timestamptz,
  idempotency_key text NOT NULL CHECK (btrim(idempotency_key) <> ''),
  request_hash text NOT NULL CHECK (btrim(request_hash) <> ''),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (requested_by_user, idempotency_key),
  CONSTRAINT sample_factory_visit_shipped_needs_outbound CHECK (
    state NOT IN ('shipped','at_factory','returning','returned')
    OR outbound_shipment_id IS NOT NULL),
  CONSTRAINT sample_factory_visit_shipped_needs_time CHECK (
    state NOT IN ('shipped','at_factory','returning','returned')
    OR shipped_at IS NOT NULL),
  CONSTRAINT sample_factory_visit_returned_needs_return CHECK (
    state <> 'returned'
    OR (return_shipment_id IS NOT NULL AND returned_at IS NOT NULL)),
  CONSTRAINT sample_factory_visit_receipt_after_ship CHECK (
    factory_received_at IS NULL OR shipped_at IS NOT NULL),
  CONSTRAINT sample_factory_visit_closed_matches_state CHECK (
    (closed_at IS NOT NULL) = (state IN ('returned','cancelled','not_returned')))
);

-- A physical piece can be at only one factory at a time. Two pieces of one
-- root may be at two factories at once - that is what lineage is for.
CREATE UNIQUE INDEX sample_factory_visit_one_active_uniq
  ON dflow.sample_factory_visit (sample_id_fk)
  WHERE state IN ('shipped','at_factory','returning');

-- Order is unique among live visits. Cancelled visits free their slot, which
-- is what makes reorder possible without renumbering history.
CREATE UNIQUE INDEX sample_factory_visit_order_uniq
  ON dflow.sample_factory_visit (sample_id_fk, visit_order)
  WHERE state <> 'cancelled';

CREATE INDEX sample_factory_visit_factory_queue_idx
  ON dflow.sample_factory_visit (factory_id, state, visit_order);

CREATE INDEX sample_factory_visit_sample_state_idx
  ON dflow.sample_factory_visit (sample_id_fk, state, visit_order);

-- Only Flow 1 samples may have a factory visit plan.
CREATE OR REPLACE FUNCTION dflow.validate_sample_factory_visit()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_workflow_type text;
BEGIN
  SELECT workflow_type INTO v_workflow_type
  FROM dflow.sample_workflow
  WHERE sample_id_fk = NEW.sample_id_fk;

  IF NOT FOUND THEN
    RAISE EXCEPTION
      'Sample % has no workflow row; factory visits are Flow 1 only', NEW.sample_id_fk
      USING ERRCODE = '23514';
  END IF;

  IF v_workflow_type <> 'nyo_purchased_factory_reference' THEN
    RAISE EXCEPTION
      'Factory visits require workflow_type nyo_purchased_factory_reference, sample % is %',
      NEW.sample_id_fk, v_workflow_type
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END $$;

CREATE TRIGGER sample_factory_visit_validate
BEFORE INSERT OR UPDATE OF sample_id_fk ON dflow.sample_factory_visit
FOR EACH ROW EXECUTE FUNCTION dflow.validate_sample_factory_visit();

CREATE OR REPLACE FUNCTION dflow.touch_sample_factory_visit_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

CREATE TRIGGER sample_factory_visit_touch
BEFORE UPDATE ON dflow.sample_factory_visit
FOR EACH ROW EXECUTE FUNCTION dflow.touch_sample_factory_visit_updated_at();

-- ---------------------------------------------------------------------------
-- 3. dflow.sample_factory_visit_event - append-only history
-- ---------------------------------------------------------------------------
CREATE TABLE dflow.sample_factory_visit_event (
  sample_factory_visit_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_factory_visit_id bigint NOT NULL
    REFERENCES dflow.sample_factory_visit(sample_factory_visit_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  revision integer NOT NULL CHECK (revision > 0),
  event_type text NOT NULL CHECK (event_type IN (
    'planned','reordered','shipped','factory_received','return_started',
    'returned','cancelled','marked_not_returned','factory_changed'
  )),
  from_state text,
  to_state text,
  from_visit_order integer,
  to_visit_order integer,
  from_factory_id integer,
  to_factory_id integer
    REFERENCES dflow."Factory"(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  sample_shipment_id bigint
    REFERENCES dflow.sample_shipment(sample_shipment_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  reason text NOT NULL CHECK (btrim(reason) <> ''),
  changed_by_user text NOT NULL CHECK (btrim(changed_by_user) <> ''),
  changed_by_role text NOT NULL CHECK (btrim(changed_by_role) <> ''),
  changed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (sample_factory_visit_id, revision)
);

CREATE INDEX sample_factory_visit_event_visit_idx
  ON dflow.sample_factory_visit_event (sample_factory_visit_id, revision DESC);

-- Monotonic revision, legal state graph, and the rules for the non-state
-- events. A CHECK cannot see the old row, so the graph lives here.
CREATE OR REPLACE FUNCTION dflow.validate_sample_factory_visit_event()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_state text;
  v_order integer;
  v_factory integer;
  v_expected_revision integer;
BEGIN
  SELECT state, visit_order, factory_id INTO v_state, v_order, v_factory
  FROM dflow.sample_factory_visit
  WHERE sample_factory_visit_id = NEW.sample_factory_visit_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Sample factory visit % does not exist', NEW.sample_factory_visit_id
      USING ERRCODE = '23503';
  END IF;

  SELECT COALESCE(max(revision),0) + 1 INTO v_expected_revision
  FROM dflow.sample_factory_visit_event
  WHERE sample_factory_visit_id = NEW.sample_factory_visit_id;

  IF NEW.revision <> v_expected_revision THEN
    RAISE EXCEPTION 'Visit event revision must be %, received %',
      v_expected_revision, NEW.revision USING ERRCODE = '23514';
  END IF;

  IF v_expected_revision = 1 AND NEW.event_type <> 'planned' THEN
    RAISE EXCEPTION 'The first event of a factory visit must be planned, received %',
      NEW.event_type USING ERRCODE = '23514';
  END IF;

  IF NEW.from_state IS DISTINCT FROM v_state THEN
    RAISE EXCEPTION 'Visit event from_state % does not match the current state %',
      COALESCE(NEW.from_state,'<null>'), v_state USING ERRCODE = '23514';
  END IF;

  -- Each event type declares the state it moves to.
  IF NEW.to_state IS DISTINCT FROM (CASE NEW.event_type
      WHEN 'planned' THEN 'planned'
      WHEN 'shipped' THEN 'shipped'
      WHEN 'factory_received' THEN 'at_factory'
      WHEN 'return_started' THEN 'returning'
      WHEN 'returned' THEN 'returned'
      WHEN 'cancelled' THEN 'cancelled'
      WHEN 'marked_not_returned' THEN 'not_returned'
      ELSE NULL END) THEN
    RAISE EXCEPTION 'Visit event % may not declare to_state %',
      NEW.event_type, COALESCE(NEW.to_state,'<null>') USING ERRCODE = '23514';
  END IF;

  IF NEW.event_type = 'planned' THEN
    IF NEW.revision <> 1 THEN
      RAISE EXCEPTION 'Only the first event may be planned' USING ERRCODE = '23514';
    END IF;

  ELSIF NEW.event_type IN ('reordered','factory_changed') THEN
    -- Intent may only be edited while the visit has not yet shipped.
    IF v_state <> 'planned' THEN
      RAISE EXCEPTION 'A % visit cannot be %', v_state,
        CASE NEW.event_type WHEN 'reordered' THEN 'reordered' ELSE 'redirected' END
        USING ERRCODE = '23514';
    END IF;
    IF NEW.event_type = 'reordered' THEN
      IF NEW.to_visit_order IS NULL OR NEW.to_visit_order <= 0 THEN
        RAISE EXCEPTION 'A reordered event must carry a positive to_visit_order'
          USING ERRCODE = '23514';
      END IF;
      IF NEW.from_visit_order IS DISTINCT FROM v_order THEN
        RAISE EXCEPTION 'Visit event from_visit_order % does not match the current order %',
          COALESCE(NEW.from_visit_order,-1), v_order USING ERRCODE = '23514';
      END IF;
    ELSE
      IF NEW.to_factory_id IS NULL THEN
        RAISE EXCEPTION 'A factory_changed event must carry a to_factory_id'
          USING ERRCODE = '23514';
      END IF;
      IF NEW.from_factory_id IS DISTINCT FROM v_factory THEN
        RAISE EXCEPTION 'Visit event from_factory_id % does not match the current factory %',
          COALESCE(NEW.from_factory_id,-1), v_factory USING ERRCODE = '23514';
      END IF;
    END IF;

  ELSE
    -- The legal state graph. shipped -> returned and at_factory -> returned
    -- are DIRECT edges on purpose: factory check-in is optional in Flow 1 and
    -- a Ningbo receipt must always be able to close the visit in one command.
    IF NOT (
      (v_state = 'planned'    AND NEW.to_state IN ('shipped','cancelled')) OR
      (v_state = 'shipped'    AND NEW.to_state IN ('at_factory','returning','returned','not_returned')) OR
      (v_state = 'at_factory' AND NEW.to_state IN ('returning','returned','not_returned')) OR
      (v_state = 'returning'  AND NEW.to_state IN ('returned','not_returned'))
    ) THEN
      RAISE EXCEPTION 'Factory visit cannot move from % to %', v_state, NEW.to_state
        USING ERRCODE = '23514';
    END IF;

    IF NEW.event_type IN ('shipped','returned') AND NEW.sample_shipment_id IS NULL THEN
      RAISE EXCEPTION 'A % event must carry its sample_shipment_id', NEW.event_type
        USING ERRCODE = '23514';
    END IF;

    -- A piece a factory never returned is gone. It may not be shipped again.
    IF NEW.event_type = 'shipped' AND EXISTS (
      SELECT 1 FROM dflow.sample_factory_visit prior
      WHERE prior.sample_id_fk = (SELECT sample_id_fk FROM dflow.sample_factory_visit
                                  WHERE sample_factory_visit_id = NEW.sample_factory_visit_id)
        AND prior.state = 'not_returned'
    ) THEN
      RAISE EXCEPTION 'This piece was never returned by a factory and cannot be shipped again'
        USING ERRCODE = '23514';
    END IF;
  END IF;

  RETURN NEW;
END $$;

CREATE TRIGGER sample_factory_visit_event_validate
BEFORE INSERT ON dflow.sample_factory_visit_event
FOR EACH ROW EXECUTE FUNCTION dflow.validate_sample_factory_visit_event();

-- The event drives the visit. Nothing else may move it.
CREATE OR REPLACE FUNCTION dflow.apply_sample_factory_visit_event()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.event_type = 'reordered' THEN
    UPDATE dflow.sample_factory_visit
    SET visit_order = NEW.to_visit_order
    WHERE sample_factory_visit_id = NEW.sample_factory_visit_id;
    RETURN NEW;
  END IF;

  IF NEW.event_type = 'factory_changed' THEN
    UPDATE dflow.sample_factory_visit
    SET factory_id = NEW.to_factory_id
    WHERE sample_factory_visit_id = NEW.sample_factory_visit_id;
    RETURN NEW;
  END IF;

  IF NEW.event_type = 'planned' THEN
    -- The row is already 'planned'; revision 1 only records who asked for it.
    RETURN NEW;
  END IF;

  UPDATE dflow.sample_factory_visit v
  SET state = NEW.to_state,
      outbound_shipment_id = CASE WHEN NEW.event_type = 'shipped'
        THEN NEW.sample_shipment_id ELSE v.outbound_shipment_id END,
      return_shipment_id = CASE WHEN NEW.event_type = 'returned'
        THEN NEW.sample_shipment_id ELSE v.return_shipment_id END,
      shipped_at = CASE WHEN NEW.event_type = 'shipped'
        THEN NEW.changed_at ELSE v.shipped_at END,
      factory_received_at = CASE WHEN NEW.event_type = 'factory_received'
        THEN NEW.changed_at ELSE v.factory_received_at END,
      returned_at = CASE WHEN NEW.event_type = 'returned'
        THEN NEW.changed_at ELSE v.returned_at END,
      closed_at = CASE WHEN NEW.to_state IN ('returned','cancelled','not_returned')
        THEN NEW.changed_at ELSE v.closed_at END
  WHERE v.sample_factory_visit_id = NEW.sample_factory_visit_id;

  RETURN NEW;
END $$;

CREATE TRIGGER sample_factory_visit_event_apply
AFTER INSERT ON dflow.sample_factory_visit_event
FOR EACH ROW EXECUTE FUNCTION dflow.apply_sample_factory_visit_event();

-- A direct state write is rejected: the newest event must already name the
-- state being written. Mirrors Release A's require_sample_path_revision.
CREATE OR REPLACE FUNCTION dflow.require_sample_factory_visit_event()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.state IS DISTINCT FROM OLD.state AND NOT EXISTS (
    SELECT 1 FROM dflow.sample_factory_visit_event e
    WHERE e.sample_factory_visit_id = NEW.sample_factory_visit_id
      AND e.to_state = NEW.state
      AND e.from_state IS NOT DISTINCT FROM OLD.state
      AND e.revision = (SELECT max(e2.revision) FROM dflow.sample_factory_visit_event e2
                        WHERE e2.sample_factory_visit_id = NEW.sample_factory_visit_id)
  ) THEN
    RAISE EXCEPTION 'Insert the append-only visit event before changing the visit state'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER sample_factory_visit_event_required
BEFORE UPDATE OF state ON dflow.sample_factory_visit
FOR EACH ROW EXECUTE FUNCTION dflow.require_sample_factory_visit_event();

CREATE OR REPLACE FUNCTION dflow.reject_sample_factory_visit_event_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Sample factory visit events are append-only' USING ERRCODE = '55000';
END $$;

CREATE TRIGGER sample_factory_visit_event_immutable
BEFORE UPDATE OR DELETE ON dflow.sample_factory_visit_event
FOR EACH ROW EXECUTE FUNCTION dflow.reject_sample_factory_visit_event_mutation();

-- ---------------------------------------------------------------------------
-- 4. dflow.sample_visit_plan - read view
-- ---------------------------------------------------------------------------
-- Deliberately NOT the dflow.sample_inventory shape (#1181): no CASE-wrapped
-- predicates and no OR self-join. Every join is plain equality on an indexed
-- column, so a filter on sample_id_fk or on (factory_id, state) reaches an
-- index. Grain is one row per visit, which is what makes the (factory_id,
-- state) factory queue index-usable at all; the sample-level rollups ride on
-- every row.
CREATE OR REPLACE VIEW dflow.sample_visit_plan AS
SELECT
  v.sample_factory_visit_id,
  v.sample_id_fk,
  COALESCE(l.root_sample_id_fk, v.sample_id_fk) AS root_sample_id_fk,
  l.parent_sample_id_fk,
  v.factory_id,
  f.factory_name,
  f.factory_nickname,
  v.visit_order,
  v.provenance,
  v.state,
  v.shipped_at,
  v.factory_received_at,
  v.returned_at,
  v.closed_at,
  v.outbound_shipment_id,
  ob.tracking_number AS outbound_tracking_number,
  ob.carrier_id AS outbound_carrier_id,
  v.return_shipment_id,
  rt.tracking_number AS return_tracking_number,
  rt.carrier_id AS return_carrier_id,
  v.requested_by_user,
  v.requested_by_role,
  v.created_at,
  v.updated_at,
  piece.piece_count,
  roll.active_visit_id,
  roll.completed_visit_count,
  roll.remaining_visit_count,
  custody.to_location_type AS current_custody_type,
  custody.to_location_id AS current_custody_id,
  custody.occurred_at AS current_custody_since
FROM dflow.sample_factory_visit v
LEFT JOIN dflow.sample_piece_lineage l ON l.sample_id_fk = v.sample_id_fk
LEFT JOIN dflow."Factory" f ON f.id = v.factory_id
LEFT JOIN dflow.sample_shipment ob ON ob.sample_shipment_id = v.outbound_shipment_id
LEFT JOIN dflow.sample_shipment rt ON rt.sample_shipment_id = v.return_shipment_id
LEFT JOIN LATERAL (
  SELECT
    max(s.sample_factory_visit_id) FILTER (
      WHERE s.state IN ('shipped','at_factory','returning')) AS active_visit_id,
    count(*) FILTER (WHERE s.state = 'returned') AS completed_visit_count,
    count(*) FILTER (WHERE s.state = 'planned') AS remaining_visit_count
  FROM dflow.sample_factory_visit s
  WHERE s.sample_id_fk = v.sample_id_fk
) roll ON true
LEFT JOIN LATERAL (
  SELECT count(*) + 1 AS piece_count
  FROM dflow.sample_piece_lineage p
  WHERE p.root_sample_id_fk = COALESCE(l.root_sample_id_fk, v.sample_id_fk)
) piece ON true
LEFT JOIN LATERAL (
  SELECT m.to_location_type, m.to_location_id, m.occurred_at
  FROM dflow.sample_movement m
  WHERE m.sample_id_fk = v.sample_id_fk
  ORDER BY m.occurred_at DESC, m.movement_id DESC
  LIMIT 1
) custody ON true;

COMMENT ON TABLE dflow.sample_piece_lineage IS
  'Shared-parent relationship for physical pieces split off one sample. One row per child; the original sample has no row and is its own root. Splitting moves no quantity - conservation stays in dflow.sample_movement.';
COMMENT ON TABLE dflow.sample_factory_visit IS
  'Release B Flow 1 factory visit plan. Intent, not custody: nothing here may contradict dflow.sample_movement.';
COMMENT ON TABLE dflow.sample_factory_visit_event IS
  'Append-only audit that drives dflow.sample_factory_visit state; never rewrite prior revisions.';
COMMENT ON VIEW dflow.sample_visit_plan IS
  'Flow 1 read model: one row per factory visit carrying sample-level rollups, lineage root, custody and both tracking numbers. Index-usable on sample_id_fk and on (factory_id, state).';

REVOKE ALL ON dflow.sample_piece_lineage,dflow.sample_factory_visit,
  dflow.sample_factory_visit_event,dflow.sample_visit_plan FROM anon,authenticated;
REVOKE ALL ON FUNCTION dflow.validate_sample_piece_lineage(),
  dflow.validate_sample_factory_visit(),
  dflow.touch_sample_factory_visit_updated_at(),
  dflow.validate_sample_factory_visit_event(),
  dflow.apply_sample_factory_visit_event(),
  dflow.require_sample_factory_visit_event(),
  dflow.reject_sample_factory_visit_event_mutation()
  FROM PUBLIC,anon,authenticated;

COMMIT;
