-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260225234858
-- Name: 55ccda32_2613_48a3_844e_a7d66540525a
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
