-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `DesignTeamTimes` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Legacy parallel design team time table
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm."DesignTeamTimes" (
    id integer NOT NULL,
    nickname_id_fk integer NOT NULL,
    brief_time integer NOT NULL,
    design_time integer NOT NULL,
    tech_packing_time integer NOT NULL,
    revisions_time integer NOT NULL,
    files_factory_time integer NOT NULL
);

ALTER TABLE plm."DesignTeamTimes" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm."DesignTeamTimes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm."DesignTeamTimes"
    ADD CONSTRAINT "DesignTeamTimes_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE plm."DesignTeamTimes" IS 'Legacy parallel design team time table';
