-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `ProdOrderHeader` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Production order header
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm."ProdOrderHeader" (
    id integer NOT NULL,
    "prodOrderNo" character varying NOT NULL,
    "companyCode" character varying,
    "prodTypeCode" character varying,
    "seasonCode" character varying,
    "shipDate" character varying,
    "dueDate" character varying,
    "shipCancelDate" character varying,
    "origShipDate" character varying,
    "origDueDate" character varying,
    "origShipCancelDate" character varying,
    "prodOrderDate" character varying,
    "prodCountry" character varying,
    "freightForwarderCode" character varying,
    "currencyCode" character varying,
    "warehouseCode" character varying,
    "uDF01" character varying,
    "uDFDate01" character varying,
    "uDFDate02" character varying,
    lcno character varying,
    "vendorCode" character varying,
    "prodRevNo" character varying,
    "prodRevDate" character varying,
    "hangTagsOrdered" character varying,
    "hangTagOrderedDate" character varying,
    "hangTagReceived" character varying,
    "hangTagReceivedDate" character varying,
    "arrivalPortCode" character varying,
    "shipPortCode" character varying,
    "carrierCode" character varying,
    "payTermCode" character varying,
    "prodCostType" character varying,
    "salesOrderNo" character varying,
    "vendorProc" character varying,
    "vendorProcDate" character varying,
    "agentProc" character varying,
    "agentProcDate" character varying,
    "forwarderProc" character varying,
    "forwarderProcDate" character varying,
    "cutterCode" character varying,
    "sewerCode" character varying,
    "prodPrinterCode" character varying,
    "vendorConfirm" character varying,
    "vendorConfirmDate" character varying,
    "customerPONo" character varying,
    "exchangeRatePkey" character varying,
    printed character varying,
    "depositAmount" character varying,
    "depositPaid" character varying,
    "depositBalance" character varying,
    "depositDate" character varying,
    "prodReferenceNo" character varying,
    "discountPerc" character varying,
    "shipViaCode" character varying,
    "depositPosted" character varying,
    "aPTransactionNo" character varying,
    "postedDate" character varying,
    "massProductionDays" character varying,
    "ftySalesRep" character varying,
    "customerCode" character varying,
    comment character varying,
    "prodQty" double precision,
    dlvy_loc_fk integer,
    prod_cost character varying,
    mg5 character varying,
    cust_order_date character varying,
    sent_po_date character varying,
    vendor_start_date character varying,
    item_not_prepro_approved character varying,
    prepro_approval_date character varying,
    calculate_fob_delivery character varying,
    cal_arrival_date character varying,
    adjusted_cust_start_date character varying,
    cust_start character varying,
    cust_cxl character varying,
    price_ticket_needed boolean,
    ticket_order_date character varying,
    tickets_receive_date character varying,
    safety_test_needed boolean,
    safety_test_date character varying,
    safety_test_passed boolean,
    photo_needed boolean,
    photo_recived boolean,
    inspection_result character varying,
    inspection_comment character varying,
    svn character varying,
    cbm character varying,
    vendor_comment character varying,
    "containerNo" character varying,
    actual_etd character varying,
    "actual_Whse_eta" character varying,
    num_docs character varying,
    doc_qc boolean,
    doc_inv boolean,
    doc_pl boolean,
    doc_bl boolean,
    doc_fcr boolean,
    doc_ctpat boolean,
    doc_tsca boolean,
    doc_athome boolean,
    ok_to_pay_date character varying,
    conditions_not_met character varying,
    paid_date character varying,
    container_recvd character varying,
    sample_aprov_lead_days character varying,
    modtime timestamp without time zone,
    "createdTime" timestamp with time zone,
    "createdUser" character varying,
    "modUser" character varying,
    udfnum01 character varying,
    mass_prod_start_date date,
    packing_start_date date,
    inspection_start_date date,
    factory_committed_prod_start character varying(255),
    actual_prod_start character varying(255),
    actual_prod_complete character varying(255),
    material_arrival_date character varying(255),
    assembly_start_date character varying(255),
    qc_inspection_date character varying(255),
    sample_start_date character varying(255),
    buyer_approval_date date,
    ticket_tracking_number character varying(255),
    booking_number character varying(255),
    freight_forwarder_name character varying(255)
);

DO $$ BEGIN
  ALTER TABLE ONLY plm."ProdOrderHeader"
    ADD CONSTRAINT "ProdOrderHeader_pkey" PRIMARY KEY ("prodOrderNo");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE plm."ProdOrderHeader" IS 'Production order header';
