-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260410132722
-- Name: 828960f3_5251_48e1_9a98_69289b3f7bbb
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
