-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `GridViewState` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Saved AG Grid state
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm."GridViewState" (
    id integer NOT NULL,
    user_id_fk integer,
    grid_id character varying(100) NOT NULL,
    view_name character varying(255) NOT NULL,
    column_state jsonb,
    filter_model jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_default boolean DEFAULT false NOT NULL
);

ALTER TABLE plm."GridViewState" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm."GridViewState_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm."GridViewState"
    ADD CONSTRAINT "GridViewState_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "GridViewState_user_grid_view" ON plm."GridViewState" USING btree (user_id_fk, grid_id, view_name);

COMMENT ON TABLE plm."GridViewState" IS 'Saved AG Grid state';
