-- Issue #1520: durable Flow 3 photo and optional QC approval history.
-- Approval facts never mutate physical custody; dflow.sample_movement remains
-- the sole inventory ledger.
BEGIN;

CREATE TABLE dflow.sample_approval_event (
  sample_approval_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_id_fk integer NOT NULL
    REFERENCES dflow.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
  sample_attachment_id integer
    REFERENCES dflow.sample_attachment(sample_attachment_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  approval_type text NOT NULL CHECK (approval_type IN ('photo','qc')),
  approval_state text NOT NULL CHECK (approval_state IN ('pending','approved','rejected')),
  qc_required boolean NOT NULL,
  destination_type text,
  destination_id text,
  reason text,
  actor_user text NOT NULL CHECK (btrim(actor_user) <> ''),
  actor_role text NOT NULL CHECK (btrim(actor_role) <> ''),
  idempotency_key text NOT NULL CHECK (btrim(idempotency_key) <> ''),
  request_hash text NOT NULL CHECK (btrim(request_hash) <> ''),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sample_approval_destination_pair_check CHECK (
    (destination_type IS NULL AND destination_id IS NULL) OR
    (destination_type IS NOT NULL AND btrim(destination_type) <> ''
      AND destination_id IS NOT NULL AND btrim(destination_id) <> '')
  ),
  CONSTRAINT sample_approval_rejection_reason_check CHECK (
    approval_state <> 'rejected' OR (reason IS NOT NULL AND btrim(reason) <> '')
  ),
  CONSTRAINT sample_approval_attachment_type_check CHECK (
    approval_type = 'photo' OR sample_attachment_id IS NULL
  ),
  UNIQUE (sample_id_fk, idempotency_key)
);

CREATE INDEX sample_approval_event_latest_idx
  ON dflow.sample_approval_event
  (sample_id_fk, approval_type, created_at DESC, sample_approval_event_id DESC);

CREATE OR REPLACE FUNCTION dflow.validate_sample_approval_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  v_current dflow.sample_approval_event;
  v_photo dflow.sample_approval_event;
BEGIN
  PERFORM pg_advisory_xact_lock(1520, NEW.sample_id_fk);

  IF NEW.sample_attachment_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM dflow.sample_attachment
    WHERE sample_attachment_id = NEW.sample_attachment_id
      AND sample_id_fk = NEW.sample_id_fk
  ) THEN
    RAISE EXCEPTION 'Attachment % does not belong to sample %',
      NEW.sample_attachment_id, NEW.sample_id_fk USING ERRCODE = '23503';
  END IF;

  SELECT * INTO v_current
  FROM dflow.sample_approval_event
  WHERE sample_id_fk = NEW.sample_id_fk AND approval_type = NEW.approval_type
  ORDER BY created_at DESC, sample_approval_event_id DESC
  LIMIT 1;

  IF NOT FOUND AND NEW.approval_state <> 'pending' THEN
    RAISE EXCEPTION 'The first % approval event must be pending', NEW.approval_type
      USING ERRCODE = '23514';
  ELSIF FOUND AND NOT (
    (v_current.approval_state = 'pending' AND NEW.approval_state IN ('approved','rejected')) OR
    (v_current.approval_state = 'rejected' AND NEW.approval_state = 'pending')
  ) THEN
    RAISE EXCEPTION 'Invalid % approval transition from % to %',
      NEW.approval_type, v_current.approval_state, NEW.approval_state USING ERRCODE = '23514';
  END IF;

  IF FOUND AND NEW.qc_required IS DISTINCT FROM v_current.qc_required THEN
    RAISE EXCEPTION 'QC requirement cannot change within an approval history'
      USING ERRCODE = '23514';
  END IF;

  IF NEW.approval_type = 'qc' THEN
    SELECT * INTO v_photo
    FROM dflow.sample_approval_event
    WHERE sample_id_fk = NEW.sample_id_fk AND approval_type = 'photo'
    ORDER BY created_at DESC, sample_approval_event_id DESC
    LIMIT 1;
    IF NOT FOUND OR v_photo.approval_state <> 'approved' OR NOT v_photo.qc_required THEN
      RAISE EXCEPTION 'QC decisions require a currently approved photo with QC required'
        USING ERRCODE = '23514';
    END IF;
    IF NOT NEW.qc_required THEN
      RAISE EXCEPTION 'QC events must carry qc_required=true' USING ERRCODE = '23514';
    END IF;
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER sample_approval_event_validate
BEFORE INSERT ON dflow.sample_approval_event
FOR EACH ROW EXECUTE FUNCTION dflow.validate_sample_approval_event();

CREATE OR REPLACE FUNCTION dflow.reject_sample_approval_event_mutation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
BEGIN
  RAISE EXCEPTION 'Sample approval events are append-only' USING ERRCODE = '55000';
END $$;

CREATE TRIGGER sample_approval_event_immutable
BEFORE UPDATE OR DELETE ON dflow.sample_approval_event
FOR EACH ROW EXECUTE FUNCTION dflow.reject_sample_approval_event_mutation();

CREATE OR REPLACE VIEW dflow.sample_approval_current
WITH (security_invoker = true) AS
SELECT DISTINCT ON (sample_id_fk, approval_type)
  sample_approval_event_id,
  sample_id_fk,
  sample_attachment_id,
  approval_type,
  approval_state,
  qc_required,
  destination_type,
  destination_id,
  reason,
  actor_user,
  actor_role,
  idempotency_key,
  request_hash,
  created_at
FROM dflow.sample_approval_event
ORDER BY sample_id_fk, approval_type, created_at DESC, sample_approval_event_id DESC;

CREATE OR REPLACE FUNCTION dflow.post_sample_approval_event(
  p_sample_id integer,
  p_approval_type text,
  p_approval_state text,
  p_qc_required boolean,
  p_actor_user text,
  p_actor_role text,
  p_idempotency_key text,
  p_request_hash text,
  p_sample_attachment_id integer DEFAULT NULL,
  p_destination_type text DEFAULT NULL,
  p_destination_id text DEFAULT NULL,
  p_reason text DEFAULT NULL
) RETURNS dflow.sample_approval_event
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
  v_existing dflow.sample_approval_event;
  v_result dflow.sample_approval_event;
BEGIN
  IF p_sample_id IS NULL OR p_approval_type IS NULL OR p_approval_state IS NULL
     OR p_qc_required IS NULL OR p_actor_user IS NULL OR btrim(p_actor_user) = ''
     OR p_actor_role IS NULL OR btrim(p_actor_role) = ''
     OR p_idempotency_key IS NULL OR btrim(p_idempotency_key) = ''
     OR p_request_hash IS NULL OR btrim(p_request_hash) = '' THEN
    RAISE EXCEPTION 'Required approval event arguments cannot be null or blank'
      USING ERRCODE = '22023';
  END IF;
  IF p_approval_type NOT IN ('photo','qc')
     OR p_approval_state NOT IN ('pending','approved','rejected') THEN
    RAISE EXCEPTION 'Unsupported approval type or state' USING ERRCODE = '22023';
  END IF;

  PERFORM pg_advisory_xact_lock(1520, p_sample_id);
  PERFORM 1 FROM dflow.sample WHERE sample_id_pk = p_sample_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Sample % does not exist', p_sample_id USING ERRCODE = '23503';
  END IF;

  SELECT * INTO v_existing
  FROM dflow.sample_approval_event
  WHERE sample_id_fk = p_sample_id AND idempotency_key = p_idempotency_key;
  IF FOUND THEN
    IF v_existing.request_hash IS DISTINCT FROM p_request_hash THEN
      RAISE EXCEPTION 'Idempotency key reused with different request'
        USING ERRCODE = '23505';
    END IF;
    RETURN v_existing;
  END IF;

  INSERT INTO dflow.sample_approval_event (
    sample_id_fk, sample_attachment_id, approval_type, approval_state, qc_required,
    destination_type, destination_id, reason, actor_user, actor_role,
    idempotency_key, request_hash
  ) VALUES (
    p_sample_id, p_sample_attachment_id, p_approval_type, p_approval_state, p_qc_required,
    p_destination_type, p_destination_id, p_reason, p_actor_user, p_actor_role,
    p_idempotency_key, p_request_hash
  ) RETURNING * INTO v_result;
  RETURN v_result;
END $$;

REVOKE ALL ON dflow.sample_approval_event, dflow.sample_approval_current
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION dflow.post_sample_approval_event(
  integer,text,text,boolean,text,text,text,text,integer,text,text,text
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION dflow.validate_sample_approval_event(),
  dflow.reject_sample_approval_event_mutation()
  FROM PUBLIC, anon, authenticated;

COMMENT ON TABLE dflow.sample_approval_event IS
  'Append-only Flow 3 photo and optional QC decision history. It never represents inventory movement.';
COMMENT ON VIEW dflow.sample_approval_current IS
  'Deterministic latest approval event for each sample and approval type.';
COMMENT ON FUNCTION dflow.post_sample_approval_event(
  integer,text,text,boolean,text,text,text,text,integer,text,text,text
) IS 'Serializes idempotent Flow 3 approval transitions without posting sample movements.';

COMMIT;
