-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260406180259
-- Name: 7b076a04_4e2c_461a_a7e9_ecc28b1b984b
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
