-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260310195534
-- Name: 3eedbd6f_0d26_401e_9b6b_a62f3177d69d
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
