-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260303203719
-- Name: 6f4820d5_d078_44c6_bcc8_614974feeeb7
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
