-- Fix forward from the exact Release A migration already applied to preview.
-- Preserve legacy headerless shipment-line behavior while enforcing complete
-- identity and route consistency for Release A header-backed shipments.
BEGIN;

-- Preview recorded the Release A version before the final shipment-header
-- objects were added to that migration. Reconcile those objects here rather
-- than changing migration history or its ledger entry.
CREATE TABLE IF NOT EXISTS dflow.sample_carrier (
  sample_carrier_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carrier_code text NOT NULL UNIQUE CHECK (carrier_code = lower(carrier_code) AND btrim(carrier_code) <> ''),
  display_name text NOT NULL UNIQUE CHECK (btrim(display_name) <> ''),
  tracking_url_template text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO dflow.sample_carrier (carrier_code,display_name,tracking_url_template)
VALUES
  ('ups','UPS','https://www.ups.com/track?tracknum={tracking_number}'),
  ('fedex','FedEx','https://www.fedex.com/fedextrack/?trknbr={tracking_number}'),
  ('dhl','DHL','https://www.dhl.com/global-en/home/tracking.html?tracking-id={tracking_number}'),
  ('usps','USPS','https://tools.usps.com/go/TrackConfirmAction?tLabels={tracking_number}')
ON CONFLICT (carrier_code) DO NOTHING;

CREATE TABLE IF NOT EXISTS dflow.sample_shipment (
  sample_shipment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carrier_id smallint REFERENCES dflow.sample_carrier(sample_carrier_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  tracking_number text CHECK (tracking_number IS NULL OR btrim(tracking_number) <> ''),
  origin_location_type text NOT NULL CHECK (origin_location_type IN ('factory','office','customer','warehouse')),
  origin_location_id text NOT NULL CHECK (btrim(origin_location_id) <> ''),
  destination_location_type text NOT NULL CHECK (destination_location_type IN ('factory','office','customer','warehouse')),
  destination_location_id text NOT NULL CHECK (btrim(destination_location_id) <> ''),
  state text NOT NULL DEFAULT 'draft' CHECK (state IN (
    'draft','packed','shipped','received','delivered_reported','delivery_exception','cancelled'
  )),
  shipped_at timestamptz,
  received_at timestamptz,
  actor_user text NOT NULL CHECK (btrim(actor_user) <> ''),
  actor_role text NOT NULL CHECK (btrim(actor_role) <> ''),
  idempotency_key text NOT NULL UNIQUE CHECK (btrim(idempotency_key) <> ''),
  request_hash text NOT NULL CHECK (btrim(request_hash) <> ''),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (origin_location_type <> destination_location_type OR origin_location_id <> destination_location_id),
  CHECK ((carrier_id IS NULL) = (tracking_number IS NULL)),
  CHECK (state NOT IN ('shipped','received','delivered_reported','delivery_exception') OR shipped_at IS NOT NULL),
  CHECK (state <> 'received' OR received_at IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS sample_shipment_active_tracking_uniq
  ON dflow.sample_shipment (carrier_id,lower(tracking_number))
  WHERE carrier_id IS NOT NULL AND state <> 'cancelled';

ALTER TABLE dflow.sample_shipment_line
  ADD COLUMN IF NOT EXISTS sample_shipment_id bigint
    REFERENCES dflow.sample_shipment(sample_shipment_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE dflow.sample_shipment_line ALTER COLUMN box_id_fk DROP NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
    WHERE conrelid='dflow.sample_shipment_line'::regclass
      AND conname='sample_shipment_line_box_or_header_check') THEN
    ALTER TABLE dflow.sample_shipment_line
      ADD CONSTRAINT sample_shipment_line_box_or_header_check
      CHECK (box_id_fk IS NOT NULL OR sample_shipment_id IS NOT NULL);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS sample_shipment_line_header_idx
  ON dflow.sample_shipment_line(sample_shipment_id,shipment_line_id)
  WHERE sample_shipment_id IS NOT NULL;

ALTER TABLE dflow.sample_box
  ADD COLUMN IF NOT EXISTS current_custody_type text,
  ADD COLUMN IF NOT EXISTS current_custody_id text;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
    WHERE conrelid='dflow.sample_box'::regclass AND conname='sample_box_custody_pair_check') THEN
    ALTER TABLE dflow.sample_box ADD CONSTRAINT sample_box_custody_pair_check CHECK (
      (current_custody_type IS NULL AND current_custody_id IS NULL) OR
      (current_custody_type IN ('factory','office','customer','warehouse','in_transit')
        AND current_custody_id IS NOT NULL AND btrim(current_custody_id) <> '')
    );
  END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS sample_box_active_name_custody_uniq
  ON dflow.sample_box(lower(btrim(box_label)),current_custody_type,current_custody_id)
  WHERE current_custody_type IS NOT NULL AND status NOT IN ('closed','cancelled');

DO $$
DECLARE v_bad bigint;
BEGIN
  SELECT count(*) INTO v_bad FROM dflow.sample_shipment_line
  WHERE route_leg NOT IN (
    'factory_to_ningbo','factory_to_nyc','factory_to_customer',
    'ningbo_to_nyc','ningbo_to_customer','nyc_to_ningbo','nyc_to_factory','nyc_to_customer',
    'ningbo_to_factory','factory_return_to_ningbo','warehouse_to_ningbo'
  );
  IF v_bad > 0 THEN
    RAISE EXCEPTION 'Release A reconciliation refused % unsupported shipment route(s)',v_bad;
  END IF;
  SELECT count(*) INTO v_bad FROM dflow.sample_movement
  WHERE from_location_type NOT IN ('factory','office','customer','warehouse','in_transit','terminal')
     OR to_location_type NOT IN ('factory','office','customer','warehouse','in_transit','terminal');
  IF v_bad > 0 THEN
    RAISE EXCEPTION 'Release A reconciliation refused % unsupported movement route(s)',v_bad;
  END IF;
END $$;

ALTER TABLE dflow.sample_shipment_line DROP CONSTRAINT IF EXISTS sample_shipment_line_route_leg_check;
ALTER TABLE dflow.sample_shipment_line ADD CONSTRAINT sample_shipment_line_route_leg_check CHECK (route_leg IN (
  'factory_to_ningbo','factory_to_nyc','factory_to_customer',
  'ningbo_to_nyc','ningbo_to_customer','nyc_to_ningbo','nyc_to_factory','nyc_to_customer',
  'ningbo_to_factory','factory_return_to_ningbo','warehouse_to_ningbo'
));
ALTER TABLE dflow.sample_shipment_line DROP CONSTRAINT IF EXISTS sample_shipment_line_origin_location_type_check;
ALTER TABLE dflow.sample_shipment_line ADD CONSTRAINT sample_shipment_line_origin_location_type_check CHECK (
  origin_location_type IN ('factory','office','customer','warehouse') OR
  (origin_location_type='terminal' AND origin_location_id LIKE '%\_office\_inventory')
);
ALTER TABLE dflow.sample_shipment_line DROP CONSTRAINT IF EXISTS sample_shipment_line_destination_location_type_check;
ALTER TABLE dflow.sample_shipment_line ADD CONSTRAINT sample_shipment_line_destination_location_type_check
  CHECK (destination_location_type IN ('factory','office','customer','warehouse'));
ALTER TABLE dflow.sample_movement DROP CONSTRAINT IF EXISTS sample_movement_from_location_type_check;
ALTER TABLE dflow.sample_movement ADD CONSTRAINT sample_movement_from_location_type_check
  CHECK (from_location_type IN ('factory','office','customer','warehouse','in_transit','terminal'));
ALTER TABLE dflow.sample_movement DROP CONSTRAINT IF EXISTS sample_movement_to_location_type_check;
ALTER TABLE dflow.sample_movement ADD CONSTRAINT sample_movement_to_location_type_check
  CHECK (to_location_type IN ('factory','office','customer','warehouse','in_transit','terminal'));

ALTER TABLE dflow.sample_movement
  ADD COLUMN IF NOT EXISTS sample_shipment_id bigint
    REFERENCES dflow.sample_shipment(sample_shipment_id) ON UPDATE CASCADE ON DELETE RESTRICT;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='dflow.sample_movement'::regclass
             AND conname='sample_movement_transit_box_identity_check') THEN
    ALTER TABLE dflow.sample_movement DROP CONSTRAINT sample_movement_transit_box_identity_check;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='dflow.sample_movement'::regclass
                 AND conname='sample_movement_transit_identity_check') THEN
    ALTER TABLE dflow.sample_movement ADD CONSTRAINT sample_movement_transit_identity_check CHECK (
      (from_location_type <> 'in_transit' AND to_location_type <> 'in_transit') OR
      (shipment_line_id IS NOT NULL AND (box_id_fk IS NOT NULL OR sample_shipment_id IS NOT NULL))
    );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='dflow.sample_movement'::regclass
                 AND conname='sample_movement_transit_location_identity_check') THEN
    ALTER TABLE dflow.sample_movement ADD CONSTRAINT sample_movement_transit_location_identity_check CHECK (
      (from_location_type <> 'in_transit' OR from_location_id=COALESCE(box_id_fk::text,sample_shipment_id::text)) AND
      (to_location_type <> 'in_transit' OR to_location_id=COALESCE(box_id_fk::text,sample_shipment_id::text))
    );
  END IF;
END $$;

COMMENT ON TABLE dflow.sample_carrier IS 'Canonical manual carrier choices. Carrier automation is deferred.';
COMMENT ON TABLE dflow.sample_shipment IS 'Shipment header shared by boxed and unboxed shipment lines; movements remain custody truth.';
REVOKE ALL ON dflow.sample_carrier,dflow.sample_shipment FROM anon,authenticated;

CREATE OR REPLACE FUNCTION dflow.prevent_sample_shipment_route_drift()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_shipment_id bigint;
  v_header record;
BEGIN
  IF TG_TABLE_NAME='sample_shipment' THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('sample_shipment:' || OLD.sample_shipment_id::text,0));
    IF (NEW.origin_location_type,NEW.origin_location_id,
      NEW.destination_location_type,NEW.destination_location_id)
     IS DISTINCT FROM
     (OLD.origin_location_type,OLD.origin_location_id,
      OLD.destination_location_type,OLD.destination_location_id)
     AND EXISTS (
       SELECT 1 FROM dflow.sample_shipment_line
       WHERE sample_shipment_id=OLD.sample_shipment_id
     ) THEN
    RAISE EXCEPTION 'Shipment route cannot change after lines are attached'
      USING ERRCODE='55000';
    END IF;
  ELSE
    PERFORM pg_advisory_xact_lock(
      hashtextextended('sample_shipment_line:' || NEW.shipment_line_id::text,0));
    v_shipment_id := NEW.sample_shipment_id;
    IF v_shipment_id IS NOT NULL THEN
      PERFORM pg_advisory_xact_lock(hashtextextended('sample_shipment:' || v_shipment_id::text,0));
      SELECT * INTO STRICT v_header FROM dflow.sample_shipment
      WHERE sample_shipment_id=v_shipment_id;
      IF (NEW.origin_location_type,NEW.origin_location_id,
          NEW.destination_location_type,NEW.destination_location_id)
         IS DISTINCT FROM
         (v_header.origin_location_type,v_header.origin_location_id,
          v_header.destination_location_type,v_header.destination_location_id) THEN
        RAISE EXCEPTION 'Shipment line route must match shipment header %',v_shipment_id
          USING ERRCODE='23514';
      END IF;
    END IF;
    IF TG_OP='UPDATE'
       AND (NEW.sample_id_fk,NEW.box_id_fk,NEW.sample_shipment_id,
            NEW.origin_location_type,NEW.origin_location_id,
            NEW.destination_location_type,NEW.destination_location_id)
           IS DISTINCT FROM
           (OLD.sample_id_fk,OLD.box_id_fk,OLD.sample_shipment_id,
            OLD.origin_location_type,OLD.origin_location_id,
            OLD.destination_location_type,OLD.destination_location_id)
       AND EXISTS (SELECT 1 FROM dflow.sample_movement
                   WHERE shipment_line_id=OLD.shipment_line_id) THEN
      RAISE EXCEPTION 'Shipment line identity and route cannot change after movement'
        USING ERRCODE='55000';
    END IF;
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS sample_shipment_route_immutable_after_lines ON dflow.sample_shipment;
CREATE TRIGGER sample_shipment_route_immutable_after_lines
BEFORE UPDATE OF origin_location_type,origin_location_id,
  destination_location_type,destination_location_id ON dflow.sample_shipment
FOR EACH ROW EXECUTE FUNCTION dflow.prevent_sample_shipment_route_drift();

DROP TRIGGER IF EXISTS sample_shipment_line_identity_immutable_after_movement
  ON dflow.sample_shipment_line;
CREATE TRIGGER sample_shipment_line_identity_immutable_after_movement
BEFORE INSERT OR UPDATE OF sample_id_fk,box_id_fk,sample_shipment_id,
  origin_location_type,origin_location_id,destination_location_type,destination_location_id
  ON dflow.sample_shipment_line
FOR EACH ROW EXECUTE FUNCTION dflow.prevent_sample_shipment_route_drift();

CREATE OR REPLACE FUNCTION dflow.validate_sample_movement_shipment_identity()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_line dflow.sample_shipment_line;
BEGIN
  IF NEW.shipment_line_id IS NULL THEN RETURN NEW; END IF;
  PERFORM pg_advisory_xact_lock(
    hashtextextended('sample_shipment_line:' || NEW.shipment_line_id::text,0));
  SELECT * INTO v_line FROM dflow.sample_shipment_line
  WHERE shipment_line_id=NEW.shipment_line_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Shipment line % does not exist',NEW.shipment_line_id USING ERRCODE='23503';
  END IF;
  IF NEW.sample_id_fk IS DISTINCT FROM v_line.sample_id_fk
     OR NEW.box_id_fk IS DISTINCT FROM v_line.box_id_fk
     OR NEW.sample_shipment_id IS DISTINCT FROM v_line.sample_shipment_id THEN
    RAISE EXCEPTION 'Movement identity does not match shipment line %',NEW.shipment_line_id
      USING ERRCODE='23514';
  END IF;
  IF v_line.sample_shipment_id IS NOT NULL AND NOT (
    (NEW.from_location_type IS NOT DISTINCT FROM v_line.origin_location_type
      AND NEW.from_location_id IS NOT DISTINCT FROM v_line.origin_location_id
      AND NEW.to_location_type='in_transit')
    OR
    (NEW.from_location_type='in_transit'
      AND NEW.to_location_type IS NOT DISTINCT FROM v_line.destination_location_type
      AND NEW.to_location_id IS NOT DISTINCT FROM v_line.destination_location_id)
  ) THEN
    RAISE EXCEPTION 'Movement route does not match shipment line %',NEW.shipment_line_id
      USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS sample_movement_shipment_identity ON dflow.sample_movement;
CREATE TRIGGER sample_movement_shipment_identity
BEFORE INSERT ON dflow.sample_movement
FOR EACH ROW EXECUTE FUNCTION dflow.validate_sample_movement_shipment_identity();

DO $$
DECLARE v_bad bigint;
BEGIN
  SELECT count(*) INTO v_bad
  FROM dflow.sample_movement m
  JOIN dflow.sample_shipment_line l ON l.shipment_line_id=m.shipment_line_id
  WHERE m.sample_id_fk IS DISTINCT FROM l.sample_id_fk
     OR m.box_id_fk IS DISTINCT FROM l.box_id_fk
     OR m.sample_shipment_id IS DISTINCT FROM l.sample_shipment_id;
  IF v_bad > 0 THEN
    RAISE EXCEPTION 'Release A integrity fix refused % movement identity mismatch(es)',v_bad;
  END IF;
  SELECT count(*) INTO v_bad
  FROM dflow.sample_shipment_line l
  JOIN dflow.sample_shipment s ON s.sample_shipment_id=l.sample_shipment_id
  WHERE (l.origin_location_type,l.origin_location_id,
         l.destination_location_type,l.destination_location_id)
        IS DISTINCT FROM
        (s.origin_location_type,s.origin_location_id,
         s.destination_location_type,s.destination_location_id);
  IF v_bad > 0 THEN
    RAISE EXCEPTION 'Release A integrity fix refused % shipment route mismatch(es)',v_bad;
  END IF;
  SELECT count(*) INTO v_bad
  FROM dflow.sample_movement m
  JOIN dflow.sample_shipment_line l ON l.shipment_line_id=m.shipment_line_id
  WHERE l.sample_shipment_id IS NOT NULL
    AND NOT (
      (m.from_location_type IS NOT DISTINCT FROM l.origin_location_type
        AND m.from_location_id IS NOT DISTINCT FROM l.origin_location_id
        AND m.to_location_type='in_transit')
      OR
      (m.from_location_type='in_transit'
        AND m.to_location_type IS NOT DISTINCT FROM l.destination_location_type
        AND m.to_location_id IS NOT DISTINCT FROM l.destination_location_id)
    );
  IF v_bad > 0 THEN
    RAISE EXCEPTION 'Release A integrity fix refused % movement route mismatch(es)',v_bad;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION dflow.post_sample_movement(
  p_sample_id integer, p_quantity integer,
  p_from_type text, p_from_id text, p_to_type text, p_to_id text,
  p_action text, p_actor_user text, p_actor_role text,
  p_idempotency_key text, p_request_hash text,
  p_box_id integer DEFAULT NULL, p_shipment_line_id bigint DEFAULT NULL,
  p_actor_factory_id integer DEFAULT NULL, p_discrepancy_code text DEFAULT NULL,
  p_discrepancy_details text DEFAULT NULL, p_reversal_of bigint DEFAULT NULL,
  p_from_label text DEFAULT NULL, p_to_label text DEFAULT NULL
) RETURNS dflow.sample_movement LANGUAGE plpgsql SECURITY INVOKER AS $$
DECLARE
  v_existing dflow.sample_movement;
  v_result dflow.sample_movement;
  v_shipment_id bigint;
  v_line_box_id integer;
  v_line_origin_type text;
  v_line_origin_id text;
  v_line_destination_type text;
  v_line_destination_id text;
BEGIN
  PERFORM pg_advisory_xact_lock(21450, p_sample_id);
  SELECT * INTO v_existing FROM dflow.sample_movement
   WHERE sample_id_fk=p_sample_id AND idempotency_key=p_idempotency_key;
  IF FOUND THEN
    IF v_existing.request_hash <> p_request_hash THEN
      RAISE EXCEPTION 'Idempotency key reused with different request' USING ERRCODE='23505';
    END IF;
    RETURN v_existing;
  END IF;
  IF p_shipment_line_id IS NOT NULL THEN
    SELECT sample_shipment_id,box_id_fk,origin_location_type,origin_location_id,
           destination_location_type,destination_location_id
      INTO v_shipment_id,v_line_box_id,v_line_origin_type,v_line_origin_id,
           v_line_destination_type,v_line_destination_id
    FROM dflow.sample_shipment_line
    WHERE shipment_line_id = p_shipment_line_id AND sample_id_fk = p_sample_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Shipment line % does not belong to sample %', p_shipment_line_id, p_sample_id
        USING ERRCODE='23503';
    END IF;
    IF p_box_id IS DISTINCT FROM v_line_box_id THEN
      RAISE EXCEPTION 'Box % does not match shipment line % box %',p_box_id,p_shipment_line_id,v_line_box_id
        USING ERRCODE='23514';
    END IF;
    IF v_shipment_id IS NOT NULL AND p_action IN ('ship','pack') AND (
      p_from_type IS DISTINCT FROM v_line_origin_type OR p_from_id IS DISTINCT FROM v_line_origin_id
      OR p_to_type <> 'in_transit'
    ) THEN
      RAISE EXCEPTION 'Ship movement route does not match shipment line %',p_shipment_line_id
        USING ERRCODE='23514';
    END IF;
    IF v_shipment_id IS NOT NULL AND p_action = 'receive' AND (
      p_from_type <> 'in_transit' OR p_to_type IS DISTINCT FROM v_line_destination_type
      OR p_to_id IS DISTINCT FROM v_line_destination_id
    ) THEN
      RAISE EXCEPTION 'Receive movement route does not match shipment line %',p_shipment_line_id
        USING ERRCODE='23514';
    END IF;
  END IF;
  INSERT INTO dflow.sample_movement(sample_id_fk,quantity,from_location_type,from_location_id,
    from_location_label,to_location_type,to_location_id,to_location_label,box_id_fk,shipment_line_id,
    sample_shipment_id,lifecycle_action,actor_user,actor_role,actor_factory_id,idempotency_key,
    request_hash,discrepancy_code,discrepancy_details,reversal_of_movement_id)
  VALUES(p_sample_id,p_quantity,p_from_type,p_from_id,p_from_label,p_to_type,p_to_id,p_to_label,
    p_box_id,p_shipment_line_id,v_shipment_id,p_action,p_actor_user,p_actor_role,p_actor_factory_id,
    p_idempotency_key,p_request_hash,p_discrepancy_code,p_discrepancy_details,p_reversal_of)
  RETURNING * INTO v_result;
  RETURN v_result;
END $$;

REVOKE ALL ON FUNCTION dflow.prevent_sample_shipment_route_drift(),
  dflow.validate_sample_movement_shipment_identity()
  FROM PUBLIC,anon,authenticated;

COMMIT;
