-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260304132128
-- Name: 811a4265_101f_40e1_9f9b_431ee2cfe56e
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
