-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `itemDetail` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: SKU/size-level item detail
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm."itemDetail" (
    item_pk integer NOT NULL,
    label_code_fk character varying,
    dim_code_fk character varying,
    prepack_code_fk character varying,
    size_code_fk character varying,
    "UPC" character varying,
    "EAN" character varying,
    "GTIN" character varying,
    item_status_hed character varying,
    uom_code_hed_fk character varying,
    retail_pric_hed numeric,
    item_cost_hed_ext numeric,
    udf_merchgroup01 character varying,
    udf_merchgroup02 character varying,
    udf_merchgroup03 character varying,
    udf_merchgroup04 character varying,
    udf_merchgroup05 character varying,
    udf_merchgroup06 character varying,
    udf_merchgroup07 character varying,
    udf_merchgroup08 character varying,
    udf_merchgroup09 character varying,
    udf_merchgroup10 character varying,
    udf_merchgroup11 character varying,
    udf_merchgroup12 character varying,
    udf_merchgroup13 character varying,
    udf_merchgroup14 character varying,
    udf_merchgroup15 character varying,
    udf_merchgroup16 character varying,
    udf_merchgroup17 character varying,
    udf_merchgroup18 character varying,
    udf_merchgroup19 character varying,
    udf_merchgroup20 character varying,
    udf_merchgroup21 character varying,
    udf_merchgroup22 character varying,
    udf_merchgroup23 character varying,
    udf_merchgroup24 character varying,
    udf_merchgroup25 character varying,
    udf_freeform_01 character varying(50),
    udf_freeform_02 character varying(50),
    udf_freeform_03 character varying(50),
    udf_freeform_04 character varying(50),
    udf_freeform_05 character varying(50),
    udf_freeform_06 character varying(50),
    udf_freeform_07 character varying(50),
    udf_freeform_08 character varying(50),
    udf_freeform_09 character varying(50),
    udf_freeform_10 character varying(50),
    udf_freeform_11 character varying(50),
    udf_freeform_12 character varying(50),
    udf_freeform_13 character varying(50),
    udf_freeform_14 character varying(50),
    udf_freeform_15 character varying(50),
    udf_freeform_16 character varying(50),
    udf_freeform_17 character varying(50),
    udf_freeform_18 character varying(50),
    udf_freeform_19 character varying(50),
    udf_freeform_20 character varying(50),
    udf_date01 timestamp without time zone,
    udf_date02 timestamp without time zone,
    udf_date03 timestamp without time zone,
    udf_date04 timestamp without time zone,
    udf_date05 timestamp without time zone,
    udf_date06 timestamp without time zone,
    udf_date07 timestamp without time zone,
    udf_date08 timestamp without time zone,
    udf_date09 timestamp without time zone,
    udf_date10 timestamp without time zone,
    udf_date11 timestamp without time zone,
    udf_date12 timestamp without time zone,
    udf_date13 timestamp without time zone,
    udf_date14 timestamp without time zone,
    udf_date15 timestamp without time zone,
    udf_date16 timestamp without time zone,
    udf_date17 timestamp without time zone,
    udf_date18 timestamp without time zone,
    udf_date19 timestamp without time zone,
    udf_date20 timestamp without time zone,
    hts_num_hed_ext_fk character varying,
    item_length_size_hed numeric,
    item_width_size_hed numeric,
    item_depth_size_hed numeric,
    item_weight_size_hed numeric,
    uom_size_fk_hed character varying,
    uom_weight_fk_hed character varying,
    innerpk_qty_hed integer,
    created_user_fk character varying,
    created_timedate timestamp without time zone,
    mod_timedate timestamp without time zone,
    mod_user_fk character varying,
    royalty_code_fk character varying,
    "udf_item_priceA" numeric,
    "udf_item_priceB" numeric,
    "udf_item_priceC" numeric,
    "udf_item_priceD" numeric,
    "udf_item_priceE" numeric,
    "udf_item_priceF" numeric,
    "udf_item_priceG" numeric,
    "udf_item_priceH" numeric,
    carton_qty integer,
    base_qty_hed integer,
    color_code_fk character varying,
    size_seq integer,
    "GenerateUPC" character varying,
    size_allowed_hed character varying,
    "share_UPC" character varying,
    vendor_code_hed_fk character varying,
    selling_price_hed numeric,
    item_content_hed character varying,
    reserved_qty integer,
    pack_type_hed character varying,
    udf_int01 integer,
    udf_int02 integer,
    udf_int03 integer,
    udf_int04 integer,
    udf_int05 integer,
    udf_int06 integer,
    udf_int07 integer,
    udf_int08 integer,
    udf_int09 integer,
    udf_int10 integer,
    udf_num01 numeric,
    udf_num02 numeric,
    udf_num03 numeric,
    udf_num04 numeric,
    udf_num05 numeric,
    udf_num06 numeric,
    udf_num07 numeric,
    udf_num08 numeric,
    udf_num09 numeric,
    udf_num10 numeric,
    non_inv_item character varying,
    udf_yesno01 character varying,
    udf_yesno02 character varying,
    udf_yesno03 character varying,
    udf_yesno04 character varying,
    udf_yesno05 character varying,
    udf_yesno06 character varying,
    udf_yesno07 character varying,
    udf_yesno08 character varying,
    udf_yesno09 character varying,
    udf_yesno10 character varying,
    udf_yesno11 character varying,
    udf_yesno12 character varying,
    udf_yesno13 character varying,
    udf_yesno14 character varying,
    udf_yesno15 character varying,
    carton_packtype_fk character varying,
    carton_code_ext character varying,
    carton_length_size_hed numeric,
    carton_width_size_hed numeric,
    carton_depth_size_hed numeric,
    carton_weight_size_hed numeric,
    "NMFC_code_hed" character varying,
    compare_price_hed numeric,
    whse_sku_id character varying,
    item_cbm_size numeric,
    season_code_hed character varying,
    size_explo_code_hed_ext character varying,
    ds_cat character varying,
    item_active_status character varying,
    item_avail_status character varying,
    discont_status character varying,
    upc_created_timedate timestamp without time zone,
    salesperson_fk character varying
);

DO $$ BEGIN
  ALTER TABLE ONLY plm."itemDetail"
    ADD CONSTRAINT "itemDetail_pkey" PRIMARY KEY (item_pk);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE plm."itemDetail" IS 'SKU/size-level item detail';
