-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `productUserAssignment` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Item user role assignments
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm."productUserAssignment" (
    id integer NOT NULL,
    item_id_fk integer NOT NULL,
    role character varying(50) NOT NULL,
    user_id_fk integer NOT NULL,
    created_by_fk integer,
    created_date timestamp with time zone NOT NULL,
    updated_by_fk integer,
    updated_date timestamp with time zone NOT NULL
);

ALTER TABLE plm."productUserAssignment" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm."productUserAssignment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm."productUserAssignment"
    ADD CONSTRAINT "productUserAssignment_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ONLY plm."productUserAssignment"
    ADD CONSTRAINT "productUserAssignment_item_id_fk_fkey" FOREIGN KEY (item_id_fk) REFERENCES plm."itemHeader"(item_id_pk) ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ONLY plm."productUserAssignment"
    ADD CONSTRAINT "productUserAssignment_user_id_fk_fkey" FOREIGN KEY (user_id_fk) REFERENCES app.users(id) ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "productUserAssignment_item_role_key" ON plm."productUserAssignment" USING btree (item_id_fk, role);

CREATE INDEX IF NOT EXISTS "productUserAssignment_user_idx" ON plm."productUserAssignment" USING btree (user_id_fk);

COMMENT ON TABLE plm."productUserAssignment" IS 'Item user role assignments';
