-- Additive: create DesignFlow table in shared schema app.
-- Mapped from DesignFlow `AuditLog` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.2.
-- Purpose: Audit / activity store
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS app."AuditLog" (
    id integer NOT NULL,
    "oldValue" text,
    "newValue" text,
    username character varying(255),
    "actionType" character varying(255),
    "actionDate" timestamp without time zone,
    user_id_fk integer,
    "moduleName" character varying(255),
    ref_id_fk integer,
    element_id character varying(255)
);

ALTER TABLE app."AuditLog" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app."AuditLog_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY app."AuditLog"
    ADD CONSTRAINT "AuditLog_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE app."AuditLog" IS 'Audit / activity store';
