-- Additive: create DesignFlow table in shared schema core.
-- Mapped from DesignFlow `vendor` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.1.
-- Purpose: PLM vendor accounts; map to core factory/vendor model
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS core.vendor (
    vendor_id integer NOT NULL,
    vendor_name character varying(255),
    vendor_email character varying(255),
    vendor_phone1 character varying(255),
    vendor_phone2 character varying(255),
    vendor_status character varying(255),
    vendor_country character varying(255),
    vendor_address1 character varying(255),
    vendor_address2 character varying(255),
    vendor_access character varying(255),
    vendor_passw character varying,
    vendor_lastname character varying,
    vendor_company_nickname character varying,
    vendor_company_name character varying,
    "vendor_wechatId" character varying,
    factory_id_fk integer,
    vendor_profile_photo text
);

ALTER TABLE core.vendor ALTER COLUMN vendor_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME core.vendor_vendor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY core.vendor
    ADD CONSTRAINT vendor_pkey PRIMARY KEY (vendor_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE core.vendor IS 'PLM vendor accounts; map to core factory/vendor model';
