-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `licensingStatus` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Item licensing status thread
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm."licensingStatus" (
    id integer NOT NULL,
    date character varying,
    feedback character varying,
    package boolean,
    status character varying,
    "from" character varying,
    moduser character varying,
    itemheader_id_fk integer,
    attachments jsonb,
    assignor_id integer,
    assignee_id integer,
    tagged_group_id integer,
    pop_comments text,
    assignee_ids jsonb DEFAULT '[]'::jsonb NOT NULL
);

ALTER TABLE plm."licensingStatus" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm."licensingStatus_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm."licensingStatus"
    ADD CONSTRAINT "licensingStatus_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ONLY plm."licensingStatus"
    ADD CONSTRAINT "licensingStatus_tagged_group_id_fkey" FOREIGN KEY (tagged_group_id) REFERENCES plm.groups(id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE plm."licensingStatus" IS 'Item licensing status thread';
