-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `ProductNickname` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Product nickname config (MG FK refs)
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm."ProductNickname" (
    id integer NOT NULL,
    nickname character varying(255) NOT NULL,
    material_id_fk integer,
    construction_id_fk integer,
    feature_id_fk integer,
    size_id_fk integer,
    licensor_id_fk integer,
    property_id_fk integer,
    sub_format_id_fk integer,
    art_source_id_fk integer,
    artist_id_fk integer,
    treatment_id_fk integer,
    group_id_fk integer,
    demographic_id_fk integer
);

ALTER TABLE plm."ProductNickname" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm."ProductNickname_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm."ProductNickname"
    ADD CONSTRAINT "ProductNickname_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE plm."ProductNickname" IS 'Product nickname config (MG FK refs)';
