-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `sample_attachment` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Sample files
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm.sample_attachment (
    sample_attachment_id integer NOT NULL,
    attachment_type character varying(50) NOT NULL,
    attachment_display_name character varying(255),
    attachment_link character varying(255) NOT NULL,
    sample_id_fk integer NOT NULL,
    primary_image boolean DEFAULT false,
    uuid uuid,
    "sample_attachment_fileName" character varying(255),
    "sample_attachment_createdTime" character varying(255),
    "sample_attachment_createdUser" character varying(255),
    "sample_attachment_modTime" character varying(255),
    "sample_attachment_modUser" character varying(255)
);

ALTER TABLE plm.sample_attachment ALTER COLUMN sample_attachment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm.sample_attachment_sample_attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample_attachment
    ADD CONSTRAINT sample_attachment_pkey PRIMARY KEY (sample_attachment_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample_attachment
    ADD CONSTRAINT sample_attachment_sample_id_fk_fkey FOREIGN KEY (sample_id_fk) REFERENCES plm.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_sample_attachment_sample_id_fk ON plm.sample_attachment USING btree (sample_id_fk);

COMMENT ON TABLE plm.sample_attachment IS 'Sample files';
