-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260304154527
-- Name: 439d6c5b_1ace_4898_996e_b2c88547bd50
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
