-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `sample_box` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Sample boxes
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm.sample_box (
    box_id_pk integer NOT NULL,
    box_label character varying(255),
    direction character varying(10),
    status character varying(40),
    origin_office character varying(20),
    dest_office character varying(20),
    final_destination character varying(50),
    tracking_number character varying(255),
    shipped_date timestamp with time zone,
    notes text,
    "box_createdTime" character varying(255),
    "box_createdUser" character varying(255),
    "box_modTime" character varying(255),
    "box_modUser" character varying(255)
);

ALTER TABLE plm.sample_box ALTER COLUMN box_id_pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm.sample_box_box_id_pk_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample_box
    ADD CONSTRAINT sample_box_pkey PRIMARY KEY (box_id_pk);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE plm.sample_box IS 'Sample boxes';
