-- Sample Tracking Release A: stable workflow/path identity, neutral creation
-- batches, canonical carriers, shipment headers, warehouse custody and the
-- server-side inventory read model. Physical custody remains exclusively in
-- dflow.sample_movement.
BEGIN;

CREATE TABLE dflow.sample_creation_batch (
  creation_batch_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mode text NOT NULL CHECK (mode IN ('single','group')),
  entry_method text NOT NULL CHECK (entry_method IN ('manual','inventory_selection','import_confirm')),
  idempotency_key text NOT NULL CHECK (btrim(idempotency_key) <> ''),
  request_hash text NOT NULL CHECK (btrim(request_hash) <> ''),
  created_by_user text NOT NULL CHECK (btrim(created_by_user) <> ''),
  created_by_role text NOT NULL CHECK (btrim(created_by_role) <> ''),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (created_by_user, idempotency_key)
);

CREATE TABLE dflow.sample_workflow (
  sample_workflow_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_id_fk integer NOT NULL UNIQUE REFERENCES dflow.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
  creation_batch_id bigint REFERENCES dflow.sample_creation_batch(creation_batch_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  workflow_type text NOT NULL CHECK (workflow_type IN (
    'nyo_purchased_factory_reference','vendor_unsolicited_offer',
    'nyo_factory_make_request','nyo_remote_china_inventory_request'
  )),
  business_path text NOT NULL CHECK (business_path IN (
    'factory_ningbo_nyo','factory_ningbo_customer','factory_nyo',
    'china_warehouse_ningbo_nyo','china_warehouse_ningbo_customer',
    'nyo_factory','nyo_ningbo','ningbo_nyo','ningbo_customer'
  )),
  workflow_state text NOT NULL DEFAULT 'draft' CHECK (workflow_state IN (
    'draft','confirmed','packed','shipped','received','delivered_reported',
    'delivery_exception','cancelled'
  )),
  contract_version text NOT NULL DEFAULT 'sample-tracking-release-a-v1'
    CHECK (contract_version = 'sample-tracking-release-a-v1'),
  created_by_user text NOT NULL CHECK (btrim(created_by_user) <> ''),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sample_workflow_valid_flow_path CHECK (
    (workflow_type = 'nyo_purchased_factory_reference' AND business_path IN ('nyo_ningbo','nyo_factory')) OR
    (workflow_type = 'vendor_unsolicited_offer' AND business_path IN ('factory_ningbo_nyo','factory_nyo')) OR
    (workflow_type = 'nyo_factory_make_request' AND business_path IN ('factory_ningbo_nyo','factory_ningbo_customer')) OR
    (workflow_type = 'nyo_remote_china_inventory_request' AND business_path IN (
      'china_warehouse_ningbo_nyo','china_warehouse_ningbo_customer','ningbo_nyo','ningbo_customer'
    ))
  )
);

CREATE INDEX sample_workflow_queue_idx
  ON dflow.sample_workflow (workflow_type, workflow_state, updated_at DESC);

CREATE TABLE dflow.sample_path_revision (
  sample_path_revision_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_workflow_id bigint NOT NULL REFERENCES dflow.sample_workflow(sample_workflow_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  revision integer NOT NULL CHECK (revision > 0),
  business_path text NOT NULL CHECK (business_path IN (
    'factory_ningbo_nyo','factory_ningbo_customer','factory_nyo',
    'china_warehouse_ningbo_nyo','china_warehouse_ningbo_customer',
    'nyo_factory','nyo_ningbo','ningbo_nyo','ningbo_customer'
  )),
  reason text NOT NULL CHECK (btrim(reason) <> ''),
  changed_by_user text NOT NULL CHECK (btrim(changed_by_user) <> ''),
  changed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (sample_workflow_id, revision)
);

CREATE OR REPLACE FUNCTION dflow.validate_sample_path_revision()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_workflow_type text;
  v_expected_revision integer;
BEGIN
  SELECT workflow_type INTO v_workflow_type
  FROM dflow.sample_workflow
  WHERE sample_workflow_id = NEW.sample_workflow_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Sample workflow % does not exist', NEW.sample_workflow_id USING ERRCODE = '23503';
  END IF;
  IF NOT (
    (v_workflow_type = 'nyo_purchased_factory_reference' AND NEW.business_path IN ('nyo_ningbo','nyo_factory')) OR
    (v_workflow_type = 'vendor_unsolicited_offer' AND NEW.business_path IN ('factory_ningbo_nyo','factory_nyo')) OR
    (v_workflow_type = 'nyo_factory_make_request' AND NEW.business_path IN ('factory_ningbo_nyo','factory_ningbo_customer')) OR
    (v_workflow_type = 'nyo_remote_china_inventory_request' AND NEW.business_path IN (
      'china_warehouse_ningbo_nyo','china_warehouse_ningbo_customer','ningbo_nyo','ningbo_customer'
    ))
  ) THEN
    RAISE EXCEPTION 'Path % is invalid for workflow type %', NEW.business_path, v_workflow_type
      USING ERRCODE = '23514';
  END IF;
  SELECT COALESCE(max(revision),0) + 1 INTO v_expected_revision
  FROM dflow.sample_path_revision WHERE sample_workflow_id = NEW.sample_workflow_id;
  IF NEW.revision <> v_expected_revision THEN
    RAISE EXCEPTION 'Path revision must be %, received %', v_expected_revision, NEW.revision
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER sample_path_revision_validate
BEFORE INSERT ON dflow.sample_path_revision
FOR EACH ROW EXECUTE FUNCTION dflow.validate_sample_path_revision();

CREATE OR REPLACE FUNCTION dflow.require_sample_path_revision()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.business_path IS DISTINCT FROM OLD.business_path AND NOT EXISTS (
    SELECT 1 FROM dflow.sample_path_revision r
    WHERE r.sample_workflow_id = NEW.sample_workflow_id
      AND r.business_path = NEW.business_path
      AND r.revision = (SELECT max(r2.revision) FROM dflow.sample_path_revision r2
                        WHERE r2.sample_workflow_id = NEW.sample_workflow_id)
  ) THEN
    RAISE EXCEPTION 'Insert the append-only path revision before changing the workflow path'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER sample_workflow_path_revision_required
BEFORE UPDATE OF business_path ON dflow.sample_workflow
FOR EACH ROW EXECUTE FUNCTION dflow.require_sample_path_revision();

CREATE OR REPLACE FUNCTION dflow.apply_sample_path_revision()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  UPDATE dflow.sample_workflow
  SET business_path = NEW.business_path, updated_at = NEW.changed_at
  WHERE sample_workflow_id = NEW.sample_workflow_id;
  RETURN NEW;
END $$;

CREATE TRIGGER sample_path_revision_apply
AFTER INSERT ON dflow.sample_path_revision
FOR EACH ROW EXECUTE FUNCTION dflow.apply_sample_path_revision();

CREATE OR REPLACE FUNCTION dflow.reject_sample_path_revision_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Sample path revisions are append-only' USING ERRCODE = '55000';
END $$;

CREATE TRIGGER sample_path_revision_immutable
BEFORE UPDATE OR DELETE ON dflow.sample_path_revision
FOR EACH ROW EXECUTE FUNCTION dflow.reject_sample_path_revision_mutation();

CREATE TABLE dflow.sample_carrier (
  sample_carrier_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carrier_code text NOT NULL UNIQUE CHECK (carrier_code = lower(carrier_code) AND btrim(carrier_code) <> ''),
  display_name text NOT NULL UNIQUE CHECK (btrim(display_name) <> ''),
  tracking_url_template text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO dflow.sample_carrier (carrier_code, display_name, tracking_url_template)
VALUES
  ('ups','UPS','https://www.ups.com/track?tracknum={tracking_number}'),
  ('fedex','FedEx','https://www.fedex.com/fedextrack/?trknbr={tracking_number}'),
  ('dhl','DHL','https://www.dhl.com/global-en/home/tracking.html?tracking-id={tracking_number}'),
  ('usps','USPS','https://tools.usps.com/go/TrackConfirmAction?tLabels={tracking_number}');

CREATE TABLE dflow.sample_shipment (
  sample_shipment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carrier_id smallint REFERENCES dflow.sample_carrier(sample_carrier_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  tracking_number text CHECK (tracking_number IS NULL OR btrim(tracking_number) <> ''),
  origin_location_type text NOT NULL CHECK (origin_location_type IN ('factory','office','customer','warehouse')),
  origin_location_id text NOT NULL CHECK (btrim(origin_location_id) <> ''),
  destination_location_type text NOT NULL CHECK (destination_location_type IN ('factory','office','customer','warehouse')),
  destination_location_id text NOT NULL CHECK (btrim(destination_location_id) <> ''),
  state text NOT NULL DEFAULT 'draft' CHECK (state IN (
    'draft','packed','shipped','received','delivered_reported','delivery_exception','cancelled'
  )),
  shipped_at timestamptz,
  received_at timestamptz,
  actor_user text NOT NULL CHECK (btrim(actor_user) <> ''),
  actor_role text NOT NULL CHECK (btrim(actor_role) <> ''),
  idempotency_key text NOT NULL UNIQUE CHECK (btrim(idempotency_key) <> ''),
  request_hash text NOT NULL CHECK (btrim(request_hash) <> ''),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (origin_location_type <> destination_location_type OR origin_location_id <> destination_location_id),
  CHECK ((carrier_id IS NULL) = (tracking_number IS NULL)),
  CHECK (state NOT IN ('shipped','received','delivered_reported','delivery_exception') OR shipped_at IS NOT NULL),
  CHECK (state <> 'received' OR received_at IS NOT NULL)
);

CREATE UNIQUE INDEX sample_shipment_active_tracking_uniq
  ON dflow.sample_shipment (carrier_id, lower(tracking_number))
  WHERE carrier_id IS NOT NULL AND state <> 'cancelled';

ALTER TABLE dflow.sample_shipment_line
  ADD COLUMN sample_shipment_id bigint REFERENCES dflow.sample_shipment(sample_shipment_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE dflow.sample_shipment_line ALTER COLUMN box_id_fk DROP NOT NULL;
ALTER TABLE dflow.sample_shipment_line ADD CONSTRAINT sample_shipment_line_box_or_header_check
  CHECK (box_id_fk IS NOT NULL OR sample_shipment_id IS NOT NULL);

CREATE OR REPLACE FUNCTION dflow.validate_sample_shipment_line_header()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_header dflow.sample_shipment;
BEGIN
  IF NEW.sample_shipment_id IS NULL THEN RETURN NEW; END IF;
  SELECT * INTO v_header FROM dflow.sample_shipment WHERE sample_shipment_id=NEW.sample_shipment_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Shipment header % does not exist',NEW.sample_shipment_id USING ERRCODE='23503';
  END IF;
  IF NEW.origin_location_type IS DISTINCT FROM v_header.origin_location_type
     OR NEW.origin_location_id IS DISTINCT FROM v_header.origin_location_id
     OR NEW.destination_location_type IS DISTINCT FROM v_header.destination_location_type
     OR NEW.destination_location_id IS DISTINCT FROM v_header.destination_location_id THEN
    RAISE EXCEPTION 'Shipment line route must match shipment header %',NEW.sample_shipment_id
      USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER sample_shipment_line_header_route
BEFORE INSERT OR UPDATE OF sample_shipment_id,origin_location_type,origin_location_id,
  destination_location_type,destination_location_id ON dflow.sample_shipment_line
FOR EACH ROW EXECUTE FUNCTION dflow.validate_sample_shipment_line_header();
CREATE INDEX sample_shipment_line_header_idx ON dflow.sample_shipment_line(sample_shipment_id, shipment_line_id)
  WHERE sample_shipment_id IS NOT NULL;

ALTER TABLE dflow.sample_box
  ADD COLUMN current_custody_type text,
  ADD COLUMN current_custody_id text;
ALTER TABLE dflow.sample_box
  ADD CONSTRAINT sample_box_custody_pair_check CHECK (
    (current_custody_type IS NULL AND current_custody_id IS NULL) OR
    (current_custody_type IN ('factory','office','customer','warehouse','in_transit')
      AND current_custody_id IS NOT NULL AND btrim(current_custody_id) <> '')
  );
CREATE UNIQUE INDEX sample_box_active_name_custody_uniq
  ON dflow.sample_box (lower(btrim(box_label)), current_custody_type, current_custody_id)
  WHERE current_custody_type IS NOT NULL AND status NOT IN ('closed','cancelled');

DO $$
DECLARE v_bad bigint;
BEGIN
  SELECT count(*) INTO v_bad FROM dflow.sample_shipment_line
  WHERE route_leg NOT IN (
    'factory_to_ningbo','factory_to_nyc','factory_to_customer',
    'ningbo_to_nyc','ningbo_to_customer','nyc_to_ningbo','nyc_to_factory','nyc_to_customer',
    'ningbo_to_factory','factory_return_to_ningbo','warehouse_to_ningbo'
  );
  IF v_bad > 0 THEN
    RAISE EXCEPTION 'Release A route-leg guard refused % unsupported existing row(s)', v_bad;
  END IF;
END $$;

ALTER TABLE dflow.sample_shipment_line DROP CONSTRAINT sample_shipment_line_route_leg_check;
ALTER TABLE dflow.sample_shipment_line ADD CONSTRAINT sample_shipment_line_route_leg_check CHECK (route_leg IN (
  'factory_to_ningbo','factory_to_nyc','factory_to_customer',
  'ningbo_to_nyc','ningbo_to_customer','nyc_to_ningbo','nyc_to_factory','nyc_to_customer',
  'ningbo_to_factory','factory_return_to_ningbo','warehouse_to_ningbo'
));

ALTER TABLE dflow.sample_shipment_line DROP CONSTRAINT sample_shipment_line_origin_location_type_check;
ALTER TABLE dflow.sample_shipment_line ADD CONSTRAINT sample_shipment_line_origin_location_type_check CHECK (
  origin_location_type IN ('factory','office','customer','warehouse') OR
  (origin_location_type = 'terminal' AND origin_location_id LIKE '%\_office\_inventory')
);
ALTER TABLE dflow.sample_shipment_line DROP CONSTRAINT sample_shipment_line_destination_location_type_check;
ALTER TABLE dflow.sample_shipment_line ADD CONSTRAINT sample_shipment_line_destination_location_type_check
  CHECK (destination_location_type IN ('factory','office','customer','warehouse'));

DO $$
DECLARE v_bad bigint;
BEGIN
  SELECT count(*) INTO v_bad FROM dflow.sample_movement
  WHERE from_location_type NOT IN ('factory','office','customer','warehouse','in_transit','terminal')
     OR to_location_type NOT IN ('factory','office','customer','warehouse','in_transit','terminal');
  IF v_bad > 0 THEN
    RAISE EXCEPTION 'Release A movement guard refused % unsupported existing row(s)', v_bad;
  END IF;
END $$;

ALTER TABLE dflow.sample_movement DROP CONSTRAINT sample_movement_from_location_type_check;
ALTER TABLE dflow.sample_movement ADD CONSTRAINT sample_movement_from_location_type_check
  CHECK (from_location_type IN ('factory','office','customer','warehouse','in_transit','terminal'));
ALTER TABLE dflow.sample_movement DROP CONSTRAINT sample_movement_to_location_type_check;
ALTER TABLE dflow.sample_movement ADD CONSTRAINT sample_movement_to_location_type_check
  CHECK (to_location_type IN ('factory','office','customer','warehouse','in_transit','terminal'));

ALTER TABLE dflow.sample_movement
  ADD COLUMN sample_shipment_id bigint REFERENCES dflow.sample_shipment(sample_shipment_id) ON UPDATE CASCADE ON DELETE RESTRICT;
DO $$
DECLARE v_name text;
BEGIN
  SELECT conname INTO v_name FROM pg_constraint
  WHERE conrelid='dflow.sample_movement'::regclass AND contype='c'
    AND pg_get_constraintdef(oid) LIKE '%box_id_fk IS NOT NULL%'
    AND pg_get_constraintdef(oid) LIKE '%shipment_line_id IS NOT NULL%';
  IF v_name IS NULL THEN
    RAISE EXCEPTION 'Could not identify the existing sample movement transit identity guard';
  END IF;
  EXECUTE format('ALTER TABLE dflow.sample_movement DROP CONSTRAINT %I',v_name);
END $$;
ALTER TABLE dflow.sample_movement DROP CONSTRAINT sample_movement_transit_box_identity_check;
ALTER TABLE dflow.sample_movement ADD CONSTRAINT sample_movement_transit_identity_check CHECK (
  (from_location_type <> 'in_transit' AND to_location_type <> 'in_transit') OR
  (shipment_line_id IS NOT NULL AND (box_id_fk IS NOT NULL OR sample_shipment_id IS NOT NULL))
);
ALTER TABLE dflow.sample_movement ADD CONSTRAINT sample_movement_transit_location_identity_check CHECK (
  (from_location_type <> 'in_transit' OR from_location_id = COALESCE(box_id_fk::text,sample_shipment_id::text)) AND
  (to_location_type <> 'in_transit' OR to_location_id = COALESCE(box_id_fk::text,sample_shipment_id::text))
);

CREATE OR REPLACE FUNCTION dflow.post_sample_movement(
  p_sample_id integer, p_quantity integer,
  p_from_type text, p_from_id text, p_to_type text, p_to_id text,
  p_action text, p_actor_user text, p_actor_role text,
  p_idempotency_key text, p_request_hash text,
  p_box_id integer DEFAULT NULL, p_shipment_line_id bigint DEFAULT NULL,
  p_actor_factory_id integer DEFAULT NULL, p_discrepancy_code text DEFAULT NULL,
  p_discrepancy_details text DEFAULT NULL, p_reversal_of bigint DEFAULT NULL,
  p_from_label text DEFAULT NULL, p_to_label text DEFAULT NULL
) RETURNS dflow.sample_movement LANGUAGE plpgsql SECURITY INVOKER AS $$
DECLARE
  v_existing dflow.sample_movement;
  v_result dflow.sample_movement;
  v_shipment_id bigint;
  v_line_box_id integer;
  v_line_origin_type text;
  v_line_origin_id text;
  v_line_destination_type text;
  v_line_destination_id text;
BEGIN
  PERFORM pg_advisory_xact_lock(21450, p_sample_id);
  SELECT * INTO v_existing FROM dflow.sample_movement
   WHERE sample_id_fk=p_sample_id AND idempotency_key=p_idempotency_key;
  IF FOUND THEN
    IF v_existing.request_hash <> p_request_hash THEN
      RAISE EXCEPTION 'Idempotency key reused with different request' USING ERRCODE='23505';
    END IF;
    RETURN v_existing;
  END IF;
  IF p_shipment_line_id IS NOT NULL THEN
    SELECT sample_shipment_id,box_id_fk,origin_location_type,origin_location_id,
           destination_location_type,destination_location_id
      INTO v_shipment_id,v_line_box_id,v_line_origin_type,v_line_origin_id,
           v_line_destination_type,v_line_destination_id
    FROM dflow.sample_shipment_line
    WHERE shipment_line_id = p_shipment_line_id AND sample_id_fk = p_sample_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Shipment line % does not belong to sample %', p_shipment_line_id, p_sample_id
        USING ERRCODE='23503';
    END IF;
    IF p_box_id IS DISTINCT FROM v_line_box_id THEN
      RAISE EXCEPTION 'Box % does not match shipment line % box %',p_box_id,p_shipment_line_id,v_line_box_id
        USING ERRCODE='23514';
    END IF;
    IF p_action IN ('ship','pack') AND (
      p_from_type IS DISTINCT FROM v_line_origin_type OR p_from_id IS DISTINCT FROM v_line_origin_id
      OR p_to_type <> 'in_transit'
    ) THEN
      RAISE EXCEPTION 'Ship movement route does not match shipment line %',p_shipment_line_id
        USING ERRCODE='23514';
    END IF;
    IF p_action = 'receive' AND (
      p_from_type <> 'in_transit' OR p_to_type IS DISTINCT FROM v_line_destination_type
      OR p_to_id IS DISTINCT FROM v_line_destination_id
    ) THEN
      RAISE EXCEPTION 'Receive movement route does not match shipment line %',p_shipment_line_id
        USING ERRCODE='23514';
    END IF;
  END IF;
  INSERT INTO dflow.sample_movement(sample_id_fk,quantity,from_location_type,from_location_id,
    from_location_label,to_location_type,to_location_id,to_location_label,box_id_fk,shipment_line_id,
    sample_shipment_id,lifecycle_action,actor_user,actor_role,actor_factory_id,idempotency_key,
    request_hash,discrepancy_code,discrepancy_details,reversal_of_movement_id)
  VALUES(p_sample_id,p_quantity,p_from_type,p_from_id,p_from_label,p_to_type,p_to_id,p_to_label,
    p_box_id,p_shipment_line_id,v_shipment_id,p_action,p_actor_user,p_actor_role,p_actor_factory_id,
    p_idempotency_key,p_request_hash,p_discrepancy_code,p_discrepancy_details,p_reversal_of)
  RETURNING * INTO v_result;
  RETURN v_result;
END $$;

CREATE OR REPLACE VIEW dflow.sample_inventory AS
SELECT
  b.sample_id_fk,
  b.location_type,
  CASE
    WHEN b.location_type = 'terminal' AND b.location_id = 'nyc_office_inventory' THEN 'office'
    WHEN b.location_type = 'terminal' AND b.location_id = 'ningbo_office_inventory' THEN 'office'
    ELSE b.location_type
  END AS product_location_type,
  CASE
    WHEN b.location_id = 'nyc_office_inventory' THEN 'nyc'
    WHEN b.location_id = 'ningbo_office_inventory' THEN 'ningbo'
    ELSE b.location_id
  END AS product_location_id,
  b.quantity,
  max(m.occurred_at) AS available_since,
  EXISTS (
    SELECT 1 FROM dflow.sample_shipment_item si
    WHERE si.sample_id_fk = b.sample_id_fk AND si.box_id_fk IS NOT NULL
  ) AS is_boxed,
  (b.location_type = 'in_transit') AS is_in_transit,
  (b.quantity > 0 AND b.location_type <> 'in_transit') AS is_eligible,
  CASE WHEN b.quantity <= 0 THEN 'no_balance'
       WHEN b.location_type = 'in_transit' THEN 'in_transit'
       ELSE NULL END AS ineligibility_reason
FROM dflow.sample_balance_by_location b
LEFT JOIN dflow.sample_movement m
  ON m.sample_id_fk = b.sample_id_fk
 AND ((m.to_location_type = b.location_type AND m.to_location_id = b.location_id)
   OR (m.from_location_type = b.location_type AND m.from_location_id = b.location_id))
WHERE b.quantity > 0
GROUP BY b.sample_id_fk,b.location_type,b.location_id,b.quantity;

CREATE INDEX sample_movement_inventory_idx
  ON dflow.sample_movement (to_location_type, to_location_id, occurred_at DESC, sample_id_fk);

COMMENT ON TABLE dflow.sample_creation_batch IS 'Neutral atomic guided-create batch for single, group, inventory-selection, or confirmed import creation.';
COMMENT ON TABLE dflow.sample_workflow IS 'Stable Release A workflow and business-path identity. Legacy samples have no row and remain unclassified.';
COMMENT ON TABLE dflow.sample_path_revision IS 'Append-only audit of path changes; never rewrite prior revisions.';
COMMENT ON TABLE dflow.sample_carrier IS 'Canonical manual carrier choices. Carrier automation is deferred.';
COMMENT ON TABLE dflow.sample_shipment IS 'Shipment header shared by boxed and unboxed shipment lines; movements remain custody truth.';
COMMENT ON VIEW dflow.sample_inventory IS 'Server inventory read model derived from movement balances, including parked office leftovers.';

REVOKE ALL ON dflow.sample_creation_batch,dflow.sample_workflow,dflow.sample_path_revision,
  dflow.sample_carrier,dflow.sample_shipment,dflow.sample_inventory FROM anon,authenticated;
REVOKE ALL ON FUNCTION dflow.reject_sample_path_revision_mutation(),
  dflow.validate_sample_path_revision(),dflow.require_sample_path_revision(),
  dflow.apply_sample_path_revision(),dflow.validate_sample_shipment_line_header()
  FROM PUBLIC,anon,authenticated;

COMMIT;
