-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `StandardizedDetail` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Standardized product detail config
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm."StandardizedDetail" (
    id integer NOT NULL,
    std_v_id_fk integer,
    std_size_id_fk integer,
    std_prod_id_fk integer
);

ALTER TABLE plm."StandardizedDetail" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm."StandardizedDetail_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm."StandardizedDetail"
    ADD CONSTRAINT "StandardizedDetail_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "StandardizedVersionDetail_pkey" ON plm."StandardizedDetail" USING btree (id);

COMMENT ON TABLE plm."StandardizedDetail" IS 'Standardized product detail config';
