-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `itemType` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Standardized item type templates
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm."itemType" (
    item_type_id integer NOT NULL,
    item_type_name character varying(100) NOT NULL,
    item_type_description text NOT NULL,
    item_type_img_thumbnail character varying(255) NOT NULL,
    item_type_img_fullsize character varying(255) NOT NULL,
    item_type_status character varying(16) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_user_fk character varying(20),
    created_time_date timestamp with time zone,
    mod_user_fk character varying(20),
    mod_time_date timestamp with time zone
);

ALTER TABLE plm."itemType" ALTER COLUMN item_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm."itemType_item_type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm."itemType"
    ADD CONSTRAINT "itemType_pkey" PRIMARY KEY (item_type_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "itemType_name_key" ON plm."itemType" USING btree (item_type_name);

CREATE INDEX IF NOT EXISTS "itemType_status_idx" ON plm."itemType" USING btree (item_type_status);

COMMENT ON TABLE plm."itemType" IS 'Standardized item type templates';
