-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260225020812
-- Name: 26ef8192_3fc9_4b87_a46b_08daca83a539
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
