-- Durable: core."Factory" as a real table replica of dflow."Factory"
-- (same columns / integer PK). Not a view; not linked via factory_source_ref.

-- Replace any prior compat view
drop view if exists core."Factory";

create table if not exists core."Factory" (
  id integer not null,
  factory_name character varying,
  factory_nickname character varying,
  factory_status character varying,
  factory_access character varying,
  sort_order integer,
  factory_country character varying(255),
  constraint "Factory_pkey" primary key (id)
);

-- Identity for new inserts (match dflow style)
do $$
begin
  if not exists (
    select 1
    from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'core'
      and c.relname = 'Factory'
      and a.attname = 'id'
      and a.attidentity <> ''
  ) then
    alter table core."Factory"
      alter column id add generated by default as identity;
  end if;
exception
  when others then
    -- If identity already present or conflict, leave as-is
    raise notice 'core."Factory".id identity setup skipped: %', sqlerrm;
end $$;

grant select, insert, update, delete on core."Factory" to service_role;
grant select, insert, update, delete on core."Factory" to authenticated;

comment on table core."Factory" is
  'PLM Factory table replica (same shape as dflow."Factory"). '
  'Synced from dflow for multi-schema DesignFlow; writable table, not a view.';
