-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260303005852
-- Name: 61c05b26_7dce_43c3_ac7a_4ebc7b792fd9
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
