-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260302223637
-- Name: 02e64966_41b2_49c9_ae71_949f9cfe7be8
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
