-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260310201059
-- Name: 43576fe3_0e01_49b0_93b4_99d5c4504e33
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
