-- Shipment intent is a plan; sample_movement (next migration) records custody.
BEGIN;

CREATE TABLE IF NOT EXISTS dflow.sample_shipment_line (
  shipment_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_id_fk integer NOT NULL REFERENCES dflow.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
  box_id_fk integer NOT NULL REFERENCES dflow.sample_box(box_id_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
  quantity_intended integer NOT NULL CHECK (quantity_intended > 0),
  origin_location_type text NOT NULL CHECK (origin_location_type IN ('factory','office','customer')),
  origin_location_id text NOT NULL CHECK (btrim(origin_location_id) <> ''),
  destination_location_type text NOT NULL CHECK (destination_location_type IN ('factory','office','customer')),
  destination_location_id text NOT NULL CHECK (btrim(destination_location_id) <> ''),
  route_leg text NOT NULL CHECK (route_leg IN ('factory_to_ningbo','factory_to_nyc','ningbo_to_nyc','nyc_to_customer','nyc_to_factory','direct_to_customer','return')),
  state text NOT NULL DEFAULT 'packed' CHECK (state IN ('packed','shipped','partially_received','received','cancelled')),
  idempotency_key text NOT NULL CHECK (btrim(idempotency_key) <> ''),
  request_hash text NOT NULL CHECK (btrim(request_hash) <> ''),
  created_by_user text NOT NULL,
  created_by_role text NOT NULL,
  created_by_factory_id integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (sample_id_fk, idempotency_key),
  CHECK (origin_location_type <> destination_location_type OR origin_location_id <> destination_location_id)
);

CREATE INDEX IF NOT EXISTS sample_shipment_line_box_idx ON dflow.sample_shipment_line(box_id_fk, state);
CREATE INDEX IF NOT EXISTS sample_shipment_line_sample_idx ON dflow.sample_shipment_line(sample_id_fk, created_at DESC);

ALTER TABLE dflow.sample_shipment_item ADD COLUMN IF NOT EXISTS quantity_intended integer;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='dflow.sample_shipment_item'::regclass AND conname='sample_shipment_item_quantity_positive') THEN
    ALTER TABLE dflow.sample_shipment_item ADD CONSTRAINT sample_shipment_item_quantity_positive
      CHECK (quantity_intended IS NULL OR quantity_intended > 0);
  END IF;
END $$;

COMMIT;
