-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260220145722
-- Name: 1aac30f3_e67e_425d_b8fe_27b286ffe4eb
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
