-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260312162210
-- Name: c1a532d8_775f_4e73_839a_eb928037fd20
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
