-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260308144405
-- Name: 5697e977_0cd5_4252_a9d0_c60b3f7aae15
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
