-- Restore the SEVENTH sample-tracking table to the dflow (app-runtime) schema.
--
-- Root cause: the 2026-07-21 restore migration
--   20260721201500_restore_dflow_sample_tracking_tables.sql
-- recreated only SIX of the seven sample-tracking tables in `dflow` (sample,
-- sample_box, sample_factory_group, sample_event, sample_comments,
-- sample_attachment). It omitted the seventh, `sample_shipment_item`, which
-- still exists only in the `plm` schema. Every running DesignFlow service is
-- pinned to a single SCHEMA=dflow, so the tracking service failed at runtime
-- with:
--   relation "dflow.sample_shipment_item" does not exist
-- and its direct factory->NYC check-in path fails closed (409) because the
-- membership model is unavailable (designflow-tracking sample.model.js
-- proveFactoryToNyc()).
--
-- Verified state before authoring (read-only, 2026-07-22), preview
-- (rjyboqwcdzcocqgmsyel) AND production (qsllyeztdwjgirsysgai):
--   * dflow.sample_shipment_item : ABSENT in both environments
--   * plm.sample_shipment_item   : present, 0 rows, no duplicate memberships
--   * dflow sample cluster row counts are tiny (prod: sample=3, attachment=1,
--     event=3; everything else 0. preview: all 0). No memberships exist
--     anywhere, so no data reconciliation is required for this repair.
--
-- This recreates the table in `dflow`, structurally identical to the `plm`
-- copy, and re-adds the two intra-cluster foreign keys with the SAME
-- ON UPDATE/DELETE rules as plm. It is additive (touches nothing that already
-- works) and reversible (DROP the one dflow table). It is written to be safe
-- whether dflow.sample_shipment_item is missing OR already present (idempotent
-- guards), per fix_sample_tracking_schema.md section 5.1.
--
-- Deliberate difference from a bare LIKE: the plm copy carries only its primary
-- key index, so this migration adds the two FK-supporting lookup indexes the
-- membership/tenancy reads need (mirroring how dflow.sample already indexes
-- box_id_fk).

BEGIN;

-- INCLUDING ALL copies columns, the GENERATED BY DEFAULT AS IDENTITY primary
-- key (each table gets its own fresh sequence), and any check/unique
-- constraints and indexes. LIKE does NOT copy foreign keys; those are added
-- explicitly below.
CREATE TABLE IF NOT EXISTS dflow.sample_shipment_item
  (LIKE plm.sample_shipment_item INCLUDING ALL);

-- Intra-cluster foreign keys (mirroring plm exactly), added idempotently so the
-- migration is safe if the table already existed with the constraints in place.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'dflow.sample_shipment_item'::regclass
      AND conname = 'sample_shipment_item_sample_id_fk_fkey'
  ) THEN
    ALTER TABLE dflow.sample_shipment_item
      ADD CONSTRAINT sample_shipment_item_sample_id_fk_fkey
      FOREIGN KEY (sample_id_fk) REFERENCES dflow.sample (sample_id_pk)
      ON UPDATE CASCADE ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'dflow.sample_shipment_item'::regclass
      AND conname = 'sample_shipment_item_box_id_fk_fkey'
  ) THEN
    ALTER TABLE dflow.sample_shipment_item
      ADD CONSTRAINT sample_shipment_item_box_id_fk_fkey
      FOREIGN KEY (box_id_fk) REFERENCES dflow.sample_box (box_id_pk)
      ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
END $$;

-- FK-supporting indexes for membership / tenancy lookups (the plm copy carried
-- only the primary-key index).
CREATE INDEX IF NOT EXISTS sample_shipment_item_sample_id_fk_idx
  ON dflow.sample_shipment_item (sample_id_fk);
CREATE INDEX IF NOT EXISTS sample_shipment_item_box_id_fk_idx
  ON dflow.sample_shipment_item (box_id_fk);

COMMIT;
