-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `sample` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Sample tracking
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm.sample (
    sample_id_pk integer NOT NULL,
    origin character varying(20) NOT NULL,
    direction character varying(10) NOT NULL,
    sample_name character varying(255),
    quantity integer,
    retail_price numeric(12,2),
    fob_cost numeric(12,2),
    customer_id_fk integer,
    courier character varying(20),
    tracking_number character varying(255),
    factory_id_fk integer,
    item_id_fk integer,
    prod_order_no_fk character varying(255),
    factory_group_id_fk integer,
    box_id_fk integer,
    status character varying(40) NOT NULL,
    office_location character varying(20),
    next_stop character varying(50),
    final_destination character varying(50),
    notes text,
    "sample_createdTime" character varying(255),
    "sample_createdUser" character varying(255),
    "sample_modTime" character varying(255),
    "sample_modUser" character varying(255)
);

ALTER TABLE plm.sample ALTER COLUMN sample_id_pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm.sample_sample_id_pk_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample
    ADD CONSTRAINT sample_pkey PRIMARY KEY (sample_id_pk);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample
    ADD CONSTRAINT sample_box_id_fk_fkey FOREIGN KEY (box_id_fk) REFERENCES plm.sample_box(box_id_pk) ON UPDATE CASCADE ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample
    ADD CONSTRAINT sample_factory_group_id_fk_fkey FOREIGN KEY (factory_group_id_fk) REFERENCES plm.sample_factory_group(factory_group_id_pk) ON UPDATE CASCADE ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_sample_box_id_fk ON plm.sample USING btree (box_id_fk);

COMMENT ON TABLE plm.sample IS 'Sample tracking';
