-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260304162110
-- Name: 04c4adbe_bd28_49b1_a234_267e4f9626b6
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
