-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `item_prod_order_detail_associations` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Item â†” prod order line bridge
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm.item_prod_order_detail_associations (
    id integer NOT NULL,
    item_header_id integer NOT NULL,
    prod_order_detail_pkey integer NOT NULL,
    matched_item_number character varying(100) NOT NULL,
    master_quantity numeric,
    match_source character varying(50) DEFAULT 'item_number'::character varying NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

ALTER TABLE plm.item_prod_order_detail_associations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm.item_prod_order_detail_associations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm.item_prod_order_detail_associations
    ADD CONSTRAINT item_prod_order_detail_associ_item_header_id_prod_order_det_key UNIQUE (item_header_id, prod_order_detail_pkey);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ONLY plm.item_prod_order_detail_associations
    ADD CONSTRAINT item_prod_order_detail_associations_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ONLY plm.item_prod_order_detail_associations
    ADD CONSTRAINT item_prod_order_detail_associations_item_header_id_fkey FOREIGN KEY (item_header_id) REFERENCES plm."itemHeader"(item_id_pk) ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ONLY plm.item_prod_order_detail_associations
    ADD CONSTRAINT item_prod_order_detail_associations_prod_order_detail_pkey_fkey FOREIGN KEY (prod_order_detail_pkey) REFERENCES plm."ProdOrderDetail"(pkey) ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS item_prod_order_detail_associations_item_header_idx ON plm.item_prod_order_detail_associations USING btree (item_header_id);

CREATE INDEX IF NOT EXISTS item_prod_order_detail_associations_matched_item_number_idx ON plm.item_prod_order_detail_associations USING btree (matched_item_number);

CREATE INDEX IF NOT EXISTS item_prod_order_detail_associations_prod_detail_idx ON plm.item_prod_order_detail_associations USING btree (prod_order_detail_pkey);

CREATE UNIQUE INDEX IF NOT EXISTS item_prod_order_detail_associations_unique_pair ON plm.item_prod_order_detail_associations USING btree (item_header_id, prod_order_detail_pkey);

COMMENT ON TABLE plm.item_prod_order_detail_associations IS 'Item â†” prod order line bridge';
