-- Durable, auditable spreadsheet preview/confirmation records.
BEGIN;

CREATE TABLE IF NOT EXISTS dflow.sample_import_job (
  import_job_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_version text NOT NULL,
  content_hash text NOT NULL CHECK (btrim(content_hash) <> ''),
  source_filename text NOT NULL,
  private_object_key text,
  uploader_user text NOT NULL,
  uploader_role text NOT NULL,
  uploader_factory_id integer,
  state text NOT NULL DEFAULT 'uploaded' CHECK (state IN ('uploaded','validated','confirmation_pending','confirmed','failed')),
  row_count integer NOT NULL DEFAULT 0 CHECK (row_count >= 0),
  warning_count integer NOT NULL DEFAULT 0 CHECK (warning_count >= 0),
  error_count integer NOT NULL DEFAULT 0 CHECK (error_count >= 0),
  photo_count integer NOT NULL DEFAULT 0 CHECK (photo_count >= 0),
  sample_count integer NOT NULL DEFAULT 0 CHECK (sample_count >= 0),
  box_count integer NOT NULL DEFAULT 0 CHECK (box_count >= 0),
  confirmation_idempotency_key text,
  confirmation_request_hash text,
  failure_details text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(uploader_user, content_hash),
  UNIQUE(confirmation_idempotency_key),
  CHECK ((confirmation_idempotency_key IS NULL) = (confirmation_request_hash IS NULL))
);

CREATE TABLE IF NOT EXISTS dflow.sample_import_row (
  import_row_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_job_id bigint NOT NULL REFERENCES dflow.sample_import_job(import_job_id) ON UPDATE CASCADE ON DELETE CASCADE,
  row_number integer NOT NULL CHECK (row_number > 0),
  normalized_values jsonb NOT NULL DEFAULT '{}'::jsonb,
  validation_errors jsonb NOT NULL DEFAULT '[]'::jsonb,
  validation_warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
  image_state text NOT NULL DEFAULT 'none' CHECK (image_state IN ('none','pending','stored','failed')),
  image_object_key text,
  resolution jsonb,
  resulting_sample_id integer REFERENCES dflow.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
  resulting_box_id integer REFERENCES dflow.sample_box(box_id_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(import_job_id,row_number)
);

CREATE INDEX IF NOT EXISTS sample_import_job_state_idx ON dflow.sample_import_job(state,created_at);
CREATE INDEX IF NOT EXISTS sample_import_row_job_idx ON dflow.sample_import_row(import_job_id,row_number);
REVOKE ALL ON dflow.sample_import_job, dflow.sample_import_row FROM anon, authenticated;

COMMIT;
