-- derived-from: 20260818024441
-- (dflow.validate_sample_path_revision() is re-derived in full from the body
--  last replaced by 20260818024441; that base must be present in the target.)
--
-- Issue #2136 -- dflow Sample Tracking: a sample a factory is asked to MAKE may
-- ship straight from the factory, to New York or to the customer, without
-- passing through Ningbo (owner-confirmed 2026-09-02).
--
-- Two widenings, and nothing else:
--   1. 'factory_customer' joins the allowed business_path value list on
--      dflow.sample_workflow and dflow.sample_path_revision.
--   2. workflow_type 'nyo_factory_make_request' may use 'factory_nyo' and
--      'factory_customer' in addition to 'factory_ningbo_nyo' and
--      'factory_ningbo_customer'.
--
-- The table CHECK dflow.sample_workflow.sample_workflow_valid_flow_path and the
-- BEFORE INSERT trigger function dflow.validate_sample_path_revision() are two
-- copies of one rule; both are widened identically here so a path revision can
-- never take a value the workflow table refuses, or the reverse.
--
-- The factory_to_customer route leg already exists
-- (20260724040000_sample_shipment_line_route_legs_explicit.sql) and is untouched.
-- Widening only permits more, so no existing row can violate the new rule and no
-- data migration is required. Constraint and function names are unchanged.
-- Re-applying this file is a no-op: every step is drop-and-recreate or
-- CREATE OR REPLACE against the same names.

BEGIN;

-- Preconditions -------------------------------------------------------------
DO $$
BEGIN
  IF to_regclass('dflow.sample_workflow') IS NULL THEN
    RAISE EXCEPTION 'Issue #2136 requires dflow.sample_workflow to exist';
  END IF;
  IF to_regclass('dflow.sample_path_revision') IS NULL THEN
    RAISE EXCEPTION 'Issue #2136 requires dflow.sample_path_revision to exist';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'dflow' AND p.proname = 'validate_sample_path_revision'
  ) THEN
    RAISE EXCEPTION 'Issue #2136 requires dflow.validate_sample_path_revision() to exist';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE n.nspname = 'dflow' AND t.relname = 'sample_workflow'
      AND c.conname = 'sample_workflow_valid_flow_path'
  ) THEN
    RAISE EXCEPTION 'Issue #2136 requires constraint sample_workflow_valid_flow_path to exist';
  END IF;
END $$;

-- 1. Add factory_customer to the allowed business_path value list ------------
-- The two value-list CHECKs are column constraints, so their names were
-- generated by the server when 20260814130000 created the tables. Both names
-- are deterministic and are asserted here before anything is dropped, so the
-- names below are recreated exactly and this migration fails closed rather than
-- leaving a second, differently named constraint behind.
DO $$
DECLARE
  r          record;
  v_name     text;
  v_count    integer;
BEGIN
  FOR r IN SELECT * FROM (VALUES
      ('sample_workflow',      'sample_workflow_business_path_check'),
      ('sample_path_revision', 'sample_path_revision_business_path_check')
    ) AS expected(table_name, constraint_name)
  LOOP
    SELECT count(*), min(c.conname)
      INTO v_count, v_name
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    JOIN pg_attribute a ON a.attrelid = t.oid AND a.attname = 'business_path' AND a.attnum > 0
    WHERE n.nspname = 'dflow'
      AND t.relname = r.table_name
      AND c.contype = 'c'
      AND c.conkey = ARRAY[a.attnum];

    IF v_count <> 1 THEN
      RAISE EXCEPTION
        'Issue #2136 expected exactly one business_path value CHECK on dflow.%, found %',
        r.table_name, v_count;
    END IF;
    IF v_name <> r.constraint_name THEN
      RAISE EXCEPTION
        'Issue #2136 expected the business_path value CHECK on dflow.% to be named %, found %',
        r.table_name, r.constraint_name, v_name;
    END IF;
  END LOOP;
END $$;

ALTER TABLE dflow.sample_workflow
  DROP CONSTRAINT sample_workflow_business_path_check;

ALTER TABLE dflow.sample_workflow
  ADD CONSTRAINT sample_workflow_business_path_check CHECK (business_path IN (
    'factory_ningbo_nyo','factory_ningbo_customer','factory_nyo','factory_customer',
    'china_warehouse_ningbo_nyo','china_warehouse_ningbo_customer',
    'nyo_factory','nyo_ningbo','ningbo_nyo','ningbo_customer'
  ));

ALTER TABLE dflow.sample_path_revision
  DROP CONSTRAINT sample_path_revision_business_path_check;

ALTER TABLE dflow.sample_path_revision
  ADD CONSTRAINT sample_path_revision_business_path_check CHECK (business_path IN (
    'factory_ningbo_nyo','factory_ningbo_customer','factory_nyo','factory_customer',
    'china_warehouse_ningbo_nyo','china_warehouse_ningbo_customer',
    'nyo_factory','nyo_ningbo','ningbo_nyo','ningbo_customer'
  ));

-- 2. Widen the nyo_factory_make_request arm of the flow/path matrix ----------
ALTER TABLE dflow.sample_workflow
  DROP CONSTRAINT IF EXISTS sample_workflow_valid_flow_path;

ALTER TABLE dflow.sample_workflow
  ADD CONSTRAINT sample_workflow_valid_flow_path CHECK (
    (workflow_type = 'nyo_purchased_factory_reference' AND business_path IN ('nyo_ningbo','nyo_factory')) OR
    (workflow_type = 'vendor_unsolicited_offer' AND business_path IN ('factory_ningbo_nyo','factory_nyo')) OR
    (workflow_type = 'nyo_factory_make_request' AND business_path IN (
      'factory_ningbo_nyo','factory_ningbo_customer','factory_nyo','factory_customer'
    )) OR
    (workflow_type = 'nyo_remote_china_inventory_request' AND business_path IN (
      'china_warehouse_ningbo_nyo','china_warehouse_ningbo_customer','ningbo_nyo','ningbo_customer'
    ))
  );

-- 3. The same widened matrix inside the path-revision trigger function -------
-- Body is unchanged from 20260818024441 except the nyo_factory_make_request arm.
CREATE OR REPLACE FUNCTION dflow.validate_sample_path_revision()
RETURNS trigger LANGUAGE plpgsql AS $fn$
DECLARE
  v_workflow_type text;
  v_expected_revision integer;
BEGIN
  SELECT workflow_type INTO v_workflow_type
  FROM dflow.sample_workflow
  WHERE sample_workflow_id = NEW.sample_workflow_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Sample workflow % does not exist', NEW.sample_workflow_id USING ERRCODE = '23503';
  END IF;
  IF NOT (
    (v_workflow_type = 'nyo_purchased_factory_reference' AND NEW.business_path IN ('nyo_ningbo','nyo_factory')) OR
    (v_workflow_type = 'vendor_unsolicited_offer' AND NEW.business_path IN ('factory_ningbo_nyo','factory_nyo')) OR
    (v_workflow_type = 'nyo_factory_make_request' AND NEW.business_path IN (
      'factory_ningbo_nyo','factory_ningbo_customer','factory_nyo','factory_customer'
    )) OR
    (v_workflow_type = 'nyo_remote_china_inventory_request' AND NEW.business_path IN (
      'china_warehouse_ningbo_nyo','china_warehouse_ningbo_customer','ningbo_nyo','ningbo_customer'
    ))
  ) THEN
    RAISE EXCEPTION 'Path % is invalid for workflow type %', NEW.business_path, v_workflow_type
      USING ERRCODE = '23514';
  END IF;
  SELECT COALESCE(max(revision),0) + 1 INTO v_expected_revision
  FROM dflow.sample_path_revision WHERE sample_workflow_id = NEW.sample_workflow_id;
  IF NEW.revision <> v_expected_revision THEN
    RAISE EXCEPTION 'Path revision must be %, received %', v_expected_revision, NEW.revision
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $fn$;

REVOKE ALL ON FUNCTION dflow.validate_sample_path_revision() FROM PUBLIC, anon, authenticated;

-- 4. Verification -----------------------------------------------------------
-- The value-list and flow/path CHECKs are proven by copying the LIVE catalog
-- definition onto a throwaway temp table and driving probe rows through it, so
-- the assertions exercise the deployed expression rather than the text above.
-- Positive and negative probes are both required.
DO $$
DECLARE
  v_def       text;
  v_pred      text;
  v_ok        boolean;
  v_table     text;
  v_tmp       text;
  v_tgenabled "char";
  v_tgtype    smallint;
  r           record;
BEGIN
  -- 4a. business_path value list on both tables.
  FOREACH v_table IN ARRAY ARRAY['sample_workflow','sample_path_revision'] LOOP
    SELECT pg_get_constraintdef(c.oid) INTO v_def
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    JOIN pg_attribute a ON a.attrelid = t.oid AND a.attname = 'business_path' AND a.attnum > 0
    WHERE n.nspname = 'dflow' AND t.relname = v_table
      AND c.contype = 'c' AND c.conkey = ARRAY[a.attnum];

    IF v_def IS NULL THEN
      RAISE EXCEPTION 'Issue #2136 verification: no business_path value CHECK found on dflow.%', v_table;
    END IF;

    v_tmp := '_v2136_values_' || v_table;
    EXECUTE format('CREATE TEMP TABLE %I (business_path text, CONSTRAINT %I %s) ON COMMIT DROP',
                   v_tmp, v_tmp || '_chk', v_def);

    FOR r IN SELECT * FROM (VALUES
        ('factory_customer', true),
        ('factory_nyo', true),
        ('factory_ningbo_nyo', true),
        ('factory_ningbo_customer', true),
        ('china_warehouse_ningbo_nyo', true),
        ('china_warehouse_ningbo_customer', true),
        ('nyo_factory', true),
        ('nyo_ningbo', true),
        ('ningbo_nyo', true),
        ('ningbo_customer', true),
        ('factory_ningbo', false),
        ('customer', false),
        ('factory_to_customer', false)
      ) AS probe(bp, expected)
    LOOP
      BEGIN
        EXECUTE format('INSERT INTO %I (business_path) VALUES ($1)', v_tmp) USING r.bp;
        v_ok := true;
      EXCEPTION WHEN check_violation THEN
        v_ok := false;
      END;
      IF v_ok <> r.expected THEN
        RAISE EXCEPTION
          'Issue #2136 verification: dflow.% business_path value CHECK accepted=% for %, expected accepted=%',
          v_table, v_ok, r.bp, r.expected;
      END IF;
    END LOOP;
  END LOOP;

  -- 4b. flow/path matrix on the workflow table.
  SELECT pg_get_constraintdef(c.oid) INTO v_def
  FROM pg_constraint c
  JOIN pg_class t ON t.oid = c.conrelid
  JOIN pg_namespace n ON n.oid = t.relnamespace
  WHERE n.nspname = 'dflow' AND t.relname = 'sample_workflow'
    AND c.conname = 'sample_workflow_valid_flow_path';

  IF v_def IS NULL THEN
    RAISE EXCEPTION 'Issue #2136 verification: sample_workflow_valid_flow_path is missing';
  END IF;

  EXECUTE format('CREATE TEMP TABLE _v2136_flow (workflow_type text, business_path text, CONSTRAINT _v2136_flow_chk %s) ON COMMIT DROP', v_def);

  FOR r IN SELECT * FROM (VALUES
      -- newly allowed by issue #2136
      ('nyo_factory_make_request','factory_nyo', true),
      ('nyo_factory_make_request','factory_customer', true),
      -- previously allowed, still allowed
      ('nyo_factory_make_request','factory_ningbo_nyo', true),
      ('nyo_factory_make_request','factory_ningbo_customer', true),
      ('nyo_purchased_factory_reference','nyo_ningbo', true),
      ('nyo_purchased_factory_reference','nyo_factory', true),
      ('vendor_unsolicited_offer','factory_ningbo_nyo', true),
      ('vendor_unsolicited_offer','factory_nyo', true),
      ('nyo_remote_china_inventory_request','china_warehouse_ningbo_nyo', true),
      ('nyo_remote_china_inventory_request','china_warehouse_ningbo_customer', true),
      ('nyo_remote_china_inventory_request','ningbo_nyo', true),
      ('nyo_remote_china_inventory_request','ningbo_customer', true),
      -- factory_customer belongs to the make request only
      ('nyo_purchased_factory_reference','factory_customer', false),
      ('vendor_unsolicited_offer','factory_customer', false),
      ('nyo_remote_china_inventory_request','factory_customer', false),
      -- the other arms are unchanged
      ('nyo_purchased_factory_reference','factory_ningbo_nyo', false),
      ('vendor_unsolicited_offer','nyo_ningbo', false),
      ('nyo_factory_make_request','ningbo_customer', false),
      ('nyo_factory_make_request','nyo_factory', false)
    ) AS probe(wt, bp, expected)
  LOOP
    BEGIN
      INSERT INTO _v2136_flow (workflow_type, business_path) VALUES (r.wt, r.bp);
      v_ok := true;
    EXCEPTION WHEN check_violation THEN
      v_ok := false;
    END;
    IF v_ok <> r.expected THEN
      RAISE EXCEPTION
        'Issue #2136 verification: sample_workflow_valid_flow_path accepted=% for (%, %), expected accepted=%',
        v_ok, r.wt, r.bp, r.expected;
    END IF;
  END LOOP;

  -- 4c. the SAME matrix inside the trigger function, proved BEHAVIOURALLY.
  -- Substring tests cannot do this: two unbound substrings both stay present if
  -- the make-request arm is left narrow and the four-token list is pasted onto a
  -- different arm, which is exactly the drift this file exists to prevent. So the
  -- acceptance predicate is lifted out of the LIVE function body and evaluated
  -- over the full probe matrix, every arm at once.
  SELECT p.prosrc INTO v_def
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'dflow' AND p.proname = 'validate_sample_path_revision';

  IF v_def IS NULL THEN
    RAISE EXCEPTION 'Issue #2136 verification: dflow.validate_sample_path_revision() is missing';
  END IF;

  v_pred := substring(v_def from 'IF NOT \(\s*(.*?)\s*\) THEN');
  IF v_pred IS NULL OR position('v_workflow_type' IN v_pred) = 0
                    OR position('NEW.business_path' IN v_pred) = 0 THEN
    RAISE EXCEPTION
      'Issue #2136 verification: could not lift the flow/path predicate out of dflow.validate_sample_path_revision()';
  END IF;

  v_pred := replace(replace(v_pred, 'v_workflow_type', '$1'), 'NEW.business_path', '$2');
  IF position('NEW.' IN v_pred) > 0 OR position('v_' IN v_pred) > 0 THEN
    RAISE EXCEPTION
      'Issue #2136 verification: the lifted predicate still references function state and cannot be probed';
  END IF;

  FOR r IN SELECT * FROM (VALUES
      -- newly allowed by issue #2136
      ('nyo_factory_make_request','factory_nyo', true),
      ('nyo_factory_make_request','factory_customer', true),
      -- previously allowed, still allowed
      ('nyo_factory_make_request','factory_ningbo_nyo', true),
      ('nyo_factory_make_request','factory_ningbo_customer', true),
      ('nyo_purchased_factory_reference','nyo_ningbo', true),
      ('nyo_purchased_factory_reference','nyo_factory', true),
      ('vendor_unsolicited_offer','factory_ningbo_nyo', true),
      ('vendor_unsolicited_offer','factory_nyo', true),
      ('nyo_remote_china_inventory_request','china_warehouse_ningbo_nyo', true),
      ('nyo_remote_china_inventory_request','china_warehouse_ningbo_customer', true),
      ('nyo_remote_china_inventory_request','ningbo_nyo', true),
      ('nyo_remote_china_inventory_request','ningbo_customer', true),
      -- factory_customer belongs to the make request only
      ('nyo_purchased_factory_reference','factory_customer', false),
      ('vendor_unsolicited_offer','factory_customer', false),
      ('nyo_remote_china_inventory_request','factory_customer', false),
      -- the other arms are unchanged
      ('nyo_purchased_factory_reference','factory_ningbo_nyo', false),
      ('vendor_unsolicited_offer','nyo_ningbo', false),
      ('nyo_factory_make_request','ningbo_customer', false),
      ('nyo_factory_make_request','nyo_factory', false),
      -- and an unknown workflow type is accepted by no arm
      ('not_a_workflow_type','factory_customer', false),
      ('not_a_workflow_type','factory_ningbo_nyo', false)
    ) AS probe(wt, bp, expected)
  LOOP
    EXECUTE 'SELECT COALESCE((' || v_pred || '), false)' INTO v_ok USING r.wt, r.bp;
    IF v_ok <> r.expected THEN
      RAISE EXCEPTION
        'Issue #2136 verification: dflow.validate_sample_path_revision() accepted=% for (%, %), expected accepted=%',
        v_ok, r.wt, r.bp, r.expected;
    END IF;
  END LOOP;

  -- 4d. the trigger is attached, ENABLED, and still BEFORE INSERT FOR EACH ROW.
  -- tgtype 7 = ROW (1) | BEFORE (2) | INSERT (4), the shape 20260818024441
  -- created. tgenabled 'O' = fires normally; a disabled trigger enforces nothing.
  SELECT g.tgenabled, g.tgtype INTO v_tgenabled, v_tgtype
  FROM pg_trigger g
  JOIN pg_class t ON t.oid = g.tgrelid
  JOIN pg_namespace n ON n.oid = t.relnamespace
  JOIN pg_proc p ON p.oid = g.tgfoid
  JOIN pg_namespace fn ON fn.oid = p.pronamespace
  WHERE n.nspname = 'dflow' AND t.relname = 'sample_path_revision'
    AND g.tgname = 'sample_path_revision_validate'
    AND fn.nspname = 'dflow' AND p.proname = 'validate_sample_path_revision'
    AND NOT g.tgisinternal;

  IF NOT FOUND THEN
    RAISE EXCEPTION
      'Issue #2136 verification: trigger sample_path_revision_validate is not attached to dflow.sample_path_revision';
  END IF;
  IF v_tgenabled <> 'O' THEN
    RAISE EXCEPTION
      'Issue #2136 verification: trigger sample_path_revision_validate is not enabled (tgenabled=%)', v_tgenabled;
  END IF;
  IF v_tgtype <> 7 THEN
    RAISE EXCEPTION
      'Issue #2136 verification: trigger sample_path_revision_validate is no longer BEFORE INSERT FOR EACH ROW (tgtype=%)', v_tgtype;
  END IF;
END $$;

COMMIT;
