-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `sample_shipment_item` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Sample shipment items
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm.sample_shipment_item (
    shipment_item_id_pk integer NOT NULL,
    sample_id_fk integer NOT NULL,
    box_id_fk integer,
    factory_group_id_fk integer,
    leg_type character varying(20),
    added_date timestamp with time zone,
    added_user character varying(255)
);

ALTER TABLE plm.sample_shipment_item ALTER COLUMN shipment_item_id_pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm.sample_shipment_item_shipment_item_id_pk_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample_shipment_item
    ADD CONSTRAINT sample_shipment_item_pkey PRIMARY KEY (shipment_item_id_pk);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample_shipment_item
    ADD CONSTRAINT sample_shipment_item_box_id_fk_fkey FOREIGN KEY (box_id_fk) REFERENCES plm.sample_box(box_id_pk) ON UPDATE CASCADE ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample_shipment_item
    ADD CONSTRAINT sample_shipment_item_sample_id_fk_fkey FOREIGN KEY (sample_id_fk) REFERENCES plm.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE plm.sample_shipment_item IS 'Sample shipment items';
