-- Additive: create DesignFlow table in shared schema core.
-- Mapped from DesignFlow `customers` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.1.
-- Purpose: PLM customer master; active retail accounts
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS core.customers (
    customers_id integer NOT NULL,
    customers_name character varying(255),
    customers_email character varying(255),
    customers_level character varying(255),
    customers_notes character varying(255),
    customers_passw character varying(255),
    customers_expire character varying(255),
    customers_status character varying(255),
    customers_auditlog character varying(255),
    customers_dilution character varying(255),
    customers_lastname character varying(255),
    customers_phonenum character varying(255),
    customers_subscription character varying(255),
    customers_logistic_load character varying(255),
    customers_subleveladmin character varying(255),
    customers_notificationsms character varying(255),
    customers_notificationemail character varying(255),
    customers_airbyte_emitted_at timestamp with time zone,
    customers_airbyte_customers_hashid text,
    customers_code character varying,
    customers_logo character varying(500)
);

ALTER TABLE core.customers ALTER COLUMN customers_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME core.customers_customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY core.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (customers_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE core.customers IS 'PLM customer master; active retail accounts';
