-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260305053146
-- Name: 20df79b0_f2da_4a4d_b320_d5e077dc0d8b
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
