-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260305184741
-- Name: 8de38e4f_d285_44a3_be72_3d2d820bc081
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
