-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260305213113
-- Name: 4109628d_4be6_4c79_9992_cf9af748d538
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
