-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `sample_factory_group` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Factory sample groups
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm.sample_factory_group (
    factory_group_id_pk integer NOT NULL,
    group_name character varying(255),
    factory_id_fk integer,
    origin character varying(20),
    direction character varying(10),
    status character varying(40),
    office_location character varying(20),
    notes text,
    "group_createdTime" character varying(255),
    "group_createdUser" character varying(255),
    "group_modTime" character varying(255),
    "group_modUser" character varying(255)
);

ALTER TABLE plm.sample_factory_group ALTER COLUMN factory_group_id_pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm.sample_factory_group_factory_group_id_pk_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample_factory_group
    ADD CONSTRAINT sample_factory_group_pkey PRIMARY KEY (factory_group_id_pk);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE plm.sample_factory_group IS 'Factory sample groups';
