-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260224211110
-- Name: 25e0360d_7626_41a5_860a_3daa108f4e95
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
