-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `sample_comments` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Sample comments
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm.sample_comments (
    id integer NOT NULL,
    comment text NOT NULL,
    sample_id_fk integer NOT NULL,
    user_id integer NOT NULL,
    parent_id integer,
    inserted_date timestamp with time zone NOT NULL
);

ALTER TABLE plm.sample_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm.sample_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample_comments
    ADD CONSTRAINT sample_comments_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample_comments
    ADD CONSTRAINT sample_comments_sample_id_fk_fkey FOREIGN KEY (sample_id_fk) REFERENCES plm.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample_comments
    ADD CONSTRAINT sample_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES app.users(id) ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE plm.sample_comments IS 'Sample comments';
