-- Additive: create DesignFlow table in shared schema app.
-- Mapped from DesignFlow `comments` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.2.
-- Purpose: Item comments; polymorphic link to PLM item
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS app.comments (
    id integer NOT NULL,
    comment character varying(50) NOT NULL,
    item_header_id integer NOT NULL,
    user_id integer NOT NULL,
    parent_id integer,
    inserted_date timestamp with time zone NOT NULL
);

ALTER TABLE app.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY app.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE app.comments IS 'Item comments; polymorphic link to PLM item';
