-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260406190053
-- Name: fd00878a_d617_4332_8639_15fab6ed00f5
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
