-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260322192514
-- Name: 03d87a3e_2a5a_4291_bc73_317511b315ff
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
