-- Durable, server-only Sample Tracking shipment email outbox.
CREATE TABLE IF NOT EXISTS dflow.sample_shipment_notice (
  sample_shipment_notice_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_shipment_id_fk bigint NOT NULL REFERENCES dflow.sample_shipment(sample_shipment_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  state text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','sending','sent','failed')),
  subject text NOT NULL CHECK (btrim(subject) <> ''),
  body_html text NOT NULL,
  body_text text,
  provider_idempotency_key uuid NOT NULL DEFAULT gen_random_uuid(),
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0 AND attempt_count <= 5),
  last_attempt_at timestamptz,
  next_attempt_at timestamptz,
  sent_at timestamptz,
  provider_message_id text,
  last_error text,
  created_by_user_id integer NOT NULL REFERENCES dflow.users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  created_by_user text NOT NULL CHECK (btrim(created_by_user) <> ''),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sample_shipment_notice_shipment_uniq UNIQUE (sample_shipment_id_fk),
  CONSTRAINT sample_shipment_notice_key_uniq UNIQUE (provider_idempotency_key),
  CONSTRAINT sample_shipment_notice_state_dates_ck CHECK (
    (state = 'sent') = (sent_at IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS dflow.sample_shipment_notice_recipient (
  sample_shipment_notice_recipient_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_shipment_notice_id_fk bigint NOT NULL REFERENCES dflow.sample_shipment_notice(sample_shipment_notice_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  user_id_fk integer NOT NULL REFERENCES dflow.users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  recipient_function text NOT NULL CHECK (recipient_function IN ('sales','design','both')),
  recipient_name_snapshot text NOT NULL CHECK (btrim(recipient_name_snapshot) <> ''),
  recipient_email_snapshot text NOT NULL CHECK (btrim(recipient_email_snapshot) <> ''),
  CONSTRAINT sample_shipment_notice_recipient_uniq UNIQUE (sample_shipment_notice_id_fk, user_id_fk)
);

CREATE OR REPLACE FUNCTION dflow.prevent_sample_shipment_notice_snapshot_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.sample_shipment_id_fk IS DISTINCT FROM OLD.sample_shipment_id_fk
     OR NEW.subject IS DISTINCT FROM OLD.subject OR NEW.body_html IS DISTINCT FROM OLD.body_html
     OR NEW.body_text IS DISTINCT FROM OLD.body_text OR NEW.provider_idempotency_key IS DISTINCT FROM OLD.provider_idempotency_key
     OR NEW.created_by_user_id IS DISTINCT FROM OLD.created_by_user_id OR NEW.created_by_user IS DISTINCT FROM OLD.created_by_user
  THEN RAISE EXCEPTION 'Sample shipment notice snapshots are immutable'; END IF;
  RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION dflow.prevent_sample_shipment_notice_recipient_snapshot_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.sample_shipment_notice_id_fk IS DISTINCT FROM OLD.sample_shipment_notice_id_fk
     OR NEW.user_id_fk IS DISTINCT FROM OLD.user_id_fk OR NEW.recipient_function IS DISTINCT FROM OLD.recipient_function
     OR NEW.recipient_name_snapshot IS DISTINCT FROM OLD.recipient_name_snapshot
     OR NEW.recipient_email_snapshot IS DISTINCT FROM OLD.recipient_email_snapshot
  THEN RAISE EXCEPTION 'Sample shipment notice recipient snapshots are immutable'; END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS sample_shipment_notice_snapshot_immutable ON dflow.sample_shipment_notice;
CREATE TRIGGER sample_shipment_notice_snapshot_immutable BEFORE UPDATE ON dflow.sample_shipment_notice
FOR EACH ROW EXECUTE FUNCTION dflow.prevent_sample_shipment_notice_snapshot_mutation();
DROP TRIGGER IF EXISTS sample_shipment_notice_recipient_snapshot_immutable ON dflow.sample_shipment_notice_recipient;
CREATE TRIGGER sample_shipment_notice_recipient_snapshot_immutable BEFORE UPDATE ON dflow.sample_shipment_notice_recipient
FOR EACH ROW EXECUTE FUNCTION dflow.prevent_sample_shipment_notice_recipient_snapshot_mutation();

CREATE OR REPLACE FUNCTION dflow.claim_sample_shipment_notice(p_notice_id bigint)
RETURNS TABLE (notice_id bigint, subject text, body_html text, provider_idempotency_key uuid, recipient_emails text[])
LANGUAGE plpgsql SECURITY DEFINER SET search_path = dflow, pg_catalog AS $$
DECLARE v_notice dflow.sample_shipment_notice;
BEGIN
  SELECT * INTO v_notice FROM dflow.sample_shipment_notice
  WHERE sample_shipment_notice_id = p_notice_id
    AND attempt_count < 5
    AND (state IN ('pending','failed') AND (next_attempt_at IS NULL OR next_attempt_at <= now())
         OR state = 'sending' AND last_attempt_at <= now() - interval '5 minutes')
  FOR UPDATE;
  IF NOT FOUND THEN RETURN; END IF;
  UPDATE dflow.sample_shipment_notice n
  SET state='sending', attempt_count=n.attempt_count+1, last_attempt_at=now(), next_attempt_at=NULL,
      last_error=NULL, updated_at=now()
  WHERE n.sample_shipment_notice_id = v_notice.sample_shipment_notice_id;
  RETURN QUERY SELECT v_notice.sample_shipment_notice_id, v_notice.subject, v_notice.body_html,
    v_notice.provider_idempotency_key,
    COALESCE((SELECT array_agg(r.recipient_email_snapshot ORDER BY r.sample_shipment_notice_recipient_id)
              FROM dflow.sample_shipment_notice_recipient r
              WHERE r.sample_shipment_notice_id_fk=v_notice.sample_shipment_notice_id), ARRAY[]::text[]);
END; $$;

REVOKE ALL ON dflow.sample_shipment_notice, dflow.sample_shipment_notice_recipient FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION dflow.claim_sample_shipment_notice(bigint) FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE ON dflow.sample_shipment_notice, dflow.sample_shipment_notice_recipient TO postgres;
GRANT EXECUTE ON FUNCTION dflow.claim_sample_shipment_notice(bigint) TO postgres;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='designflow') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE ON dflow.sample_shipment_notice, dflow.sample_shipment_notice_recipient TO designflow';
    EXECUTE 'GRANT EXECUTE ON FUNCTION dflow.claim_sample_shipment_notice(bigint) TO designflow';
  END IF;
END $$;

COMMENT ON TABLE dflow.sample_shipment_notice IS 'Immutable shipment email snapshot with bounded, provider-idempotent delivery state.';
COMMENT ON FUNCTION dflow.claim_sample_shipment_notice(bigint) IS 'Atomically claims one pending, failed, or stale sending notice for server-side delivery; max five attempts and five-minute spacing.';
