-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260610100545
-- Name: fuzzy_resolve_sku_files_used_and_fix_normalizer
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
