-- Immutable quantity authority, concurrency guard, idempotent posting API, closeouts.
BEGIN;

CREATE TABLE IF NOT EXISTS dflow.sample_movement (
  movement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_id_fk integer NOT NULL REFERENCES dflow.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
  quantity integer NOT NULL CHECK (quantity > 0),
  from_location_type text NOT NULL CHECK (from_location_type IN ('factory','office','customer','in_transit','terminal')),
  from_location_id text NOT NULL CHECK (btrim(from_location_id) <> ''),
  from_location_label text,
  to_location_type text NOT NULL CHECK (to_location_type IN ('factory','office','customer','in_transit','terminal')),
  to_location_id text NOT NULL CHECK (btrim(to_location_id) <> ''),
  to_location_label text,
  box_id_fk integer REFERENCES dflow.sample_box(box_id_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
  shipment_line_id bigint REFERENCES dflow.sample_shipment_line(shipment_line_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  lifecycle_action text NOT NULL CHECK (lifecycle_action IN ('create','pack','ship','receive','retain','repack','deliver','return','dispose','loss','correct','reopen','closeout')),
  prior_status text,
  resulting_status text,
  discrepancy_code text CHECK (discrepancy_code IS NULL OR discrepancy_code IN ('short','over','damaged','wrong_item','lost','other')),
  discrepancy_details text,
  actor_user text NOT NULL CHECK (btrim(actor_user) <> ''),
  actor_role text NOT NULL CHECK (btrim(actor_role) <> ''),
  actor_factory_id integer,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  idempotency_key text NOT NULL CHECK (btrim(idempotency_key) <> ''),
  request_hash text NOT NULL CHECK (btrim(request_hash) <> ''),
  reversal_of_movement_id bigint REFERENCES dflow.sample_movement(movement_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (sample_id_fk, idempotency_key),
  CHECK (from_location_type <> to_location_type OR from_location_id <> to_location_id),
  CHECK (reversal_of_movement_id IS NULL OR reversal_of_movement_id <> movement_id),
  CHECK ((discrepancy_code IS NULL AND discrepancy_details IS NULL) OR discrepancy_code IS NOT NULL),
  CHECK ((from_location_type <> 'in_transit' AND to_location_type <> 'in_transit') OR (box_id_fk IS NOT NULL AND shipment_line_id IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS sample_movement_sample_time_idx ON dflow.sample_movement(sample_id_fk, occurred_at, movement_id);
CREATE INDEX IF NOT EXISTS sample_movement_source_idx ON dflow.sample_movement(sample_id_fk, from_location_type, from_location_id);
CREATE INDEX IF NOT EXISTS sample_movement_destination_idx ON dflow.sample_movement(sample_id_fk, to_location_type, to_location_id);
CREATE INDEX IF NOT EXISTS sample_movement_box_idx ON dflow.sample_movement(box_id_fk, occurred_at) WHERE box_id_fk IS NOT NULL;

CREATE OR REPLACE FUNCTION dflow.sample_movement_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE v_balance bigint; v_original_sample integer;
BEGIN
  PERFORM pg_advisory_xact_lock(21450, NEW.sample_id_fk);
  IF NEW.reversal_of_movement_id IS NOT NULL THEN
    SELECT sample_id_fk INTO v_original_sample FROM dflow.sample_movement WHERE movement_id=NEW.reversal_of_movement_id;
    IF v_original_sample IS NULL OR v_original_sample <> NEW.sample_id_fk THEN
      RAISE EXCEPTION 'Correction must reference an existing movement for the same sample' USING ERRCODE='23514';
    END IF;
  END IF;
  IF NOT (NEW.from_location_type='terminal' AND NEW.from_location_id IN ('created','receipt_overage','reconciled_opening')) THEN
    SELECT COALESCE(sum(CASE WHEN to_location_type=NEW.from_location_type AND to_location_id=NEW.from_location_id THEN quantity ELSE 0 END),0)
         - COALESCE(sum(CASE WHEN from_location_type=NEW.from_location_type AND from_location_id=NEW.from_location_id THEN quantity ELSE 0 END),0)
      INTO v_balance FROM dflow.sample_movement WHERE sample_id_fk=NEW.sample_id_fk;
    IF v_balance < NEW.quantity THEN
      RAISE EXCEPTION 'Insufficient sample balance: available %, requested %', v_balance, NEW.quantity USING ERRCODE='23514';
    END IF;
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS sample_movement_guard_trigger ON dflow.sample_movement;
CREATE TRIGGER sample_movement_guard_trigger BEFORE INSERT ON dflow.sample_movement
FOR EACH ROW EXECUTE FUNCTION dflow.sample_movement_guard();

CREATE OR REPLACE FUNCTION dflow.reject_sample_movement_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Posted sample movements are immutable; use a compensating correction' USING ERRCODE='55000'; END $$;
DROP TRIGGER IF EXISTS sample_movement_immutable_trigger ON dflow.sample_movement;
CREATE TRIGGER sample_movement_immutable_trigger BEFORE UPDATE OR DELETE ON dflow.sample_movement
FOR EACH ROW EXECUTE FUNCTION dflow.reject_sample_movement_mutation();

CREATE OR REPLACE FUNCTION dflow.post_sample_movement(
  p_sample_id integer, p_quantity integer,
  p_from_type text, p_from_id text, p_to_type text, p_to_id text,
  p_action text, p_actor_user text, p_actor_role text,
  p_idempotency_key text, p_request_hash text,
  p_box_id integer DEFAULT NULL, p_shipment_line_id bigint DEFAULT NULL,
  p_actor_factory_id integer DEFAULT NULL, p_discrepancy_code text DEFAULT NULL,
  p_discrepancy_details text DEFAULT NULL, p_reversal_of bigint DEFAULT NULL,
  p_from_label text DEFAULT NULL, p_to_label text DEFAULT NULL
) RETURNS dflow.sample_movement LANGUAGE plpgsql SECURITY INVOKER AS $$
DECLARE v_existing dflow.sample_movement; v_result dflow.sample_movement;
BEGIN
  PERFORM pg_advisory_xact_lock(21450, p_sample_id);
  SELECT * INTO v_existing FROM dflow.sample_movement
   WHERE sample_id_fk=p_sample_id AND idempotency_key=p_idempotency_key;
  IF FOUND THEN
    IF v_existing.request_hash <> p_request_hash THEN
      RAISE EXCEPTION 'Idempotency key reused with different request' USING ERRCODE='23505';
    END IF;
    RETURN v_existing;
  END IF;
  INSERT INTO dflow.sample_movement(sample_id_fk,quantity,from_location_type,from_location_id,from_location_label,to_location_type,to_location_id,to_location_label,box_id_fk,shipment_line_id,lifecycle_action,actor_user,actor_role,actor_factory_id,idempotency_key,request_hash,discrepancy_code,discrepancy_details,reversal_of_movement_id)
  VALUES(p_sample_id,p_quantity,p_from_type,p_from_id,p_from_label,p_to_type,p_to_id,p_to_label,p_box_id,p_shipment_line_id,p_action,p_actor_user,p_actor_role,p_actor_factory_id,p_idempotency_key,p_request_hash,p_discrepancy_code,p_discrepancy_details,p_reversal_of)
  RETURNING * INTO v_result;
  RETURN v_result;
END $$;

CREATE TABLE IF NOT EXISTS dflow.sample_stop_closeout (
  closeout_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_id_fk integer NOT NULL REFERENCES dflow.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
  location_type text NOT NULL CHECK (location_type IN ('factory','office','customer')),
  location_id text NOT NULL CHECK (btrim(location_id) <> ''),
  movement_watermark bigint NOT NULL REFERENCES dflow.sample_movement(movement_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  revision integer NOT NULL DEFAULT 1 CHECK (revision > 0),
  state text NOT NULL DEFAULT 'closed' CHECK (state IN ('closed','reopened')),
  note text NOT NULL,
  closed_by_user text NOT NULL,
  closed_by_role text NOT NULL,
  closed_at timestamptz NOT NULL DEFAULT now(),
  reopens_closeout_id bigint REFERENCES dflow.sample_stop_closeout(closeout_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  UNIQUE(sample_id_fk, location_type, location_id, revision)
);
CREATE INDEX IF NOT EXISTS sample_stop_closeout_open_idx ON dflow.sample_stop_closeout(sample_id_fk,location_type,location_id,state);

REVOKE ALL ON dflow.sample_movement, dflow.sample_shipment_line, dflow.sample_stop_closeout FROM anon, authenticated;
REVOKE ALL ON FUNCTION dflow.post_sample_movement(integer,integer,text,text,text,text,text,text,text,text,text,integer,bigint,integer,text,text,bigint,text,text) FROM PUBLIC, anon, authenticated;

COMMIT;
