-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260225233835
-- Name: 8c5a8965_cedd_42fd_b1c9_3a982516ec79
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
