-- Additive: create missing Designflow landing-schema table used by
-- designflow-item-master product assignments / getItemInfo include.
-- Mapped to plm operational item master in
-- docs/designflow-master-data-migration/designflow-schema-segregation.md §4.3 #23.
--
-- Applied to production project qsllyeztdwjgirsysgai (schema dflow) 2026-07-10.

CREATE TABLE IF NOT EXISTS dflow."productUserAssignment" (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  item_id_fk integer NOT NULL,
  role character varying(50) NOT NULL,
  user_id_fk integer NOT NULL,
  created_by_fk integer NULL,
  created_date timestamp with time zone NOT NULL DEFAULT now(),
  updated_by_fk integer NULL,
  updated_date timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "productUserAssignment_pkey" PRIMARY KEY (id),
  CONSTRAINT "productUserAssignment_item_role_key" UNIQUE (item_id_fk, role),
  CONSTRAINT "productUserAssignment_item_id_fk_fkey"
    FOREIGN KEY (item_id_fk) REFERENCES dflow."itemHeader" (item_id_pk),
  CONSTRAINT "productUserAssignment_user_id_fk_fkey"
    FOREIGN KEY (user_id_fk) REFERENCES dflow.users (id)
);

CREATE INDEX IF NOT EXISTS "productUserAssignment_user_idx"
  ON dflow."productUserAssignment" (user_id_fk);

COMMENT ON TABLE dflow."productUserAssignment" IS
  'Item user role assignments (creative_designer, licensing_person, etc.). Matches designflow-item-master Sequelize model productUserAssignment.';
