-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260304155542
-- Name: 56e4ac3f_178a_4bdf_93f3_9ca012d699c9
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
