-- Additive: create DesignFlow table in shared schema plm.
-- Mapped from DesignFlow `sample_event` per
-- docs/designflow-master-data-migration/designflow-schema-segregation.md section 4.3.
-- Purpose: Sample status events
-- Branch: db-migration. Apply on preview first (shared-db-gatekeeper / AGENTS.md).
--
CREATE TABLE IF NOT EXISTS plm.sample_event (
    event_id_pk integer NOT NULL,
    sample_id_fk integer,
    box_id_fk integer,
    factory_group_id_fk integer,
    event_type character varying(30) NOT NULL,
    from_status character varying(40),
    to_status character varying(40),
    office_location character varying(20),
    event_user_id_fk integer,
    event_user character varying(255),
    event_time timestamp with time zone NOT NULL,
    notes text
);

ALTER TABLE plm.sample_event ALTER COLUMN event_id_pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME plm.sample_event_event_id_pk_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample_event
    ADD CONSTRAINT sample_event_pkey PRIMARY KEY (event_id_pk);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE ONLY plm.sample_event
    ADD CONSTRAINT sample_event_sample_id_fk_fkey FOREIGN KEY (sample_id_fk) REFERENCES plm.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_sample_event_sample_id_fk ON plm.sample_event USING btree (sample_id_fk);

COMMENT ON TABLE plm.sample_event IS 'Sample status events';
