-- Owner-authorized Release A catalog reconciliation.
-- Runs only after 20260814130000 and 20260814193402. It repairs the exact
-- partial-preview state and is a verified no-op reconciliation on a fresh target.
BEGIN;

DO $$
DECLARE v_present integer;
BEGIN
  IF (SELECT count(*) FROM supabase_migrations.schema_migrations
      WHERE version IN ('20260814130000','20260814193402')) <> 2 THEN
    RAISE EXCEPTION 'Release A reconciliation requires both approved predecessor ledger versions exactly once';
  END IF;
  IF to_regclass('dflow.sample_carrier') IS NULL
     OR to_regclass('dflow.sample_shipment') IS NULL THEN
    RAISE EXCEPTION 'Release A reconciliation requires carrier and shipment foundations';
  END IF;
  SELECT count(*) INTO v_present
  FROM (VALUES ('dflow.sample_creation_batch'),('dflow.sample_workflow'),('dflow.sample_path_revision')) AS expected(name)
  WHERE to_regclass(expected.name) IS NOT NULL;
  IF v_present NOT IN (0,3) THEN
    RAISE EXCEPTION 'Release A reconciliation refused mixed workflow catalog state: % of 3 tables exist', v_present;
  END IF;
  IF (SELECT count(*) FROM dflow.sample_carrier WHERE is_active) <> 4
     OR (SELECT count(*) FROM dflow.sample_carrier
         WHERE is_active AND carrier_code IN ('ups','fedex','dhl','usps')) <> 4 THEN
    RAISE EXCEPTION 'Release A reconciliation requires exactly the four approved active carrier seeds';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS dflow.sample_creation_batch (
  creation_batch_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mode text NOT NULL CHECK (mode IN ('single','group')),
  entry_method text NOT NULL CHECK (entry_method IN ('manual','inventory_selection','import_confirm')),
  idempotency_key text NOT NULL CHECK (btrim(idempotency_key) <> ''),
  request_hash text NOT NULL CHECK (btrim(request_hash) <> ''),
  created_by_user text NOT NULL CHECK (btrim(created_by_user) <> ''),
  created_by_role text NOT NULL CHECK (btrim(created_by_role) <> ''),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (created_by_user, idempotency_key)
);

CREATE TABLE IF NOT EXISTS dflow.sample_workflow (
  sample_workflow_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_id_fk integer NOT NULL UNIQUE REFERENCES dflow.sample(sample_id_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
  creation_batch_id bigint REFERENCES dflow.sample_creation_batch(creation_batch_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  workflow_type text NOT NULL CHECK (workflow_type IN (
    'nyo_purchased_factory_reference','vendor_unsolicited_offer',
    'nyo_factory_make_request','nyo_remote_china_inventory_request'
  )),
  business_path text NOT NULL CHECK (business_path IN (
    'factory_ningbo_nyo','factory_ningbo_customer','factory_nyo',
    'china_warehouse_ningbo_nyo','china_warehouse_ningbo_customer',
    'nyo_factory','nyo_ningbo','ningbo_nyo','ningbo_customer'
  )),
  workflow_state text NOT NULL DEFAULT 'draft' CHECK (workflow_state IN (
    'draft','confirmed','packed','shipped','received','delivered_reported',
    'delivery_exception','cancelled'
  )),
  contract_version text NOT NULL DEFAULT 'sample-tracking-release-a-v1'
    CHECK (contract_version = 'sample-tracking-release-a-v1'),
  created_by_user text NOT NULL CHECK (btrim(created_by_user) <> ''),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sample_workflow_valid_flow_path CHECK (
    (workflow_type = 'nyo_purchased_factory_reference' AND business_path IN ('nyo_ningbo','nyo_factory')) OR
    (workflow_type = 'vendor_unsolicited_offer' AND business_path IN ('factory_ningbo_nyo','factory_nyo')) OR
    (workflow_type = 'nyo_factory_make_request' AND business_path IN ('factory_ningbo_nyo','factory_ningbo_customer')) OR
    (workflow_type = 'nyo_remote_china_inventory_request' AND business_path IN (
      'china_warehouse_ningbo_nyo','china_warehouse_ningbo_customer','ningbo_nyo','ningbo_customer'
    ))
  )
);

CREATE INDEX IF NOT EXISTS sample_workflow_queue_idx
  ON dflow.sample_workflow (workflow_type, workflow_state, updated_at DESC);

CREATE TABLE IF NOT EXISTS dflow.sample_path_revision (
  sample_path_revision_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_workflow_id bigint NOT NULL REFERENCES dflow.sample_workflow(sample_workflow_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  revision integer NOT NULL CHECK (revision > 0),
  business_path text NOT NULL CHECK (business_path IN (
    'factory_ningbo_nyo','factory_ningbo_customer','factory_nyo',
    'china_warehouse_ningbo_nyo','china_warehouse_ningbo_customer',
    'nyo_factory','nyo_ningbo','ningbo_nyo','ningbo_customer'
  )),
  reason text NOT NULL CHECK (btrim(reason) <> ''),
  changed_by_user text NOT NULL CHECK (btrim(changed_by_user) <> ''),
  changed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (sample_workflow_id, revision)
);

CREATE OR REPLACE FUNCTION dflow.validate_sample_path_revision()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_workflow_type text;
  v_expected_revision integer;
BEGIN
  SELECT workflow_type INTO v_workflow_type
  FROM dflow.sample_workflow
  WHERE sample_workflow_id = NEW.sample_workflow_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Sample workflow % does not exist', NEW.sample_workflow_id USING ERRCODE = '23503';
  END IF;
  IF NOT (
    (v_workflow_type = 'nyo_purchased_factory_reference' AND NEW.business_path IN ('nyo_ningbo','nyo_factory')) OR
    (v_workflow_type = 'vendor_unsolicited_offer' AND NEW.business_path IN ('factory_ningbo_nyo','factory_nyo')) OR
    (v_workflow_type = 'nyo_factory_make_request' AND NEW.business_path IN ('factory_ningbo_nyo','factory_ningbo_customer')) OR
    (v_workflow_type = 'nyo_remote_china_inventory_request' AND NEW.business_path IN (
      'china_warehouse_ningbo_nyo','china_warehouse_ningbo_customer','ningbo_nyo','ningbo_customer'
    ))
  ) THEN
    RAISE EXCEPTION 'Path % is invalid for workflow type %', NEW.business_path, v_workflow_type
      USING ERRCODE = '23514';
  END IF;
  SELECT COALESCE(max(revision),0) + 1 INTO v_expected_revision
  FROM dflow.sample_path_revision WHERE sample_workflow_id = NEW.sample_workflow_id;
  IF NEW.revision <> v_expected_revision THEN
    RAISE EXCEPTION 'Path revision must be %, received %', v_expected_revision, NEW.revision
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS sample_path_revision_validate ON dflow.sample_path_revision;
CREATE TRIGGER sample_path_revision_validate
BEFORE INSERT ON dflow.sample_path_revision
FOR EACH ROW EXECUTE FUNCTION dflow.validate_sample_path_revision();

CREATE OR REPLACE FUNCTION dflow.require_sample_path_revision()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.business_path IS DISTINCT FROM OLD.business_path AND NOT EXISTS (
    SELECT 1 FROM dflow.sample_path_revision r
    WHERE r.sample_workflow_id = NEW.sample_workflow_id
      AND r.business_path = NEW.business_path
      AND r.revision = (SELECT max(r2.revision) FROM dflow.sample_path_revision r2
                        WHERE r2.sample_workflow_id = NEW.sample_workflow_id)
  ) THEN
    RAISE EXCEPTION 'Insert the append-only path revision before changing the workflow path'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS sample_workflow_path_revision_required ON dflow.sample_workflow;
CREATE TRIGGER sample_workflow_path_revision_required
BEFORE UPDATE OF business_path ON dflow.sample_workflow
FOR EACH ROW EXECUTE FUNCTION dflow.require_sample_path_revision();

CREATE OR REPLACE FUNCTION dflow.apply_sample_path_revision()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  UPDATE dflow.sample_workflow
  SET business_path = NEW.business_path, updated_at = NEW.changed_at
  WHERE sample_workflow_id = NEW.sample_workflow_id;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS sample_path_revision_apply ON dflow.sample_path_revision;
CREATE TRIGGER sample_path_revision_apply
AFTER INSERT ON dflow.sample_path_revision
FOR EACH ROW EXECUTE FUNCTION dflow.apply_sample_path_revision();

CREATE OR REPLACE FUNCTION dflow.reject_sample_path_revision_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Sample path revisions are append-only' USING ERRCODE = '55000';
END $$;

DROP TRIGGER IF EXISTS sample_path_revision_immutable ON dflow.sample_path_revision;
CREATE TRIGGER sample_path_revision_immutable
BEFORE UPDATE OR DELETE ON dflow.sample_path_revision
FOR EACH ROW EXECUTE FUNCTION dflow.reject_sample_path_revision_mutation();

CREATE OR REPLACE FUNCTION dflow.validate_sample_shipment_line_header()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_header dflow.sample_shipment;
BEGIN
  IF NEW.sample_shipment_id IS NULL THEN RETURN NEW; END IF;
  SELECT * INTO v_header FROM dflow.sample_shipment WHERE sample_shipment_id=NEW.sample_shipment_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Shipment header % does not exist',NEW.sample_shipment_id USING ERRCODE='23503';
  END IF;
  IF NEW.origin_location_type IS DISTINCT FROM v_header.origin_location_type
     OR NEW.origin_location_id IS DISTINCT FROM v_header.origin_location_id
     OR NEW.destination_location_type IS DISTINCT FROM v_header.destination_location_type
     OR NEW.destination_location_id IS DISTINCT FROM v_header.destination_location_id THEN
    RAISE EXCEPTION 'Shipment line route must match shipment header %',NEW.sample_shipment_id
      USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS sample_shipment_line_header_route ON dflow.sample_shipment_line;
CREATE TRIGGER sample_shipment_line_header_route
BEFORE INSERT OR UPDATE OF sample_shipment_id,origin_location_type,origin_location_id,
  destination_location_type,destination_location_id ON dflow.sample_shipment_line
FOR EACH ROW EXECUTE FUNCTION dflow.validate_sample_shipment_line_header();
CREATE OR REPLACE VIEW dflow.sample_inventory AS
SELECT
  b.sample_id_fk,
  b.location_type,
  CASE
    WHEN b.location_type = 'terminal' AND b.location_id = 'nyc_office_inventory' THEN 'office'
    WHEN b.location_type = 'terminal' AND b.location_id = 'ningbo_office_inventory' THEN 'office'
    ELSE b.location_type
  END AS product_location_type,
  CASE
    WHEN b.location_id = 'nyc_office_inventory' THEN 'nyc'
    WHEN b.location_id = 'ningbo_office_inventory' THEN 'ningbo'
    ELSE b.location_id
  END AS product_location_id,
  b.quantity,
  max(m.occurred_at) AS available_since,
  EXISTS (
    SELECT 1 FROM dflow.sample_shipment_item si
    WHERE si.sample_id_fk = b.sample_id_fk AND si.box_id_fk IS NOT NULL
  ) AS is_boxed,
  (b.location_type = 'in_transit') AS is_in_transit,
  (b.quantity > 0 AND b.location_type <> 'in_transit') AS is_eligible,
  CASE WHEN b.quantity <= 0 THEN 'no_balance'
       WHEN b.location_type = 'in_transit' THEN 'in_transit'
       ELSE NULL END AS ineligibility_reason
FROM dflow.sample_balance_by_location b
LEFT JOIN dflow.sample_movement m
  ON m.sample_id_fk = b.sample_id_fk
 AND ((m.to_location_type = b.location_type AND m.to_location_id = b.location_id)
   OR (m.from_location_type = b.location_type AND m.from_location_id = b.location_id))
WHERE b.quantity > 0
GROUP BY b.sample_id_fk,b.location_type,b.location_id,b.quantity;

CREATE INDEX IF NOT EXISTS sample_movement_inventory_idx
  ON dflow.sample_movement (to_location_type, to_location_id, occurred_at DESC, sample_id_fk);

COMMENT ON TABLE dflow.sample_creation_batch IS 'Neutral atomic guided-create batch for single, group, inventory-selection, or confirmed import creation.';
COMMENT ON TABLE dflow.sample_workflow IS 'Stable Release A workflow and business-path identity. Legacy samples have no row and remain unclassified.';
COMMENT ON TABLE dflow.sample_path_revision IS 'Append-only audit of path changes; never rewrite prior revisions.';
COMMENT ON VIEW dflow.sample_inventory IS 'Server inventory read model derived from movement balances, including parked office leftovers.';

REVOKE ALL ON dflow.sample_creation_batch,dflow.sample_workflow,dflow.sample_path_revision,
  dflow.sample_inventory FROM anon,authenticated;
REVOKE ALL ON FUNCTION dflow.reject_sample_path_revision_mutation(),
  dflow.validate_sample_path_revision(),dflow.require_sample_path_revision(),
  dflow.apply_sample_path_revision(),dflow.validate_sample_shipment_line_header()
  FROM PUBLIC,anon,authenticated;

DO $$
DECLARE v_missing text[];
BEGIN
  SELECT array_agg(name ORDER BY name) INTO v_missing
  FROM (VALUES
    ('dflow.sample_creation_batch'),('dflow.sample_workflow'),
    ('dflow.sample_path_revision'),('dflow.sample_inventory')
  ) AS expected(name)
  WHERE to_regclass(expected.name) IS NULL;
  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'Release A reconciliation postcondition missing relations: %', v_missing;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='dflow' AND p.proname='validate_sample_path_revision')
     OR NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='dflow' AND p.proname='require_sample_path_revision')
     OR NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='dflow' AND p.proname='apply_sample_path_revision')
     OR NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='dflow' AND p.proname='reject_sample_path_revision_mutation')
     OR NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='dflow' AND p.proname='validate_sample_shipment_line_header') THEN
    RAISE EXCEPTION 'Release A reconciliation postcondition missing functions';
  END IF;
  IF has_table_privilege('anon','dflow.sample_creation_batch','SELECT')
     OR has_table_privilege('authenticated','dflow.sample_workflow','SELECT')
     OR has_table_privilege('authenticated','dflow.sample_path_revision','SELECT')
     OR has_table_privilege('authenticated','dflow.sample_inventory','SELECT') THEN
    RAISE EXCEPTION 'Release A reconciliation postcondition found forbidden direct table privilege';
  END IF;
END $$;

COMMIT;

