-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260224200816
-- Name: 4c2c4b03_dd19_47f8_8b24_154bd930b31d
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
