-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260223124754
-- Name: ec8ec7b5_b242_4c3d_86f1_c231feb8864b
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
