-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260310201321
-- Name: b1b89ddc_7566_474e_b333_e006df61ab06
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
