-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260308165531
-- Name: d54069e8_da83_46d6_a44b_e2e9249bc9ea
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
