-- Production migration-history marker for pre-shared-db PopDAM migration.
--
-- Version: 20260306012513
-- Name: 5a8f1b82_0aa4_461d_ad6d_de8cf8844a66
--
-- This migration was already applied to the production Supabase project before
-- the shared-db repository became the canonical migration workspace. The SQL
-- body intentionally remains empty here. The purpose of this file is to let
-- Supabase CLI compare the local migration ledger with the production ledger
-- without trying to replay legacy PopDAM migrations from this repository.
