import test from 'node:test'
import assert from 'node:assert/strict'
import { buildFiveOutcomeAcceptanceReport } from './acceptance-report.mjs'

const states=['entered','dispatched','implementation_complete','review_ready','preview_verified','merged','production_authorized','production_applied','live_verified']
function outcome(sequence,{service=sequence%2?'urgent-application':'standard-application',step=5}={}){const issue=400+sequence,start=Date.parse('2026-09-12T12:00:00Z')+sequence*3600000;return{sequence,issue,work_type:'structural',service_class:service,unchanged_poll_count:0,manual_reconstruction_count:0,events:states.map((event_type,index)=>({event_type,work_issue:issue,result:'succeeded',timestamp:new Date(start+index*step*60000).toISOString()})),waits:[{kind:'owner',started_at:new Date(start).toISOString(),ended_at:new Date(start+60000).toISOString()},{kind:'external',started_at:new Date(start+60000).toISOString(),ended_at:new Date(start+180000).toISOString()}],exceptions:sequence===3?['provider outage excluded from active time']:[]}}
const input=()=>({outcomes:[1,2,3,4,5].map((n)=>outcome(n)),baseline:{n:9,median_request_to_live_minutes:100},refusal_evidence:[{result:'refused',evidence:'artifact:refusal-1'}]})

test('five consecutive structural live outcomes report every phase, waits, raw n, exceptions and improvement',()=>{const report=buildFiveOutcomeAcceptanceReport(input());assert.equal(report.status,'accepted');assert.equal(report.sample.n,5);assert.equal(report.baseline.n,9);assert.equal(report.current.n,5);assert.equal(report.current.median_request_to_live_minutes,40);assert.equal(report.current.improvement_percent,60);assert.deepEqual(Object.keys(report.outcomes[0].phase_minutes),['request_to_dispatch','dispatch_to_implementation','implementation_to_review','review_ci_wait','merge','production_decision_wait','production_apply','live_verification']);assert.deepEqual(report.outcomes[0].wait_minutes,{owner:1,external:2});assert.deepEqual(report.exceptions,[{issue:403,detail:'provider outage excluded from active time'}])})

test('acceptance refuses non-five, nonconsecutive, nonstructural and incomplete lifecycle samples',()=>{for(const mutate of [x=>x.outcomes.pop(),x=>x.outcomes[2].sequence=9,x=>x.outcomes[1].work_type='repo-maintenance',x=>x.outcomes[0].events.pop()]){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/five consecutive|sequence|structural|incomplete/)}})

test('duplicated, reordered, foreign-issue and refused lifecycle events cannot manufacture completion',()=>{for(const mutate of [x=>x.outcomes[0].events.splice(2,0,x.outcomes[0].events[1]),x=>x.outcomes[0].events.reverse(),x=>x.outcomes[0].events[4].work_issue=999,x=>x.outcomes[0].events[4].result='refused']){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/duplicated, incomplete, or out of order/)}})

test('urgent and standard dispatch targets are enforced independently',()=>{let value=input();value.outcomes[0]=outcome(1,{service:'urgent-application',step:11});assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/10-minute/);value=input();value.outcomes[1]=outcome(2,{service:'standard-application',step:61});assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/60-minute/)})

test('unchanged polling, manual reconstruction, absent refusal proof and weak median all fail closed',()=>{for(const mutate of [x=>x.outcomes[0].unchanged_poll_count=1,x=>x.outcomes[0].manual_reconstruction_count=1,x=>x.refusal_evidence=[],x=>x.baseline.median_request_to_live_minutes=79]){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/polling|reconstruction|refusal|below 50/)}})

test('owner and external waits remain separate and malformed waits refuse',()=>{const value=input();value.outcomes[0].waits[0].kind='internal';assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/unknown wait kind/);const reversed=input();reversed.outcomes[0].waits[0].ended_at='2026-01-01T00:00:00Z';assert.throws(()=>buildFiveOutcomeAcceptanceReport(reversed),/chronological/)})
