import test from 'node:test'
import assert from 'node:assert/strict'
import { buildFiveOutcomeAcceptanceReport as buildReport, main } from './acceptance-report.mjs'
import { canonicalJson, sha256 } from './evidence-bundle.mjs'
import { mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'

const states=['entered','dispatched','implementation_complete','review_ready','preview_verified','merged','production_authorized','production_applied','live_verified']
const head='a'.repeat(40),digest='sha256:'+'b'.repeat(64)
const bind=(value,keys)=>`sha256:${sha256(canonicalJson(Object.fromEntries(keys.map((key)=>[key,value[key]]))))}`
function outcome(sequence,{service=sequence%2?'urgent-application':'standard-application',step=5}={}){const issue=400+sequence,start=Date.parse('2026-09-12T12:00:00Z')+sequence*3600000,eventId=String(sequence).padStart(64,'0'),evidence=`artifact:live-${issue}`,identity={work_issue:issue,event_id:eventId,head_sha:head,evidence};identity.evidence_digest=bind(identity,['work_issue','event_id','head_sha','evidence']);return{sequence,issue,work_type:'structural',service_class:service,unchanged_poll_count:0,manual_reconstruction_count:0,lifecycle_identity:identity,events:states.map((event_type,index)=>({event_id:event_type==='live_verified'?eventId:String(index+10).padStart(64,'0'),event_type,work_issue:issue,head_sha:head,result:'succeeded',evidence_urls:event_type==='live_verified'?[evidence]:[],timestamp:new Date(start+index*step*60000).toISOString()})),waits:[{kind:'owner',started_at:new Date(start).toISOString(),ended_at:new Date(start+60000).toISOString()},{kind:'external',started_at:new Date(start+60000).toISOString(),ended_at:new Date(start+180000).toISOString()}],exceptions:sequence===3?['provider outage excluded from active time']:[]}}
function cohort(issues){const content={schema_version:1,ordered_work_issues:issues},value={schema_version:1,source_evidence:'artifact:cohort-ledger',artifact_id:91,artifact_digest:`sha256:${sha256(canonicalJson(content))}`,ledger_head_sha:head,ordered_work_issues:issues};return{...value,cohort_digest:`sha256:${sha256(canonicalJson(value))}`}}
const input=()=>{const outcomes=[1,2,3,4,5].map((n)=>outcome(n)),refusal={result:'refused',work_issue:499,head_sha:head,event_id:'f'.repeat(64),evidence:'artifact:refusal-1'};refusal.evidence_digest=bind(refusal,['result','work_issue','event_id','head_sha','evidence']);const refusal_evidence=[refusal],content={entries:refusal_evidence},refusal_ledger={source_evidence:'artifact:refusal-ledger',artifact_id:92,artifact_digest:`sha256:${sha256(canonicalJson(content))}`,ledger_head_sha:head,count:1,set_digest:`sha256:${sha256(canonicalJson(refusal_evidence))}`};return{outcomes,cohort:cohort(outcomes.map((x)=>x.issue)),baseline:{n:5,samples:[90,95,100,105,110],median_request_to_live_minutes:100},refusal_evidence,refusal_ledger}}
const authoritative=(value)=>({readCohortArtifact:()=>({source_evidence:value.cohort.source_evidence,artifact_id:value.cohort.artifact_id,ledger_head_sha:value.cohort.ledger_head_sha,content:{schema_version:value.cohort.schema_version,ordered_work_issues:structuredClone(value.cohort.ordered_work_issues)}}),readRefusalLedger:()=>({source_evidence:value.refusal_ledger.source_evidence,artifact_id:value.refusal_ledger.artifact_id,ledger_head_sha:value.refusal_ledger.ledger_head_sha,content:{entries:structuredClone(value.refusal_evidence)}})})
const buildFiveOutcomeAcceptanceReport=(value)=>buildReport(value,authoritative(value))

test('five consecutive structural live outcomes report every phase, waits, raw n, exceptions and improvement',()=>{const report=buildFiveOutcomeAcceptanceReport(input());assert.equal(report.status,'accepted');assert.equal(report.sample.n,5);assert.equal(report.baseline.n,5);assert.equal(report.current.n,5);assert.equal(report.current.median_request_to_live_minutes,40);assert.equal(report.current.improvement_percent,60);assert.deepEqual(Object.keys(report.outcomes[0].phase_minutes),['request_to_dispatch','dispatch_to_implementation','implementation_to_review','review_ci_wait','merge','production_decision_wait','production_apply','live_verification']);assert.deepEqual(report.outcomes[0].wait_minutes,{owner:1,external:2});assert.deepEqual(report.exceptions,[{issue:403,detail:'provider outage excluded from active time'}])})

test('acceptance refuses non-five, fabricated order, nonstructural and incomplete lifecycle samples',()=>{for(const mutate of [x=>x.outcomes.pop(),x=>x.outcomes.reverse(),x=>x.outcomes[1].work_type='repo-maintenance',x=>x.outcomes[0].events.pop()]){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/five consecutive|authoritative consecutive|structural|incomplete/)}})

test('duplicated, reordered, foreign-issue and failed lifecycle events cannot manufacture completion',()=>{for(const mutate of [x=>x.outcomes[0].events.splice(2,0,x.outcomes[0].events[1]),x=>x.outcomes[0].events.reverse(),x=>x.outcomes[0].events[4].work_issue=999,x=>x.outcomes[0].events.at(-1).result='refused']){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/duplicated, incomplete, failed, foreign, or out of order/)}})

test('urgent and standard dispatch targets are enforced independently',()=>{let value=input();value.outcomes[0]=outcome(1,{service:'urgent-application',step:11});assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/10-minute/);value=input();value.outcomes[1]=outcome(2,{service:'standard-application',step:61});assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/60-minute/)})

test('unchanged polling, manual reconstruction, absent refusal proof and weak median all fail closed',()=>{for(const mutate of [x=>x.outcomes[0].unchanged_poll_count=1,x=>x.outcomes[0].manual_reconstruction_count=1,x=>x.refusal_evidence=[],x=>{x.baseline.samples=[75,77,79,81,83];x.baseline.median_request_to_live_minutes=79}]){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/polling|reconstruction|refusal|below 50/)}})

test('owner and external waits remain separate and malformed waits refuse',()=>{const value=input();value.outcomes[0].waits[0].kind='internal';assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/unknown wait kind/);const reversed=input();reversed.outcomes[0].waits[0].ended_at='2026-01-01T00:00:00Z';assert.throws(()=>buildFiveOutcomeAcceptanceReport(reversed),/chronological/)})

test('five outcomes must have unique authoritative issue identities',()=>{const value=input();value.cohort.ordered_work_issues[4]=value.cohort.ordered_work_issues[0];assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/five unique/)})

test('live_verified must be exact succeeded and identity-bound',()=>{for(const mutate of [x=>x.outcomes[0].events.at(-1).event_id='e'.repeat(64),x=>x.outcomes[0].lifecycle_identity.work_issue=999,x=>x.outcomes[0].events.at(-1).evidence_urls=[]]){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/identity/)}})

test('refusal proof cannot be filtered, unbound, or attached to another head',()=>{for(const mutate of [x=>x.refusal_evidence=[],x=>delete x.refusal_evidence[0].work_issue,x=>x.refusal_evidence[0].head_sha='c'.repeat(39),x=>x.refusal_evidence[0].evidence_digest='fabricated']){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/refusal/)}})

test('cohort digest detects a fabricated caller sequence',()=>{const value=input();value.cohort.ordered_work_issues.reverse();assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/cohort digest/)})

test('baseline n and median are recomputed from raw samples',()=>{for(const mutate of [x=>x.baseline.n=99,x=>x.baseline.median_request_to_live_minutes=200,x=>x.baseline.samples=[200]]){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/baseline n|baseline median/)}})

test('a wholly fabricated recomputed cohort cannot replace authoritative readback',()=>{const value=input(),io=authoritative(value);value.cohort.ordered_work_issues.reverse();const identity=Object.fromEntries(Object.entries(value.cohort).filter(([key])=>key!=='cohort_digest'));value.cohort.cohort_digest=`sha256:${sha256(canonicalJson(identity))}`;value.outcomes.reverse();assert.throws(()=>buildReport(value,io),/artifact readback|canonical content/)})

test('a nonempty filtered refusal subset cannot pass the authoritative set',()=>{const value=input(),extra={...value.refusal_evidence[0],work_issue:500,event_id:'e'.repeat(64),evidence:'artifact:refusal-2'};extra.evidence_digest=bind(extra,['result','work_issue','event_id','head_sha','evidence']);const authoritativeEntries=[...value.refusal_evidence,extra],io={...authoritative(value),readRefusalLedger:()=>({source_evidence:value.refusal_ledger.source_evidence,artifact_id:value.refusal_ledger.artifact_id,ledger_head_sha:value.refusal_ledger.ledger_head_sha,content:{entries:authoritativeEntries}})};value.refusal_ledger.count=2;value.refusal_ledger.set_digest=`sha256:${sha256(canonicalJson(authoritativeEntries))}`;value.refusal_ledger.artifact_digest=`sha256:${sha256(canonicalJson({entries:authoritativeEntries}))}`;assert.throws(()=>buildReport(value,io),/filtered or changed subset/)})

function cliFixture(){const root=mkdtempSync(path.join(tmpdir(),'acceptance-authority-')),value=input();for(const [claim,content] of [[value.cohort,{schema_version:1,ordered_work_issues:value.cohort.ordered_work_issues}],[value.refusal_ledger,{entries:value.refusal_evidence}]]){const key=sha256(canonicalJson({source_evidence:claim.source_evidence,artifact_id:claim.artifact_id}));writeFileSync(path.join(root,`artifact-${key}.json`),JSON.stringify({source_evidence:claim.source_evidence,artifact_id:claim.artifact_id,ledger_head_sha:claim.ledger_head_sha,content}))}const report=path.join(root,'report.json');writeFileSync(report,JSON.stringify(value));return{root,report,value}}

function captureMain(argv,options){const logs=[],errors=[],oldLog=console.log,oldError=console.error;console.log=(x)=>logs.push(x);console.error=(x)=>errors.push(x);try{return{code:main(argv,options),logs,errors}}finally{console.log=oldLog;console.error=oldError}}

test('live CLI resolves both claimed artifacts only through its trusted root',()=>{const fixture=cliFixture(),result=captureMain(['--input',fixture.report],{artifactRoot:fixture.root});assert.equal(result.code,0);assert.equal(result.errors.length,0);assert.match(result.logs[0],/"accepted"/)})

test('live CLI rejects path substitution and a fabricated report cohort refusal trio',()=>{const fixture=cliFixture(),outside=mkdtempSync(path.join(tmpdir(),'acceptance-fabricated-'));writeFileSync(path.join(outside,'cohort.json'),'{}');writeFileSync(path.join(outside,'refusals.json'),'{}');const substituted=captureMain(['--input',fixture.report,'--cohort-artifact',path.join(outside,'cohort.json'),'--refusal-ledger',path.join(outside,'refusals.json')],{artifactRoot:fixture.root});assert.equal(substituted.code,2);assert.match(substituted.errors[0],/trusted artifact store/);const fabricated=JSON.parse(JSON.stringify(fixture.value));fabricated.cohort.source_evidence='artifact:fabricated-cohort';fabricated.refusal_ledger.source_evidence='artifact:fabricated-refusals';const cohortIdentity=Object.fromEntries(Object.entries(fabricated.cohort).filter(([key])=>key!=='cohort_digest'));fabricated.cohort.cohort_digest=`sha256:${sha256(canonicalJson(cohortIdentity))}`;const report=path.join(outside,'report.json');writeFileSync(report,JSON.stringify(fabricated));const trio=captureMain(['--input',report],{artifactRoot:outside});assert.equal(trio.code,2);assert.match(trio.errors[0],/unreadable/)})

test('authoritative readers reject returned source id head and canonical-content substitutions',()=>{for(const mutate of [x=>x.source_evidence='artifact:other',x=>x.artifact_id=999,x=>x.ledger_head_sha='c'.repeat(40),x=>x.content.ordered_work_issues.reverse()]){const value=input(),io=authoritative(value),original=io.readCohortArtifact;io.readCohortArtifact=(source,id)=>{const row=original(source,id);mutate(row);return row};assert.throws(()=>buildReport(value,io),/requested source, id, or head|canonical content|claimed exact identity/)}})
