import test from 'node:test'
import assert from 'node:assert/strict'
import { buildFiveOutcomeAcceptanceReport } from './acceptance-report.mjs'
import { canonicalJson, sha256 } from './evidence-bundle.mjs'

const states=['entered','dispatched','implementation_complete','review_ready','preview_verified','merged','production_authorized','production_applied','live_verified']
const head='a'.repeat(40),digest='sha256:'+'b'.repeat(64)
const bind=(value,keys)=>`sha256:${sha256(canonicalJson(Object.fromEntries(keys.map((key)=>[key,value[key]]))))}`
function outcome(sequence,{service=sequence%2?'urgent-application':'standard-application',step=5}={}){const issue=400+sequence,start=Date.parse('2026-09-12T12:00:00Z')+sequence*3600000,eventId=String(sequence).padStart(64,'0'),evidence=`artifact:live-${issue}`,identity={work_issue:issue,event_id:eventId,head_sha:head,evidence};identity.evidence_digest=bind(identity,['work_issue','event_id','head_sha','evidence']);return{sequence,issue,work_type:'structural',service_class:service,unchanged_poll_count:0,manual_reconstruction_count:0,lifecycle_identity:identity,events:states.map((event_type,index)=>({event_id:event_type==='live_verified'?eventId:String(index+10).padStart(64,'0'),event_type,work_issue:issue,head_sha:head,result:'succeeded',evidence_urls:event_type==='live_verified'?[evidence]:[],timestamp:new Date(start+index*step*60000).toISOString()})),waits:[{kind:'owner',started_at:new Date(start).toISOString(),ended_at:new Date(start+60000).toISOString()},{kind:'external',started_at:new Date(start+60000).toISOString(),ended_at:new Date(start+180000).toISOString()}],exceptions:sequence===3?['provider outage excluded from active time']:[]}}
function cohort(issues){const value={schema_version:1,source_evidence:'artifact:cohort-ledger',artifact_id:91,artifact_digest:digest,ledger_head_sha:head,ordered_work_issues:issues};return{...value,cohort_digest:`sha256:${sha256(canonicalJson(value))}`}}
const input=()=>{const outcomes=[1,2,3,4,5].map((n)=>outcome(n)),refusal={result:'refused',work_issue:499,head_sha:head,event_id:'f'.repeat(64),evidence:'artifact:refusal-1'};refusal.evidence_digest=bind(refusal,['result','work_issue','event_id','head_sha','evidence']);return{outcomes,cohort:cohort(outcomes.map((x)=>x.issue)),baseline:{n:5,samples:[90,95,100,105,110],median_request_to_live_minutes:100},refusal_evidence:[refusal]}}

test('five consecutive structural live outcomes report every phase, waits, raw n, exceptions and improvement',()=>{const report=buildFiveOutcomeAcceptanceReport(input());assert.equal(report.status,'accepted');assert.equal(report.sample.n,5);assert.equal(report.baseline.n,5);assert.equal(report.current.n,5);assert.equal(report.current.median_request_to_live_minutes,40);assert.equal(report.current.improvement_percent,60);assert.deepEqual(Object.keys(report.outcomes[0].phase_minutes),['request_to_dispatch','dispatch_to_implementation','implementation_to_review','review_ci_wait','merge','production_decision_wait','production_apply','live_verification']);assert.deepEqual(report.outcomes[0].wait_minutes,{owner:1,external:2});assert.deepEqual(report.exceptions,[{issue:403,detail:'provider outage excluded from active time'}])})

test('acceptance refuses non-five, fabricated order, nonstructural and incomplete lifecycle samples',()=>{for(const mutate of [x=>x.outcomes.pop(),x=>x.outcomes.reverse(),x=>x.outcomes[1].work_type='repo-maintenance',x=>x.outcomes[0].events.pop()]){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/five consecutive|authoritative consecutive|structural|incomplete/)}})

test('duplicated, reordered, foreign-issue and failed lifecycle events cannot manufacture completion',()=>{for(const mutate of [x=>x.outcomes[0].events.splice(2,0,x.outcomes[0].events[1]),x=>x.outcomes[0].events.reverse(),x=>x.outcomes[0].events[4].work_issue=999,x=>x.outcomes[0].events.at(-1).result='refused']){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/duplicated, incomplete, failed, foreign, or out of order/)}})

test('urgent and standard dispatch targets are enforced independently',()=>{let value=input();value.outcomes[0]=outcome(1,{service:'urgent-application',step:11});assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/10-minute/);value=input();value.outcomes[1]=outcome(2,{service:'standard-application',step:61});assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/60-minute/)})

test('unchanged polling, manual reconstruction, absent refusal proof and weak median all fail closed',()=>{for(const mutate of [x=>x.outcomes[0].unchanged_poll_count=1,x=>x.outcomes[0].manual_reconstruction_count=1,x=>x.refusal_evidence=[],x=>{x.baseline.samples=[75,77,79,81,83];x.baseline.median_request_to_live_minutes=79}]){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/polling|reconstruction|refusal|below 50/)}})

test('owner and external waits remain separate and malformed waits refuse',()=>{const value=input();value.outcomes[0].waits[0].kind='internal';assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/unknown wait kind/);const reversed=input();reversed.outcomes[0].waits[0].ended_at='2026-01-01T00:00:00Z';assert.throws(()=>buildFiveOutcomeAcceptanceReport(reversed),/chronological/)})

test('five outcomes must have unique authoritative issue identities',()=>{const value=input();value.cohort.ordered_work_issues[4]=value.cohort.ordered_work_issues[0];assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/five unique/)})

test('live_verified must be exact succeeded and identity-bound',()=>{for(const mutate of [x=>x.outcomes[0].events.at(-1).event_id='e'.repeat(64),x=>x.outcomes[0].lifecycle_identity.work_issue=999,x=>x.outcomes[0].events.at(-1).evidence_urls=[]]){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/identity/)}})

test('refusal proof cannot be filtered, unbound, or attached to another head',()=>{for(const mutate of [x=>x.refusal_evidence=[],x=>delete x.refusal_evidence[0].work_issue,x=>x.refusal_evidence[0].head_sha='c'.repeat(39),x=>x.refusal_evidence[0].evidence_digest='fabricated']){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/refusal/)}})

test('cohort digest detects a fabricated caller sequence',()=>{const value=input();value.cohort.ordered_work_issues.reverse();assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/cohort digest/)})

test('baseline n and median are recomputed from raw samples',()=>{for(const mutate of [x=>x.baseline.n=99,x=>x.baseline.median_request_to_live_minutes=200,x=>x.baseline.samples=[200]]){const value=input();mutate(value);assert.throws(()=>buildFiveOutcomeAcceptanceReport(value),/baseline n|baseline median/)}})
