import assert from 'node:assert/strict'
import test from 'node:test'
import { proposeTrain, validateTrain, transitionTrain, MigrationTrainError } from './migration-train.mjs'
const h=(c,n=40)=>c.repeat(n), entries=(n=10)=>Array.from({length:n},(_,i)=>({version:`20260912${String(i).padStart(6,'0')}`,file_sha256:h((i%9+1).toString(),64),source_pr:100+i,merge_sha:h(((i+1)%9+1).toString()),dependencies:i?[`20260912${String(i-1).padStart(6,'0')}`]:[],risk_class:'ddl-compatible',role:'postgres',preview_assertion:`preview-${i}`,production_assertion:`prod-${i}`}))
function fixture(n=10){const es=entries(n),manifest=proposeTrain({target:'production',target_identity:'project:prod',base_main_sha:h('a'),entries:es}),proof={main_sha:h('a'),target_identity:'project:prod',available_roles:['postgres'],applied_versions:[],main_migrations:{},merge_in_main:{},preview_assertions:{},production_assertions:{}};for(const e of es){proof.main_migrations[e.version]={file_sha256:e.file_sha256,source_pr:e.source_pr,merge_sha:e.merge_sha};proof.merge_in_main[e.merge_sha]=true;proof.preview_assertions[e.version]={assertion:e.preview_assertion,result:'passed'};proof.production_assertions[e.version]={assertion:e.production_assertion,result:'passed'}}return{manifest,proof}}
test('ten compatible migrations form one immutable validated train',()=>{const {manifest,proof}=fixture();assert.equal(validateTrain(manifest,proof).entries.length,10)})
test('missing dependency refuses by migration and dependency',()=>{const {manifest,proof}=fixture(2);manifest.entries[1].dependencies=['20250101000000'];const rebuilt=proposeTrain(manifest);assert.throws(()=>validateTrain(rebuilt,proof),/migration .* missing an earlier dependency 20250101000000/)})
test('superseded migration refuses by name',()=>{const {manifest,proof}=fixture(1);proof.superseded_versions=[manifest.entries[0].version];assert.throws(()=>validateTrain(manifest,proof),/superseded/)})
test('absent database role refuses by name',()=>{const {manifest,proof}=fixture(1);proof.available_roles=[];assert.throws(()=>validateTrain(manifest,proof),/requires absent database role/)})
test('mixed risk classes refuse together',()=>{const {manifest,proof}=fixture(2),es=manifest.entries.map((e,i)=>({...e,risk_class:i?'grant-change':e.risk_class})),mixed=proposeTrain({...manifest,entries:es});assert.throws(()=>validateTrain(mixed,proof),/mixed risk classes/)})
test('stale main, target, hash, merge and assertion proof each refuse',()=>{for(const mutate of [p=>p.main_sha=h('b'),p=>p.target_identity='other',p=>p.main_migrations[Object.keys(p.main_migrations)[0]].file_sha256=h('f',64),p=>p.merge_in_main[Object.keys(p.merge_in_main)[0]]=false,p=>p.preview_assertions[Object.keys(p.preview_assertions)[0]]='wrong']){const {manifest,proof}=fixture(1);mutate(proof);assert.throws(()=>validateTrain(manifest,proof),MigrationTrainError)}})
test('mid-train failure records only an exact proper prefix and recovery is forward-only',()=>{const {manifest,proof}=fixture(3),valid=validateTrain(manifest,proof),refs=new Map(),io={createImmutable:(r,d,x)=>refs.has(r)?false:(refs.set(r,{digest:d,record:x}),true),readImmutable:r=>refs.get(r)};const auth=transitionTrain(valid,'authorized',io,{authorization_digest:h('b',64),current_main_sha:h('a'),target_identity:'project:prod'}),run=transitionTrain(auth,'dispatched',io),failed=transitionTrain(run,'failed',io,{applied_prefix:[manifest.entries[0].version]});assert.deepEqual(failed.applied_prefix,[manifest.entries[0].version]);assert.equal(transitionTrain(failed,'dispatched',io).state,'dispatched');assert.throws(()=>transitionTrain(run,'failed',io,{applied_prefix:[manifest.entries[1].version]}),/exact proper applied prefix/);assert.throws(()=>transitionTrain(run,'authorized',io),/cannot move/)})
test('immutable or stale authorization refuses rather than overwrites',()=>{const {manifest,proof}=fixture(1),valid=validateTrain(manifest,proof),refs=new Map(),io={createImmutable:(r,d,x)=>refs.has(r)?false:(refs.set(r,{digest:d,record:x}),true),readImmutable:r=>refs.get(r)},args={authorization_digest:h('b',64),current_main_sha:h('a'),target_identity:'project:prod'};transitionTrain(valid,'authorized',io,args);assert.throws(()=>transitionTrain(valid,'authorized',io,{...args,authorization_digest:h('c',64)}),/conflicting immutable/);assert.throws(()=>transitionTrain(valid,'authorized',io,{...args,current_main_sha:h('c')}),/exact current main/)})
test('out-of-order train and failed assertion refuse',()=>{const es=entries(2);assert.throws(()=>proposeTrain({target:'production',target_identity:'project:prod',base_main_sha:h('a'),entries:[es[1],es[0]]}),/strictly version ordered/);const {manifest,proof}=fixture(1);proof.preview_assertions[manifest.entries[0].version].result='failed';assert.throws(()=>validateTrain(manifest,proof),/exact passing/)})
