import assert from 'node:assert/strict'
import test from 'node:test'
import {proposeTrain,persistProposedTrain,validateTrain,transitionTrain,MigrationTrainError} from './migration-train.mjs'
const h=(c,n=40)=>c.repeat(n)
const entries=(n=10)=>Array.from({length:n},(_,i)=>({version:`20260912${String(i).padStart(6,'0')}`,file_sha256:h((i%9+1).toString(),64),source_pr:100+i,merge_sha:h(((i+1)%9+1).toString()),dependencies:i?[`20260912${String(i-1).padStart(6,'0')}`]:[],risk_class:'ddl-compatible',role:'postgres',preview_assertion:`preview-${i}`,production_assertion:`prod-${i}`}))
const store=()=>{const refs=new Map();return{refs,createImmutable:(ref,digest,record)=>refs.has(ref)?false:(refs.set(ref,{digest,record:structuredClone(record)}),true),readImmutable:ref=>refs.get(ref)}}
function fixture(n=10){const es=entries(n),manifest=proposeTrain({target:'production',target_identity:'project:prod',base_main_sha:h('a'),entries:es}),proof={main_sha:h('a'),target_identity:'project:prod',available_roles:['postgres'],applied_versions:[],main_migrations:{},merge_in_main:{},preview_assertions:{},production_assertions:{}};for(const e of es){proof.main_migrations[e.version]={file_sha256:e.file_sha256,source_pr:e.source_pr,merge_sha:e.merge_sha};proof.merge_in_main[e.merge_sha]=true;proof.preview_assertions[e.version]={assertion:e.preview_assertion,result:'passed'};proof.production_assertions[e.version]={assertion:e.production_assertion,result:'passed'}}return{manifest,proof}}
function authorized(n=3){const {manifest,proof}=fixture(n),io=store();persistProposedTrain(manifest,io);const valid=validateTrain(manifest,proof),auth=transitionTrain(valid,'authorized',io,{authorization_digest:h('b',64),current_main_sha:h('a'),target_identity:'project:prod'});return{manifest,proof,io,auth}}
const assertions=(es)=>Object.fromEntries(es.map((e)=>[e.version,{file_sha256:e.file_sha256,preview_assertion:e.preview_assertion,preview_result:'passed',production_assertion:e.production_assertion,production_result:'passed'}]))
test('ten compatible migrations form one immutable validated train',()=>{const {manifest,proof}=fixture();assert.equal(validateTrain(manifest,proof).entries.length,10)})
test('dependency, supersession, role, and mixed risk refuse',()=>{let x=fixture(2);x.manifest.entries[1].dependencies=['20250101000000'];assert.throws(()=>validateTrain(proposeTrain(x.manifest),x.proof),/missing an earlier dependency/);x=fixture(1);x.proof.superseded_versions=[x.manifest.entries[0].version];assert.throws(()=>validateTrain(x.manifest,x.proof),/superseded/);x=fixture(1);x.proof.available_roles=[];assert.throws(()=>validateTrain(x.manifest,x.proof),/absent database role/);x=fixture(2);const mixed=proposeTrain({...x.manifest,entries:x.manifest.entries.map((e,i)=>({...e,risk_class:i?'grant-change':e.risk_class}))});assert.throws(()=>validateTrain(mixed,x.proof),/mixed risk/)})
test('stale target, main, hash, merge, and assertion refuse',()=>{for(const mutate of [p=>p.main_sha=h('b'),p=>p.target_identity='other',p=>p.main_migrations[Object.keys(p.main_migrations)[0]].file_sha256=h('f',64),p=>p.merge_in_main[Object.keys(p.merge_in_main)[0]]=false,p=>p.preview_assertions[Object.keys(p.preview_assertions)[0]]='wrong']){const {manifest,proof}=fixture(1);mutate(proof);assert.throws(()=>validateTrain(manifest,proof),MigrationTrainError)}})
test('authorization requires canonical durable predecessor and readback',()=>{const {manifest,proof}=fixture(1),io=store(),valid=validateTrain(manifest,proof),args={authorization_digest:h('b',64),current_main_sha:h('a'),target_identity:'project:prod'};assert.throws(()=>transitionTrain(valid,'authorized',io,args),/predecessor/);persistProposedTrain(manifest,io);const ref=[...io.refs.keys()][0];io.refs.get(ref).record.target='forged';assert.throws(()=>transitionTrain(valid,'authorized',io,args),/predecessor/);io.refs.clear();persistProposedTrain(manifest,io);assert.equal(transitionTrain(valid,'authorized',io,args).generation,2);const lost={createImmutable:()=>true,readImmutable:()=>null};assert.throws(()=>persistProposedTrain(manifest,lost),/readback/)})
test('forged, mutated, or stale lifecycle state cannot dispatch or close',()=>{const {manifest,io,auth}=authorized(1),base={current_main_sha:h('a'),target_identity:'project:prod'};for(const forged of [{...auth,generation:99},{...auth,train_id:h('c',64)},{...auth,entries:[{...auth.entries[0],file_sha256:h('f',64)}]}])assert.throws(()=>transitionTrain(forged,'dispatched',io,base),MigrationTrainError);assert.throws(()=>transitionTrain(auth,'dispatched',io,{...base,current_main_sha:h('c')}),/exact current main/);const fake={...manifest,state:'dispatched',generation:99};assert.throws(()=>transitionTrain(fake,'closed',io,{...base,live_applied_versions:[manifest.entries[0].version],live_assertions:assertions(manifest.entries)}),MigrationTrainError)})
test('failure binds the exact live-ledger proper prefix',()=>{const {manifest,io,auth}=authorized(3),base={current_main_sha:h('a'),target_identity:'project:prod'},run=transitionTrain(auth,'dispatched',io,base),v=manifest.entries.map(e=>e.version);const failed=transitionTrain(run,'failed',io,{...base,applied_prefix:[v[0]],live_applied_versions:[v[0]]});assert.deepEqual(failed.applied_prefix,[v[0]]);for(const x of [{applied_prefix:[v[0]],live_applied_versions:[]},{applied_prefix:[v[0]],live_applied_versions:[v[0],v[1]]},{applied_prefix:[v[1]],live_applied_versions:[v[1]]},{applied_prefix:v,live_applied_versions:v}])assert.throws(()=>transitionTrain(run,'failed',io,{...base,...x}),/proper applied prefix/)})
test('recovery refuses replay and exposes only remaining suffix',()=>{const {manifest,io,auth}=authorized(3),base={current_main_sha:h('a'),target_identity:'project:prod'},run=transitionTrain(auth,'dispatched',io,base),v=manifest.entries.map(e=>e.version),failed=transitionTrain(run,'failed',io,{...base,applied_prefix:[v[0]],live_applied_versions:[v[0]]}),recovery=transitionTrain(failed,'dispatched',io,{...base,live_applied_versions:[v[0]]});assert.deepEqual(recovery.remaining_suffix,[v[1],v[2]]);for(const live_applied_versions of [[],[v[0],v[1]],v])assert.throws(()=>transitionTrain(failed,'dispatched',io,{...base,live_applied_versions}),/unchanged exact live-ledger/)})
test('close requires full live ledger and exact per-migration report',()=>{const {manifest,io,auth}=authorized(2),base={current_main_sha:h('a'),target_identity:'project:prod'},run=transitionTrain(auth,'dispatched',io,base),v=manifest.entries.map(e=>e.version),report=assertions(manifest.entries);for(const live_applied_versions of [[],[v[0]]])assert.throws(()=>transitionTrain(run,'closed',io,{...base,live_applied_versions,live_assertions:report}),/exact full train/);assert.throws(()=>transitionTrain(run,'closed',io,{...base,live_applied_versions:v,live_assertions:{...report,extra:report[v[0]]}}),/one report/);const bad=structuredClone(report);bad[v[0]].production_result='failed';assert.throws(()=>transitionTrain(run,'closed',io,{...base,live_applied_versions:v,live_assertions:bad}),/exact live assertion/);assert.equal(transitionTrain(run,'closed',io,{...base,live_applied_versions:v,live_assertions:report}).state,'closed')})
test('out-of-order train and failed assertion refuse',()=>{const es=entries(2);assert.throws(()=>proposeTrain({target:'production',target_identity:'project:prod',base_main_sha:h('a'),entries:[es[1],es[0]]}),/strictly version ordered/);const {manifest,proof}=fixture(1);proof.preview_assertions[manifest.entries[0].version].result='failed';assert.throws(()=>validateTrain(manifest,proof),/exact passing/)})
