import test from 'node:test';import assert from 'node:assert/strict'
import { readyRecord,persistInitialReady,preparePreviewDispatch,terminalizeReady,repairPreviewReady,reconcileFlow,ReconcileError } from './reconcile.mjs'
import { githubIo, main as managerMain } from '../manage-migration-author-lanes.mjs'
const h='a'.repeat(40),b='b'.repeat(64),base={issue:7,pr:8,head_sha:h,bundle_id:b,route:'ordinary_preview_apply',route_context:'',manifest:{target:'preview',preview_allowlist:'v',claim_pr:'8',claim_head_sha:h}}
function fake(){const refs=new Map(),eventLog=[],state={current:base,ready:[]};return{state,refs,eventLog,resolveMarker:()=>({live:true,task:'t',calling_task:'t'}),actor:()=> 't',now:()=>new Date(0).toISOString(),appendEvent:e=>eventLog.push(e),createRef:(r,d,record)=>refs.has(r)?false:(refs.set(r,{digest:d,record}),true),readRef:r=>refs.get(r),listReady:()=>state.ready,selectCurrent:()=>state.current,withMutex:f=>f(),events:()=>eventLog}}
test('ready identity changes with every safety identity input',()=>{const one=readyRecord(base);for(const [key,value] of [['issue',9],['head_sha','c'.repeat(40)],['bundle_id','d'.repeat(64)],['route','merged_rehearsal'],['route_context','e'.repeat(40)]]){const candidate={...base,[key]:value};if(key==='route')candidate.route_context='e'.repeat(40);if(key==='route_context')candidate.route='merged_rehearsal';if(candidate.route==='merged_rehearsal')candidate.manifest={target:'preview',preview_allowlist:'v',commit_sha:'f'.repeat(40),merged_preview_source_pr:'8'};assert.notEqual(readyRecord(candidate).ready_id,one.ready_id)}})
test('event is written before immutable ready ref and retry is idempotent',()=>{const io=fake(),order=[];io.appendEvent=e=>{order.push('event');io.eventLog.push(e)};const create=io.createRef;io.createRef=(...a)=>{order.push('ref');return create(...a)};const a=persistInitialReady(base,io),c=persistInitialReady(base,io);assert.deepEqual(order.slice(0,2),['event','ref']);assert.equal(a.record.ready_id,c.record.ready_id)})
test('preparation creates successor before stale terminal outcome',()=>{const io=fake(),old=readyRecord(base);io.state.ready=[{record:old}];persistInitialReady(base,io);io.state.current={...base,head_sha:'c'.repeat(40)};const newer=readyRecord(io.state.current);io.state.ready.push({record:newer});const result=preparePreviewDispatch(7,io);assert.equal(result.record.ready_id,newer.ready_id);assert.equal(io.refs.get(`refs/db-preview-ready-outcomes/${old.ready_id}`).record.outcome,'superseded')})
test('only completing apply evidence can terminalize dispatched',()=>{const io=fake();assert.throws(()=>terminalizeReady('x','dispatched',{positive:true,mode:'dry-run'},io),ReconcileError);assert.equal(terminalizeReady('x','dispatched',{positive:true,mode:'apply'},io).outcome,'dispatched')})
test('repair refuses corrupt live identity without a write',()=>{const io=fake(),id=readyRecord(base).ready_id;persistInitialReady(base,io);const before=io.refs.size;assert.throws(()=>repairPreviewReady(id,7,io),/owner decision/);assert.equal(io.refs.size,before)})
test('no matching marker is report only',()=>{const io=fake();io.resolveMarker=()=>null;const result=reconcileFlow({issues:[{issue:7,preview_edge_satisfied:true}]},io);assert.equal(result.status,'REPORT_ONLY');assert.equal(result.actions[0].action,'report-preview-ready')})
test('matching marker performs guarded transitions rather than only describing them',()=>{const io=fake(),called=[];io.relinquishCapacity=(row)=>called.push(['relinquish',row.issue]);io.resumeCapacity=(row)=>called.push(['resume',row.issue]);io.persistReady=(row)=>called.push(['ready',row.issue]);const result=reconcileFlow({issues:[{issue:1,capacity_state:'active',blocker:{durable:true}},{issue:2,capacity_state:'relinquished',blocker:{resolved:true}},{issue:3,preview_edge_satisfied:true}]},io);assert.equal(result.status,'RECONCILED');assert.deepEqual(called,[['relinquish',1],['resume',2],['ready',3]])})
test('unreadable live preview evidence is explicit and fails closed',()=>{const io=fake(),result=reconcileFlow({issues:[{issue:7,preview_error:'required CI unreadable'}]},io);assert.equal(result.status,'UNVERIFIABLE');assert.equal(result.actions[0].reason,'required CI unreadable')})
test('manager exposes a concrete runtime adapter and delegates preparation',()=>{assert.equal(typeof githubIo.orchestratorFlowAdapter,'function');const adapter=fake();adapter.state.ready=[{record:readyRecord(base)}];const io={orchestratorFlowAdapter:()=>adapter};assert.equal(managerMain(['--prepare-preview-dispatch','7'],new Date(),io),0)})
