import assert from 'node:assert/strict'
import test from 'node:test'
import { allocateReviewer, approvedExecutionCandidates, executionKey, wakeOldestCompatibleWait } from './reviewer-allocation.mjs'

const active=[{name:'grok',wrapper:'ai-grok',provider:'grok'},{name:'glm-a',wrapper:'ai-glm',provider:'glm'},{name:'glm-alias',wrapper:'ai-glm',provider:'glm'}],overflow=[{name:'codex',wrapper:'ai-codex',provider:'codex'}]
const request=(issue=1)=>({issue,pr:issue+10,head_sha:'a'.repeat(40),bundle_id:'b'.repeat(64)})
function ioFixture(){const reservations=new Map(),waits=[];let sequence=0;return {reservations,waits,readReservation:(key)=>reservations.get(key),createReservation:(ref,digest,record)=>{if(reservations.has(record.execution_key))return false;reservations.set(record.execution_key,{ref,digest,record});return true},withMutex:(fn)=>fn(),nextWaitSequence:()=>++sequence,createWait:(ref,digest,record)=>{waits.push({ref,digest,record,terminal:false});return true},listWaits:()=>waits,liveReviewIdentity:(issue,pr)=>({issue,pr,head_sha:'a'.repeat(40),bundle_id:'b'.repeat(64)}),claimWait:(wait)=>{if(wait.claimed)return false;wait.claimed=true;return true},assignClaimedWait:(wait,key)=>({wait,key}),supersedeWait:(wait)=>{wait.terminal=true}}}

test('aliases sharing one provider/wrapper have one canonical execution key',()=>{assert.equal(executionKey(active[1]),executionKey(active[2]));assert.equal(approvedExecutionCandidates({active}).length,2)})
test('distinct execution keys reserve concurrently without a global execution lock',()=>{const io=ioFixture();const first=allocateReviewer(request(1),{active,overflow},io),second=allocateReviewer(request(2),{active,overflow},io);assert.equal(first.status,'assigned');assert.equal(second.status,'assigned');assert.notEqual(first.execution_key,second.execution_key)})
test('active reviewers precede overflow and arbitrary inactive names are absent',()=>{const candidates=approvedExecutionCandidates({active,overflow,prohibited:['glm-a']});assert.equal(candidates[0].name,'grok');assert.equal(candidates.at(-1).name,'codex');assert.ok(!candidates.some((row)=>row.name==='unknown'))})
test('all busy creates an ordered durable wait, never a duplicate busy assignment',()=>{const io=ioFixture();for(const reviewer of approvedExecutionCandidates({active,overflow}))io.reservations.set(reviewer.execution_key,{});const first=allocateReviewer(request(1),{active,overflow},io),second=allocateReviewer(request(2),{active,overflow},io);assert.equal(first.status,'review-wait');assert.equal(second.record?.status,undefined);assert.ok(first.wait_id<second.wait_id)})
test('exact execution-context denial is process-local and not persisted',()=>{const io=ioFixture();const selected=allocateReviewer(request(),{active,overflow,context_denied:['grok']},io);assert.notEqual(selected.reviewer,'grok');assert.equal(approvedExecutionCandidates({active,overflow})[0].name,'grok')})
test('two wakers claim an oldest compatible wait exactly once',()=>{const io=ioFixture();for(const reviewer of approvedExecutionCandidates({active,overflow}))io.reservations.set(reviewer.execution_key,{});const wait=allocateReviewer(request(),{active,overflow},io);const key=wait.eligible_execution_keys[0];assert.ok(wakeOldestCompatibleWait(key,io));assert.equal(wakeOldestCompatibleWait(key,io),null)})
