import assert from 'node:assert/strict'
import test from 'node:test'
import { reviewerStartDecision,runnerStartDecision,acceptRunnerResult,StartRerouteError } from './start-reroute.mjs'
const h='a'.repeat(40),at='2026-09-11T10:00:00Z',late='2026-09-11T10:11:00Z',assignment={id:'r1',head_sha:h,assigned_at:at}
test('unavailable, quarantined, and durably unstarted reviewers reroute once after the SLO',()=>{for(const state of ['unusable','quarantined','confirmed-not-started'])assert.equal(reviewerStartDecision(assignment,{now:late,provider_state:state}).action,'governed-return-and-reroute');assert.throws(()=>reviewerStartDecision(assignment,{now:late,provider_state:'unusable',replacement_exists:true}),/exactly once/)})
test('durable provider lifecycle keeps a quiet active review intact',()=>{assert.equal(reviewerStartDecision(assignment,{now:late,provider_state:'confirmed-not-started',lifecycle:[{assignment_id:'r1',type:'provider_contacted',at:'2026-09-11T10:01:00Z'}]}).action,'keep-active')})
test('uncertain paid review refuses replacement',()=>{assert.throws(()=>reviewerStartDecision(assignment,{now:late,provider_state:'remote-unknown'}),/preserve the lease/)})
test('terminal format drift uses same-session clarification',()=>{assert.equal(reviewerStartDecision(assignment,{now:late,provider_state:'usable',lifecycle:[{assignment_id:'r1',type:'terminal_format_invalid',at:late}]}).action,'same-session-clarification')})
const attempt={id:'run1',workflow:'contract',lane:'preferred',head_sha:h,queued_at:at,required_assertions:['sql','contract']},lanes=[{name:'fallback',qualified:true,assertions:['contract','sql']}]
test('unpicked runner gets one new qualified full-coverage run',()=>{const decision=runnerStartDecision(attempt,{now:late,qualified_lanes:lanes});assert.equal(decision.action,'dispatch-new-run');assert.deepEqual(decision.required_assertions,attempt.required_assertions);assert.throws(()=>runnerStartDecision(attempt,{now:late,qualified_lanes:lanes,replacement_exists:true}),/exactly once/)})
test('started runner remains active and incomplete fallback refuses',()=>{assert.equal(runnerStartDecision(attempt,{now:late,lifecycle:[{attempt_id:'run1',type:'runner_started',at:'2026-09-11T10:02:00Z'}],qualified_lanes:lanes}).action,'keep-active');assert.throws(()=>runnerStartDecision(attempt,{now:late,qualified_lanes:[{name:'bad',qualified:true,assertions:['sql']}]}),/preserves every assertion/)})
test('accepted assertion result is compare-and-create exactly once',()=>{const refs=new Map(),io={createAccepted:(r,d,x)=>refs.has(r)?false:(refs.set(r,{digest:d,result:x}),true),readAccepted:r=>refs.get(r)},result={attempt_id:'run2',workflow:'contract',head_sha:h,result_digest:'b'.repeat(64),assertions:[{name:'sql',result:'passed'},{name:'contract',result:'passed'}]};assert.equal(acceptRunnerResult(result,io).accepted,true);assert.equal(acceptRunnerResult(result,io).accepted,true);assert.throws(()=>acceptRunnerResult({...result,attempt_id:'late',result_digest:'c'.repeat(64)},io),/already accepted/);assert.throws(()=>acceptRunnerResult({...result,assertions:[{name:'sql',result:'failed'}]},io),StartRerouteError)})
