import assert from 'node:assert/strict'
import test from 'node:test'
import { reviewerStartDecision,runnerStartDecision,reserveReviewerReroute,reserveRunnerReroute,acceptRunnerResult,createDurableStartRerouteAdapter,dispatchQueuedReroute } from './start-reroute.mjs'
import { canonicalJson,sha256 } from './evidence-bundle.mjs'
const h='a'.repeat(40),at='2026-09-11T10:00:00Z',late='2026-09-11T10:11:00Z',assignment={id:'r1',head_sha:h,assigned_at:at}
const store=()=>{const refs=new Map(),claims=new Map(),acks=new Map(),dispatches=new Map(),live={reviewer:{now:late,provider_state:'unusable',lifecycle:[]},runner:{now:late,lifecycle:[],qualified_lanes:lanes}},durable={withMutex:f=>f(),readPair:r=>refs.get(r),compareCreatePair:(r,expected,pair)=>refs.has(r)?false:(refs.set(r,pair),true),readLive:kind=>live[kind],createAccepted:(r,d,x)=>refs.has(r)?false:(refs.set(r,{digest:d,result:x}),true),readAccepted:r=>refs.get(r),readDispatchAck:r=>acks.get(r),compareCreateDispatchClaim:(r,x)=>claims.has(r)?false:(claims.set(r,x),true),readDispatchClaim:r=>claims.get(r),dispatchReplacement:(id,record)=>dispatches.has(id)?{status:'existing',reroute_id:id,replacement_id:dispatches.get(id).replacement_id}:(dispatches.set(id,record),{status:'created',reroute_id:id,replacement_id:record.replacement_id}),compareCreateDispatchAck:(r,x)=>acks.has(r)?false:(acks.set(r,x),true)};return{refs,claims,acks,dispatches,live,durable,io:createDurableStartRerouteAdapter(durable)}}
test('unavailable, quarantined, and durably unstarted reviewers become reroute candidates after the SLO',()=>{for(const state of ['unusable','quarantined','confirmed-not-started'])assert.equal(reviewerStartDecision(assignment,{now:late,provider_state:state}).action,'governed-return-and-reroute')})
test('durable provider lifecycle keeps a quiet active review intact',()=>{assert.equal(reviewerStartDecision(assignment,{now:late,provider_state:'confirmed-not-started',lifecycle:[{assignment_id:'r1',type:'provider_contacted',at:'2026-09-11T10:01:00Z'}]}).action,'keep-active')})
test('uncertain paid review refuses replacement',()=>{assert.throws(()=>reviewerStartDecision(assignment,{now:late,provider_state:'remote-unknown'}),/preserve the lease/)})
test('terminal format drift uses same-session clarification',()=>{assert.equal(reviewerStartDecision(assignment,{now:late,provider_state:'usable',lifecycle:[{assignment_id:'r1',type:'terminal_format_invalid',at:late}]}).action,'same-session-clarification')})
const attempt={id:'run1',workflow:'contract',lane:'preferred',head_sha:h,queued_at:at,required_assertions:['sql','contract']},lanes=[{name:'fallback',qualified:true,assertions:['contract','sql']}]
test('unpicked runner gets a qualified exact-coverage candidate',()=>{const decision=runnerStartDecision(attempt,{now:late,qualified_lanes:lanes});assert.equal(decision.action,'dispatch-new-run');assert.deepEqual(decision.required_assertions,['contract','sql'])})
test('started runner remains active and incomplete fallback refuses',()=>{assert.equal(runnerStartDecision(attempt,{now:late,lifecycle:[{attempt_id:'run1',type:'runner_started',at:'2026-09-11T10:02:00Z'}],qualified_lanes:lanes}).action,'keep-active');assert.throws(()=>runnerStartDecision(attempt,{now:late,qualified_lanes:[{name:'bad',qualified:true,assertions:['sql']}]}),/preserves every assertion/)})
test('concurrent reviewer reroutes queue one immutable replacement',()=>{const s=store(),decision=reviewerStartDecision(assignment,{now:late,provider_state:'unusable'}),replacement={id:'r2',provider:'muse'};assert.equal(reserveReviewerReroute(assignment,decision,replacement,s.io).status,'queued');assert.equal(reserveReviewerReroute(assignment,decision,replacement,s.io).status,'existing');assert.equal(s.dispatches.size,0);assert.throws(()=>reserveReviewerReroute(assignment,decision,{id:'r3',provider:'glm'},s.io),/different reviewer replacement/)})
test('concurrent runner reroutes queue one immutable replacement',()=>{const s=store(),decision=runnerStartDecision(attempt,{now:late,qualified_lanes:lanes});assert.equal(reserveRunnerReroute(attempt,decision,{id:'run2'},s.io).status,'queued');assert.equal(reserveRunnerReroute(attempt,decision,{id:'run2'},s.io).status,'existing');assert.equal(s.dispatches.size,0);assert.throws(()=>reserveRunnerReroute(attempt,decision,{id:'run3'},s.io),/different runner replacement/)})
test('queue acknowledgement binds reroute and replacement ids',()=>{const s=store(),decision=runnerStartDecision(attempt,{now:late,qualified_lanes:lanes});s.io.compareCreateRerouteAndReplacement=()=>({status:'queued',reroute_id:'wrong',replacement_id:'run2'});assert.throws(()=>reserveRunnerReroute(attempt,decision,{id:'run2'},s.io),/queue acknowledgement/)})
test('reviewer start or paid-state uncertainty arising during reservation refuses before dispatch',()=>{for(const change of [s=>s.live.reviewer.lifecycle.push({assignment_id:'r1',type:'provider_contacted',at:late}),s=>s.live.reviewer.provider_state='remote-unknown']){const s=store(),decision=reviewerStartDecision(assignment,{now:late,provider_state:'unusable'}),atomic=s.io.compareCreateRerouteAndReplacement;s.io.compareCreateRerouteAndReplacement=(request)=>{change(s);return atomic(request)};assert.throws(()=>reserveReviewerReroute(assignment,decision,{id:'r2',provider:'muse'},s.io),/started or changed|preserve the lease/);assert.equal(s.dispatches.size,0);assert.equal(s.refs.size,0)}})
test('runner start arising during reservation refuses before dispatch',()=>{const s=store(),decision=runnerStartDecision(attempt,{now:late,qualified_lanes:lanes}),atomic=s.io.compareCreateRerouteAndReplacement;s.io.compareCreateRerouteAndReplacement=(request)=>{s.live.runner.lifecycle.push({attempt_id:'run1',type:'runner_started',at:late});return atomic(request)};assert.throws(()=>reserveRunnerReroute(attempt,decision,{id:'run2'},s.io),/started or changed/);assert.equal(s.dispatches.size,0);assert.equal(s.refs.size,0)})
test('durable adapter persists reservation and queue acknowledgement in one CAS record',()=>{const s=store(),decision=runnerStartDecision(attempt,{now:late,qualified_lanes:lanes}),result=reserveRunnerReroute(attempt,decision,{id:'run2'},s.io),pair=s.durable.readPair(result.ref);assert.equal(pair.digest,result.reroute_id);assert.equal(pair.record.replacement_id,'run2');assert.deepEqual(pair.queue,{status:'queued',reroute_id:result.reroute_id,replacement_id:'run2'});assert.equal(s.refs.size,1);assert.equal(s.dispatches.size,0)})
test('lost queue response retries before changed lifecycle and still has not fabricated dispatch',()=>{const s=store(),decision=runnerStartDecision(attempt,{now:late,qualified_lanes:lanes}),original=s.durable.compareCreatePair;let lost=true;s.durable.compareCreatePair=(...args)=>{const created=original(...args);if(created&&lost){lost=false;throw new Error('response lost')}return created};assert.throws(()=>reserveRunnerReroute(attempt,decision,{id:'run2'},s.io),/response lost/);s.live.runner.lifecycle.push({attempt_id:'run1',type:'runner_started',at:late});const recovered=reserveRunnerReroute(attempt,decision,{id:'run2'},s.io);assert.equal(recovered.status,'existing');assert.equal(s.refs.size,1);assert.equal(s.dispatches.size,0)})
test('downstream worker dispatches each queued paid review or runner once and persists exact ack',()=>{for(const kind of ['reviewer','runner']){const s=store(),queued=kind==='reviewer'?reserveReviewerReroute(assignment,reviewerStartDecision(assignment,{now:late,provider_state:'unusable'}),{id:'r2',provider:'muse'},s.io):reserveRunnerReroute(attempt,runnerStartDecision(attempt,{now:late,qualified_lanes:lanes}),{id:'run2'},s.io);assert.equal(dispatchQueuedReroute(queued.ref,s.durable).status,'acknowledged');assert.equal(dispatchQueuedReroute(queued.ref,s.durable).status,'existing');assert.equal(s.dispatches.size,1);assert.equal(s.acks.size,1)}})
test('lost dispatch acknowledgement retries idempotently without duplicate external dispatch',()=>{const s=store(),queued=reserveRunnerReroute(attempt,runnerStartDecision(attempt,{now:late,qualified_lanes:lanes}),{id:'run2'},s.io),original=s.durable.compareCreateDispatchAck;let lost=true;s.durable.compareCreateDispatchAck=(...args)=>{const created=original(...args);if(created&&lost){lost=false;throw new Error('ack response lost')}return created};assert.throws(()=>dispatchQueuedReroute(queued.ref,s.durable),/ack response lost/);assert.equal(dispatchQueuedReroute(queued.ref,s.durable).status,'existing');assert.equal(s.dispatches.size,1);assert.equal(s.acks.size,1)})
const sealedResult=(reservation,assertionRows=[{name:'sql',result:'passed'},{name:'contract',result:'passed'}])=>{const identity={attempt_id:'run2',supersedes_attempt_id:'run1',reroute_id:reservation.reroute_id,workflow:'contract',lane:'fallback',head_sha:h,assertions:[...assertionRows].sort((a,b)=>a.name.localeCompare(b.name))};return{...identity,result_digest:sha256(canonicalJson(identity))}}
test('accepted result binds exact requirements and supersession chain',()=>{const s=store(),decision=runnerStartDecision(attempt,{now:late,qualified_lanes:lanes}),reservation=reserveRunnerReroute(attempt,decision,{id:'run2'},s.io),result=sealedResult(reservation);assert.equal(acceptRunnerResult(result,attempt,s.io).accepted,true);assert.equal(acceptRunnerResult(result,attempt,s.io).accepted,true);assert.throws(()=>acceptRunnerResult({...result,attempt_id:'foreign'},attempt,s.io),/immutable reroute/);assert.throws(()=>acceptRunnerResult({...result,workflow:'foreign'},attempt,s.io),/original workflow/);assert.throws(()=>acceptRunnerResult(sealedResult(reservation,[{name:'sql',result:'passed'}]),attempt,s.io),/exact original assertion set/);assert.throws(()=>acceptRunnerResult(sealedResult(reservation,[...result.assertions,{name:'bonus',result:'passed'}]),attempt,s.io),/exact original assertion set/);assert.throws(()=>acceptRunnerResult({...result,supersedes_attempt_id:'other'},attempt,s.io),/original workflow/);assert.throws(()=>acceptRunnerResult({...result,lane:'foreign'},attempt,s.io),/immutable reroute/);assert.throws(()=>acceptRunnerResult({...result,result_digest:'c'.repeat(64)},attempt,s.io),/canonical digest/)})
test('failing and duplicate assertion results refuse',()=>{const s=store(),decision=runnerStartDecision(attempt,{now:late,qualified_lanes:lanes}),reservation=reserveRunnerReroute(attempt,decision,{id:'run2'},s.io);assert.throws(()=>acceptRunnerResult(sealedResult(reservation,[{name:'sql',result:'failed'},{name:'contract',result:'passed'}]),attempt,s.io),/exact original assertion set/);assert.throws(()=>acceptRunnerResult(sealedResult(reservation,[{name:'sql',result:'passed'},{name:'sql',result:'passed'}]),attempt,s.io),/exact original assertion set/)})
